### ISSUE TITLE
拖动会卡顿

### ISSUE THREAD

**Issue by whkrain** [zhiyiYo/PyQt-Frameless-Window#10]
不知道从什么时候开始，Win10上拖动位置窗口会慢慢悠悠的移动过去？

**Comment by zhiyiYo** [comment]
是不是开了亚克力效果啊

**Comment by whkrain** [comment]
> 是不是开了亚克力效果啊

对 但是我记得之前开了也没问题。难道我记错了？

**Comment by zhiyiYo** [comment]
Win10 好像一直都有问题，Win11 修复了拖动问题，但是拉伸还是没有解决

**Comment by zhiyiYo** [comment]
> > 是不是开了亚克力效果啊
> 
> 对 但是我记得之前开了也没问题。难道我记错了？

可能你之前拖动窗口的时候没有显示窗口内容？

**Comment by whkrain** [comment]
> 

我也记不清了。。但是当时我试了几个方案，你这个效果最好。就用了，最近突然发现这个问题，我都怀疑是不是某次win10更新导致的。

**Comment by zhiyiYo** [comment]
升级到 Win11 解决问题😕

**Comment by whkrain** [comment]
> 升级到 Win11 解决问题😕

好的 谢谢

**Comment by citizenll** [comment]
> > 升级到 Win11 解决问题😕
> 
> 好的 谢谢

win10这个就不解决了吗，win10还是有很多用户呀

**Comment by zhiyiYo** [comment]
> win10这个就不解决了吗，win10还是有很多用户呀

对不起，做不到
