### ISSUE TITLE
可变标题栏高度

### ISSUE THREAD

**Issue by wuyuanyi135** [zhiyiYo/PyQt-Frameless-Window#100]
现在的标题栏按钮是采用硬编码的方式画出最小最大化窗口，并用一个svg图像来显示关闭窗口按钮。再修改了标题栏高度后硬编码画出的坐标会略有偏移。建议采用相对坐标绘制线条以实现保持居中的效果。
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/11760870/7e655c63-f070-46f2-b0f2-91041b98f061)

**Comment by 17Reset** [comment]
请问你是如何将标题栏变为黑色的？

**Comment by zhiyiYo** [comment]
32px 是 Windows 标准的标题栏高度，所以代码中直接硬编码了坐标。如果希望调整高度，需要自己更换图标
