### ISSUE TITLE
添加QWebEngine后，窗体最大化后有一圈白色边框

### ISSUE THREAD

**Issue by zhaochengyang123** [zhiyiYo/PyQt-Frameless-Window#101]
**Describe the bug**
在example-gallery-demo页面添加一个PivotInterface，然后添加QWebEngine后，运行后framelesswindow主窗体四个角由圆角变为直角，最大化后不能全屏，有一圈白色边框

**Environment**
 - OS: Windows11
 - DPI scaling: 100%
 - Python: 3.11 64-bit
 - PySide6: 6.4.2

![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/59644033/d07baefc-0205-4aae-825d-541f8af30f04)

**Comment by zhiyiYo** [comment]
有最小复现代码吗？这个应该和 gallery 没有关系

**Comment by zhaochengyang123** [comment]
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/59644033/c204676e-ead3-48c0-8e5e-cec212c9bfb4)
就给example-gallery，homeinterface.py添加了两条代码，添加qwebengine控件后就这样了
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/59644033/299555e6-fccd-436d-9dd8-68bbac2327b6)

**Comment by zhaochengyang123** [comment]
> 有最小复现代码吗？这个应该和 gallery 没有关系

大佬见3楼

**Comment by zhiyiYo** [comment]
PyQt 挺正常的

**Comment by zhaochengyang123** [comment]
> PyQt 挺正常的

pyside6不能正常用了嘛，是不是只能用pyqt

**Comment by zhiyiYo** [comment]
或者试下 pyside2 有没有这个问题，如果不商用的话 pyqt 也可以
