### ISSUE TITLE
WindowStaysOnTopHint breaks the titlebar

### ISSUE THREAD

**Issue by rllysleepy** [zhiyiYo/PyQt-Frameless-Window#102]
**Describe the bug**
When using `self.setWindowFlags(Qt.WindowType.WindowStaysOnTopHint)`, the window will have two title bars. Adding `self.titleBar.hide()` only removes one of the title bars, and leaves behind a disabled titlebar.

**Environment**
 - OS: Windows11
 - DPI scaling: 200%
 - Python: 3.10.11
 - PyQt6

**Code**
```python
import sys
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *
from qframelesswindow import *

class MainWindow(AcrylicWindow):
    def __init__(self, *args, parent=None):
        super().__init__(*args, parent=parent)
        self.setWindowFlags(Qt.WindowType.WindowStaysOnTopHint)
        self.titleBar.hide()

app = QApplication(sys.argv)
window = MainWindow()
window.show()
sys.exit(app.exec())
```

**Expected behavior**
There should only be one title bar, and it should be hidden.

**Screenshots**
2 Titlebars when not hidden
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/94653795/a626aaff-577f-4647-91c7-658b3466cd1f)

1 Disabled Titlebar when hidden
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/94653795/11610297-224e-4b2b-9b08-7b3742598f5d)

**Comment by zhiyiYo** [comment]
```python
class MainWindow(AcrylicWindow):
    def __init__(self, *args, parent=None):
        super().__init__(*args, parent=parent)
        self.setWindowFlags(self.windowFlags()| Qt.WindowType.WindowStaysOnTopHint)

        self.windowEffect.enableBlurBehindWindow(self.winId())
        self.windowEffect.addWindowAnimation(self.winId())
        self.windowEffect.setAcrylicEffect(self.winId())
        if sys.platform == 'win32' and sys.getwindowsversion().build >= 22000:
            self.windowEffect.addShadowEffect(self.winId())
```

**Comment by rllysleepy** [comment]
Works great! Thank you!
It looks like what's happening is that I'm deleting the `FramelessWindowHint` flag, which causes the extra titlebar. Very smart solution with giving the window blur and acrylic effect back, very cool :)
