### ISSUE TITLE
Support for Acrylic Dialog

### ISSUE THREAD

**Issue by rllysleepy** [zhiyiYo/PyQt-Frameless-Window#103]
I tried making an acrylic dialog, but it didn't work; instead, it just gave me a solid white window.
```python
class AcrylicDialog(QDialog, AcrylicWindow):
    def __init__(self, title="", content=None, parent=None):
        super().__init__(parent=parent)
```
How can I implement this? Will it ever be added as a feature?

**Comment by zhiyiYo** [comment]
```python
self.setStyleSheet("Window{background:transparent}")
```

**Comment by rllysleepy** [comment]
Also; the dialog window needs to be its own window; it cannot have a parent, because the window ID will be the same as its parent. That breaks the Acrylic effect and other window effects.
