### ISSUE TITLE
the frameless window will lose about 5~10 pixels on the right border when maximized.

### ISSUE THREAD

**Issue by ShadowGuan** [zhiyiYo/PyQt-Frameless-Window#104]
**Describe the bug**
before maxmized:
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/21018699/37275415-528e-4ad4-a236-23ead12e5d7d)
after maxmized:
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/21018699/4e8e9218-e256-4d7c-8aee-0a240509dad3)

you can clearly see that the  close button is not fully displayed.
it's very obvious for the widgets in the window, which are close to  the right border or have a margin.

for example:
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/21018699/e721db12-e5e9-497e-a4b2-640f88830af1)
you can see the right margin of the white box has been eaten.

**Environment**
 - OS: Windows11
 - DPI scaling: 200%
 - Python: 3.8.7
 - PySide6: 6.5.1.1

**To Reproduce**
Steps to reproduce the behavior(you can use GIF to demonstrate :):
create any frameless window and maximize it.

**Comment by ShadowGuan** [comment]
最大化之后，右边总会少几个像素，
我猜测跟拉伸的把手相关。

一开始我还以为是我继承实现的窗口和title bar有问题，
花了一天时间排查，才发现是库本身存在的问题。

真是一个悲伤的故事。。。

**Comment by zhiyiYo** [comment]
换成 6.4.2 吧
