### ISSUE TITLE
关于窗口边框

### ISSUE THREAD

**Issue by St-Luo** [zhiyiYo/PyQt-Frameless-Window#105]
今天找ChatGPT问了一些关于窗口边框的问题，本以为会答非所问，但它却给了一个我比较满意的代码：

    import sys
    
    import win32con
    import win32gui
    from PyQt5.QtWidgets import QApplication, QMainWindow
    
    
    class Window(QMainWindow):
        def __init__(self):
            super().__init__()
    
            hwnd = int(self.winId())
    
            win32gui.SetWindowLong(hwnd, win32con.GWL_STYLE,
                                   win32gui.GetWindowLong(hwnd, win32con.GWL_STYLE) & ~win32con.WS_CAPTION)
    
    
    if __name__ == '__main__':
        app = QApplication(sys.argv)
        window = Window()
        window.show()
        sys.exit(app.exec_())

![图片](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/75152171/67770508-a5e9-40ef-822e-7e0dc61efda1)

这个窗口有阴影，可以改变大小（可以在阴影处改变大小，不用将鼠标放在窗口内），这个窗口还有边框
除了没有标题栏、移动窗口和动画效果外，其他和普通窗口没两样
唯一的问题就是顶部边框粗细不对
如果解决了边框粗细问题，就可以用这个方法解决主题色的问题了

**Comment by zhiyiYo** [comment]
这个看起来和 Qt 的 CustomWindowHint 效果一样
