### ISSUE TITLE
Frameless window not Working with QtDesigner 

### ISSUE THREAD

**Issue by The-VoyZ** [zhiyiYo/PyQt-Frameless-Window#106]
**Describe the bug**
The App wont start if i use a QtDesigner Ui File. 

**Environment**
 - OS: Windows10
 - Python: Python 3.11
 - PyQt6 6.5.1

**To Reproduce**
Imported a UI class from QtDesigner. 
And Tryed the Frameless window on it. 

i get this error : 
  File "c:\Users\User\Desktop\Testing\main_window.py", line 27, in <module>
    demo = Window()
           ^^^^^^^^
  File "c:\Users\User\Desktop\Testing\main_window.py", line 22, in __init__
    self.setupUi(self)
  File "c:\Users\User\Desktop\Testing\mainwindow.py", line 639, in setupUi
    MainWindow.setCentralWidget(self.centralwidget)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'setCentralWidget'. Did you mean: 'centralwidget'?

**Code**
import sys
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import Qt 
from mainwindow import *
import resources_rc

from qframelesswindow import FramelessWindow

class Window(FramelessWindow, Ui_MainWindow):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec())

**Expected behavior**
the File should atleast start

the Ui file is here: 
as a .txt just import it into a .py file :)
[Mainwindow_ui.py.txt](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/11917667/Mainwindow_ui.py.txt)

**Comment by zhiyiYo** [comment]
You should use `FramelessMainWindow`, please check the examples.
