### ISSUE TITLE
Transfer of PyPI package name

### ISSUE THREAD

**Issue by rayzchen** [zhiyiYo/PyQt-Frameless-Window#107]
A while ago when this project was only for PyQt5, I forked it and converted it to be compatible with PySide6. Since then, you have wonderfully maintained this project for multiple Qt packages, one of which (`Pysidesix-Frameless-Window`) had to be renamed because I had already released a package called `Pyside6-Frameless-Window`. Are you willing to use this package name if I delete it? I am no longer maintaining my fork anyways.

**Comment by zhiyiYo** [comment]
I have published `PySideSix-Frameless-Window` on pypi and it's a dependency of PySide6-Fluent-Widgets, so I will not change the package name
