### ISSUE TITLE
mica effect

### ISSUE THREAD

**Issue by 309GXW** [zhiyiYo/PyQt-Frameless-Window#110]
主函数调用登陆窗口时提示报错，该怎么解决。UserWarning: The mica effect is only available on Win11 warnings.warn("The mica effect is only available on Win11")

**Comment by zhiyiYo** [comment]
这不是写的很清楚吗，只在 Win11 可以用，可以换成亚克力效果

**Comment by 309GXW** [comment]
为什么在模块内直接调用时候可以运行，没有报错
