### ISSUE TITLE
OpenGL removes window-effect from FramelessWindow, PySide6

### ISSUE THREAD

**Issue by Ndeh-007** [zhiyiYo/PyQt-Frameless-Window#113]
I am not sure if this counts as a bug or a feature issue.

**Description of Issue**
When adding (at runtime) a new widget(QOpenGLWidget or OpenGL Components from pyqtgraph.opengl) that carries OpenGL components to an already existing window created with FrameslessWindow, the application reloads itself and the properties of FramelessWindow window-effect are no more. 
Changes noticed:
- no border radius when window is not maximized
- no border when not window maximized
- no drop shadow
- no window snap effect
- when maximized, there exists a padding all the way around the window content. In a manner which suggest the contentMargins of the main window has been unset.

If QMainWindow is used instead of FramlessWindow, the application still reloads itself but the window effects are not affected. 

**Environment**
 - OS: Windows 11
 - DPI scaling: 100%
 - Python: 3.10.7 64-bit
 - PySide6: 6.4.2
 
**To Reproduce**
1. Create a PySide6 Application using FramelessWindow
2. Run the application
3. Add an OpenGL Widget
or
1. Create a PySide6 Application using FramelessWindow with an OpenGL Widget
2. Run Application

**Code**
The provided code example uses [pyqtgraph](https://www.pyqtgraph.org/) to render 3d objects. 

```
from qframelesswindow import FramelessWindow
import pyqtgraph.opengl as gl

class MainWindow(FramelessWindow):
    def __init__(self):
        super().__init__()
        self.wLayout = QVBoxLayout()
        self.setWindowTitle("OpenGL widget Error")
        self.state = QLabel("Before adding open gl, window effect intact")
        self.addWButton = QPushButton("add 3d widget")
        self.addWButton.clicked.connect(self.add3DWidget)
        self.wLayout.addWidget(self.state)
        self.wLayout.addWidget(self.addWButton)
        self.setLayout(self.wLayout)
        self.titleBar.raise_()
        self.add3DWidget()

    def add3DWidget(self):
        w3d = gl.GLViewWidget()
        self.wLayout.addWidget(w3d)
        self.state.setText("After adding opengl widget, application reloads and window effect is no more.")

app = QApplication(sys.argv)
window = MainWindow()
window.show()
sys.exit(app.exec())
```

**Expected behavior**
Window Effects should not change after adding OpenGL

**Screenshots**
Case 1: Before adding a widget containing openGL
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/65168520/6af70c38-c656-4171-a3d5-3a553a25f105)

Case 2: After Adding a widget containging OpenGL
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/65168520/0fcb6621-dd45-493b-9849-51301692f423)

**Comment by zhiyiYo** [comment]
Try PyQt5

**Comment by Ndeh-007** [comment]
Okay, thank you very much. 

Can you please help me an explanantion as to why the application reloads itself when the opengl components are added? I cannot find any related material

**Comment by zhiyiYo** [comment]
try `FramelessWindow.updateFrameless()`

**Comment by mesa-git** [comment]
@Ndeh-007 did you manage to solve this any other way?

**Comment by Ndeh-007** [comment]
No I didn't 

I ended up having to call `updateFrameless` before showing the window on start-up

**Comment by mesa-git** [comment]
yea that worked for me as well, thanks
