### ISSUE TITLE
Content on the Right Side Is Not Visible When the Window Is in Full-Screen Mode

### ISSUE THREAD

**Issue by emrecpp** [zhiyiYo/PyQt-Frameless-Window#115]
There is no issue when the window is not in full-screen mode; however, when it is maximized to full screen, a portion of the content on the right side of the window does not fit properly and remains invisible.
(Please pay attention to the close button (often represented by an 'X' icon) located at the top-right corner of the window.)
**Note:** I Have Two Monitors.

**Environment**
 - OS: Windows10
 - DPI scaling: 100%
 - Python: 3.11.2 64-bit
 - PySide6: 6.5.0

![issue1](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/29755479/8d10ed95-d76a-4105-a3d4-ef54a5c76562)

**Comment by zhiyiYo** [comment]
You can use PySide 6.4.2 to solve this issue

**Comment by emrecpp** [comment]
> You can use PySide 6.4.2 to solve this issue

Downgrading the qt version worked, but are you working on making it work in versions after 6.4.2? Thank you!

**Comment by zhiyiYo** [comment]
I can't solve this problem at present

**Comment by ben-everest** [comment]
> > You can use PySide 6.4.2 to solve this issue
> 
> Downgrading the qt version worked, but are you working on making it work in versions after 6.4.2? Thank you!

It seems to be an issue with how the new version of PySide6 is handling the resize event. The PyQt5 version works correctly.
Adding a note about PySide 6.4.2 in the README may be helpful for other people who run into this issue.
