### ISSUE TITLE
titlebar

### ISSUE THREAD

**Issue by m3tros** [zhiyiYo/PyQt-Frameless-Window#118]
I need to make it so that I can attach the title to a specific widget. by default it stretches across the width of all windows and is above all widgets, but I need it to be bound to a QWidget. i need to pin qwidget to qspiltter. how to do it all?

![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/107058068/031caee5-63d0-477e-996b-a3f9c427c3de)
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/107058068/f9de2e2a-f401-42ba-8040-5a9ca2050a5e)

**Comment by m3tros** [comment]
because the header is above all widgets, I can't use qlineedit. title closes qlineedit.

**Comment by m3tros** [comment]
Below is the code that doesn't work. for some reason, when I click the "expand" button, the buttons just disappear

```python3
class InfoPassword(QtWidgets.QWidget):

    def __init__(self, parent, window_parent, *args, **kwargs):
        super(InfoPassword, self).__init__(parent, *args, **kwargs)
        self.parent = parent
        self.window_parent = window_parent
   
        self.initUI()
    
    def initUI(self):
        vbox = QtWidgets.QVBoxLayout()
        
        vbox.addWidget(self.parent.titleBar)
        vbox.addStretch(1)
        self.setLayout(vbox)
```



![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/107058068/f8142f28-ca60-4d85-b176-129d1a8a8e3f)
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/107058068/7a67fc6f-3a14-4149-a1ac-30a17fde1861)
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/107058068/3a6d3d9d-d860-49b6-8326-2ade7015816c)

**Comment by m3tros** [comment]
here is an example result
![Untitled](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/107058068/8104fb33-a79f-4639-9ae5-58a2a3ff6320)

**Comment by m3tros** [comment]
help

**Comment by m3tros** [comment]
суки

**Comment by m3tros** [comment]
суки

**Comment by suterberg** [comment]
You can see https://github.com/zhiyiYo/PyQt-Fluent-Widgets, this has the title like what you want

**Comment by m3tros** [comment]
> You can see https://github.com/zhiyiYo/PyQt-Fluent-Widgets, this has the title like what you want

thanks
