### ISSUE TITLE
可否支持pyside6

### ISSUE THREAD

**Issue by HowieHz** [zhiyiYo/PyQt-Frameless-Window#12]
自己尝试改了改（hpyculator项目里面改了改，引用了代码（还没在pypi上发布之前引用的）），
win这边切换到pyside6非常快捷（改import）
但是linux部分的切换到pyside6有个库在pyside6找不到对应
，不得不说博客和代码都很棒

**Comment by zhiyiYo** [comment]
你指的是 sip 模块找不到吗

**Comment by zhiyiYo** [comment]
也许你可以换成 `shiboken.getCppPointer(QX11Info.connection())[0]` 试试

**Comment by HowieHz** [comment]
> 你指的是 sip 模块找不到吗

是的

**Comment by HowieHz** [comment]
> 也许你可以换成 `shiboken.getCppPointer(QX11Info.connection())[0]` 试试

好，我试试

**Comment by zhiyiYo** [comment]
@HowieHz 
程序跑起来了吗

**Comment by HowieHz** [comment]
无法找到
PyQt5.QtWinExtras.QtWin
PyQt5.QtX11Extras.QX11Info
在pyside6的对应
(https://doc.qt.io/qtforpython-5/PySide2/QtX11Extras/QX11Info.html  但是PySide6查无此模块)

另外我只有win和mac的测试环境

**Comment by zhiyiYo** [comment]
如果你不用亚克力窗口的话可以把 `QtWin.enbleBlurBehind()` 注释掉，也可以通过调用 dwmapi.dll 里面的接口 `DwmEnableBlurBehindWindow` 来实现，MSDN 的文档为 [DWM Blur Behind Overview](https://docs.microsoft.com/en-us/windows/win32/dwm/blur-ovw)，Qt 的实现代码是：
```cpp
bool QtWin::enableBlurBehindWindow(QWidget widget, bool enable)
{
    Q_ASSERT(widget);
    bool result = false;
#ifdef Q_OS_WIN
    if (resolveLibs())
    {
        DWM_BLURBEHIND bb = {0};
        bb.fEnable = enable;
        bb.dwFlags = DWM_BB_ENABLE;
        bb.hRgnBlur = NULL;
        widget->setAttribute(Qt::WA_TranslucentBackground, enable);
        widget->setAttribute(Qt::WA_NoSystemBackground, enable);
        HRESULT hr = pDwmEnableBlurBehindWindow(reinterpret_cast<HWND>(widget->winId()), &bb);
        if (SUCCEEDED(hr))
        {
            result = true;
            windowNotifier()->addWidget(widget);
        }
    }
#endif // Q_OS_WIN

    return result;
}
```

 `QX11Info.connection()` 也可以参考一下 Qt 的源代码：
```cpp
xcb_connection_t *QX11Info::connection()
{
    if (!qApp)
        return nullptr;
    QPlatformNativeInterface *native = qApp->platformNativeInterface();
    if (!native)
        return nullptr;

    void *connection = native->nativeResourceForIntegration(QByteArray("connection"));
    return reinterpret_cast<xcb_connection_t *>(connection);
}
```

**Comment by HowieHz** [comment]
> 我晚上找个时间把这些代码翻译成 python 的好了🤔

(๑•̀ㅂ•́)و✧谢谢

**Comment by zhiyiYo** [comment]
@HowieHz 
捣鼓了一晚上，发现还是无法正确获取和 X11 服务器之间的连接，Linux 下窗口的移动和拖拽暂时还实现不了😕

**Comment by HowieHz** [comment]
> @HowieHz 捣鼓了一晚上，发现还是无法正确获取和 X11 服务器之间的连接，Linux 下窗口的移动和拖拽暂时还实现不了，而且 Qt6 也没有 `Qt.Edges`，放弃治疗了😕

那在pyside6环境下就是windows only了233
辛苦了

**Comment by HowieHz** [comment]
> @HowieHz 捣鼓了一晚上，发现还是无法正确获取和 X11 服务器之间的连接，Linux 下窗口的移动和拖拽暂时还实现不了，而且 Qt6 也没有 `Qt.Edges`，放弃治疗了😕

那在pyside6环境下就是windows only了233
辛苦了

**Comment by HowieHz** [comment]
pyqt6到是能无缝上

**Comment by zhiyiYo** [comment]
pyqt6 也没有 `QtWinExtras` 模块吧

**Comment by HowieHz** [comment]
> pyqt6 也没有 `QtWinExtras` 模块吧

是的，我记错了

**Comment by zhiyiYo** [comment]
> > pyqt6 也没有 `QtWinExtras` 模块吧
> 
> 是的，我记错了

现在 PyQt6 分支下的亚克力窗口实现无需QtWinExtras 模块

**Comment by zhiyiYo** [comment]
@HowieHz 
目前 PySide6 分支已添加对 Linux 的支持

**Comment by HowieHz** [comment]
> @HowieHz 目前 PySide6 分支已添加对 Linux 的支持

![0C7559F0](https://user-images.githubusercontent.com/94725606/215266656-5dc68b0f-5c2e-43e1-be12-c45fb5bc90b1.png)
