### ISSUE TITLE
窗口缩放时，如何限制窗口的最小宽度，防止titleBar过度压缩

### ISSUE THREAD

**Issue by gamesun** [zhiyiYo/PyQt-Frameless-Window#122]
**Is your feature request related to a problem? Please describe.**
窗口缩放时，如何限制窗口的最小宽度，以防止titleBar的控件重叠或显示不全

**Describe the solution you'd like**
限制窗口的最小宽度?

**Describe alternatives you've considered**
我试了改变titleBar的sizePolicy, 给每个控件设置setMinimumSize，setFixedSize，没能成功
或者`self.titleBar.hBoxLayout.setSizeConstraint(QLayout.SetFixedSize)`，只是titleBar不缩放了，但会被cut
可能我的方向不对？请指点一下，谢谢

**Additional context**
以您的examples\demo.py为例，横向缩放到最窄时，titleBar被压缩过度了
![2](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/3817128/e46a6ce6-7b32-4d04-bc70-06f1b9d190b7)

**Comment by zhiyiYo** [comment]
给主界面setMinimumWidth

**Comment by gamesun** [comment]
> 给主界面setMinimumWidth

谢谢
如果标题栏有个控件的宽度是动态变化的，有什么event，可以自动更新这个MinimunWidth

**Comment by zhiyiYo** [comment]
安个事件过滤器
