### ISSUE TITLE
[BUG] PyQt5-Fameless-Window 0.3.4 及以后的版本，FluentWindow 无法通过拖拽右侧边缘改变窗口大小

### ISSUE THREAD

**Issue by Zzaphkiel** [zhiyiYo/PyQt-Frameless-Window#132]
**Describe the bug**
若 PyQt5-Frameless-Window 版本大于等于 0.3.4，则 PyQt5-Fluent-Widgets 中 `FluentWindow` 窗口无法通过拖拽右侧边缘来调整横向大小，而左侧边缘可以拖拽。

![屏幕录制 2023-11-12 161413](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/60383222/7d9f34ad-d8fc-4a43-89f2-626340ad07b5)

**Environment**
 - OS: Windows 11 22H2
 - DPI scaling: 100%
 - Python: 3.8.16 64-bit
 - PyQt5: 5.15.9
 - PyQt5-Fluent-Widgets: 1.3.5
 - PyQt5-Frameless-Window: >= 0.3.4

**To Reproduce**
- 运行 PyQt5-Fluent-Widgets 中 `examples\window\fluent_window\demo.py` 或 `examples\gallary\demo.py` 等 `FluentWindow`
- 鼠标靠近窗口右侧边缘，看到问题。

**Code**
`PyQt5-Fluent-Widgets` 示例代码。

**Expected behavior**
其应该同小于等于 0.3.3 版本一样，能够通过拖拽窗口右侧边缘调节窗口大小。

**Something else**
PyQt5-Frameless-Window 中 `examples\acrylic_demo.py` 同样存在该问题，而 `demo.py`、`main_window.py` 以及 `web_engine.py` 则不存在。

**Comment by zhiyiYo** [comment]
0.3.7 修复了
