### ISSUE TITLE
Exception is thrown from __init__ of WindowsFramelessWindowsBase if multiple inheritance is used in a sub-class

### ISSUE THREAD

**Issue by UsYer** [zhiyiYo/PyQt-Frameless-Window#134]
**Describe the bug**
The __init__ method throws "TypeError: object.__init__() takes exactly one argument" if a subclass of, for example. FramelessMainWindow uses multiple inheritance.
I.E.:
```python
class Foo:
    pass


class MainWindow(FramelessMainWindow, Foo):

    def __init__(self):
        super().__init__()  # raises TypeError: object.__init__() takes exactly one argument
```

The problem was introduced [here](https://github.com/zhiyiYo/PyQt-Frameless-Window/commit/a3b86b588827f1460a6fcea82fa29171b5221ec1#diff-6f6acfb377a40a856f440107db5c0bd908d938792cb41612760a1da56097dff1R24)
This works fine as long as the sub classes only use single inheritance. But multiple inheritance changes the method resolution order, which is why the exception is raised.

A solution could be to simply remove this super call in the WindowsFramelessWindowsBase class, because it has no explicit parent class.
Another way would be to explicitly call the __init__ method of QMainWindow in WindowsFramelessWindowBase and the __init__ of QDialog in WindowsFramelessDialog.

Maybe the same problem is present in the Mac and Linux part, but i couldn't test that.

**Environment**
环境信息
 - OS: Windows10
 - DPI scaling: 100 %
 - Python: 3.10.11 64-bit
 - PyQt5: PySide 6.6

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. Change main_window.py in examples to 
```python
class Foo:
    pass


class MainWindow(FramelessMainWindow, Foo):

    def __init__(self):
        super().__init__()  
```
2. Execute
3. TypeError: object.__init__() takes exactly one argument is raised

**Expected behavior**
There should be no Exception

**Screenshots**
N/A

**Comment by UsYer** [comment]
After looking into it a bit more, it seems that this problem has its origin in a change in PySide 6.5 where correct multiple inheritance handling for \__init__ methods was introduced. Since you changed the order of base classes of `WindowsFramelessMainWindow` and `WindowsFramelessDialog` the code now fails.
See: https://forum.qt.io/topic/144262/typeerror-with-pyside-6-5-0-for-multiple-inheritance-of-mainwindow/28
I don't know what the correct fix is but maybe the base class order has to be reverted?

**Comment by suterberg** [comment]
亲 class麻烦初始化一下
class Foo:
    def __init__(self,*args,**kwargs):
        pass

**Comment by UsYer** [comment]
Okay, so just switching the order of base classes fixes the problem in my case.
Generally speaking it seems that the QT based classes need to be the last base class.
So in case of the example this would work:
```python
class Foo:
    pass


class MainWindow(Foo, FramelessMainWindow):

    def __init__(self):
        super().__init__()
```
