### ISSUE TITLE
窗口关闭后显示在通知栏图标，然后再恢复窗口时，窗口边框消失，阴影消失，无法通过边框缩放窗口。

### ISSUE THREAD

**Issue by riverbird** [zhiyiYo/PyQt-Frameless-Window#139]
**Describe the bug**
窗口关闭后显示在通知栏图标，然后再恢复窗口时，窗口边框消失，阴影消失，无法通过边框缩放窗口。

**Environment**
环境信息
 - OS: [e.g. Windows11]
 - DPI scaling: [e.g. 100%]
 - Python: [e.g. 3.11.7 64-bit]
 - PySide6: [e.g. 6.6.1]

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. 关闭窗口，执行closeEvent方法；
2. 在tray icon的菜单中，加入恢复窗口代码，执行__on_action_open_window方法；
3. 执行后，mainwindow的边框消失，阴影没有出现。

**Code**
最小复现代码
```python
# 窗口关闭事件
    def closeEvent(self, event: QCloseEvent) -> None:
        if self.tray_icon.isVisible():
            self.close()
# 窗口恢复事件
    def __on_action_open_window(self):
        self.showNormal()
```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
你用的是亚克力窗口吗？

**Comment by riverbird** [comment]
> 你用的是亚克力窗口吗？

不是的，只是普通窗口，class MainWindow(FramelessMainWindow)

**Comment by riverbird** [comment]
关闭前正常显示窗口边框样式：
关闭后showNormal()后窗口边框样式:

**Comment by riverbird** [comment]
### 关闭前
![001](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/1852814/cf645e0d-b7c2-414f-abb8-cbe8bd416d39)
### 恢复后
![002](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/1852814/1ebd2742-0ffa-4542-b3ed-ee412ce79b79)

**Comment by zhiyiYo** [comment]
我之前写的 Groove 也缩小到托盘，但是没遇到过你这个问题，不行的话试下6.4.2或者pyqt5

**Comment by riverbird** [comment]
问题已解决：
    def __on_action_open_window(self):
        self.showNormal()
        self.updateFrameless()
加了最后一句后，窗口显示正常：）
