### ISSUE TITLE
“显示强调色”的问题

### ISSUE THREAD

**Issue by guangziteam** [zhiyiYo/PyQt-Frameless-Window#14]
开了“显示强调色”以后出现了好多问题……😫
![图片](https://user-images.githubusercontent.com/75152171/178411448-14e2553f-3c84-4a06-bc54-ffac8ac03c6b.png)
正常情况下边框会显示主题色，但是用WindowEffect以后只会显示默认的边框，不会变色
![图片](https://user-images.githubusercontent.com/75152171/178411550-f5646385-94a1-4453-ab82-c0e9d95486c5.png)
![图片](https://user-images.githubusercontent.com/75152171/178411993-46cfba6f-2507-4c61-b9b1-bdd90a214555.png)
而且有一个很奇怪的问题，如果使用云母特效，它会强制在标题栏的位置加一个有主题色的背景（就很离谱）
![图片](https://user-images.githubusercontent.com/75152171/178419584-c37d5240-cb59-4beb-b953-79e7d83e4319.png)

**Comment by zhiyiYo** [comment]
@guangziteam 
我觉得想要主题色功能的话，可以自己去调用 api 获取颜色然后给 TitleBar 画上去，我没打算加这个功能（都自定义标题栏和窗口了，还用主题色干嘛🤔），Mica 效果的标题栏背景色 bug 有点奇怪，晚上再看看问题出在哪

**Comment by guangziteam** [comment]
标题栏的颜色到是没问题，主要是边框的颜色怎么办，就那个灰灰的边😕

**Comment by zhiyiYo** [comment]
chrome 浏览器也是灰色的边，好像只有 UWP 应用会把主题色应用到 border 上

**Comment by guangziteam** [comment]
没有呀，你是不是没开强调色
![图片](https://user-images.githubusercontent.com/75152171/178425634-fd70b2b9-fa60-446e-b3b3-e4c7b9ecb29d.png)

**Comment by guangziteam** [comment]
我就只是想在标题栏上加点按钮……就像旧版的资源管理器一样，不改变其它地方……
![图片](https://user-images.githubusercontent.com/75152171/178425431-6f69b143-54ba-4cfe-a4f1-a90f1ccd229b.png)

**Comment by zhiyiYo** [comment]
> 没有呀，你是不是没开强调色 ![图片](https://user-images.githubusercontent.com/75152171/178425634-fd70b2b9-fa60-446e-b3b3-e4c7b9ecb29d.png)

原来是失去焦点的时候是灰色的，窗口获得焦点会有颜色😕

**Comment by guangziteam** [comment]
看来我只能跳槽去做uwp了……主要是做个uwp应用电脑嗡嗡响，那编辑器占用贼高

**Comment by zhiyiYo** [comment]
> 看来我只能跳槽去做uwp了……主要是做个uwp应用电脑嗡嗡响，那编辑器占用贼高

要在 Qt 中实现主题色边框肯定是能做到的，不过我暂时没有这个打算😑

**Comment by guangziteam** [comment]
那……你这些是在哪学的……我啥都搜不到……

**Comment by zhiyiYo** [comment]
> 那……你这些是在哪学的……我啥都搜不到……

readme 里面给出了 reference 的仓库，但是那代码写的实在太恶心了，看完代码之后最好洗洗眼睛😇

**Comment by guangziteam** [comment]
哦，我去看看怎么个恶心法😂……

**Comment by guangziteam** [comment]
好家伙……全是C++的……我……只会python……

**Comment by zhiyiYo** [comment]
> 好家伙……全是C++的……我……只会python……

就算会C++ ，要理清他的代码也很生草😅

**Comment by zhiyiYo** [comment]
@guangziteam 
https://github.com/alexmercerind/flutter_acrylic/releases/tag/v1.0.0 这里面有给出一个 demo，但是 exe 我双击了没反应，不知道是不是 Windows 版本的问题，也许你可以试试他的标题栏背景在使用 mica 特效的时候会不会变色

**Comment by guangziteam** [comment]
我也打不开，我看了一下他的代码，他没有void main，我猜他可能需要用别的程序调用它或者在它的基础上加东西才能用

**Comment by zhiyiYo** [comment]
> 我也打不开，我看了一下他的代码，他没有void main，我猜他可能需要用别的程序调用它或者在它的基础上加东西才能用

应该是 windows 版本问题，我在 22000 上面试了是能运行 exe 的

**Comment by zhiyiYo** [comment]
@guangziteam 
发现 Windows11 22000 开了 "在标题栏和系统边框显示强调色" 并使用 Mica 效果，不会在标题栏下方出现主题色，估计这个 bug 和系统版本有关系

**Comment by guangziteam** [comment]
![图片](https://user-images.githubusercontent.com/75152171/178707374-143c2e29-686d-41df-acb0-aeff799f3d83.png)
我也发现了可能是系统的问题……因为我发现系统应用也有这个毛病……
![图片](https://user-images.githubusercontent.com/75152171/178707565-1e81ef0a-8fd5-4522-a260-95721cf6e460.png)

**Comment by guangziteam** [comment]
可能是因为我太久没更新了，我不知道为什么，我的电脑没法更新，可能是这个导致的

**Comment by guangziteam** [comment]
![图片](https://user-images.githubusercontent.com/75152171/178707927-6bf4bc1c-1050-4f32-9d09-f7c09ddaf338.png)

**Comment by guangziteam** [comment]
我今天重装了电脑，升级到了最新版，发现云母问题依旧还在，你看看你是不是最新版，我这边目前是最新版
![图片](https://user-images.githubusercontent.com/75152171/178997296-204596a6-f295-4a53-a3ff-f1a8bf0d8d0f.png)

**Comment by guangziteam** [comment]
亚克力：
![图片](https://user-images.githubusercontent.com/75152171/178998431-27e6a8e6-50c9-450a-86ca-f9b8d81a4f14.png)
云母：
![图片](https://user-images.githubusercontent.com/75152171/178998497-505f0859-bc94-4f73-a4f0-ac1ff830f7ec.png)

**Comment by guangziteam** [comment]
我也是22621啊，难不成我装了盗版的系统……
![图片](https://user-images.githubusercontent.com/75152171/179004394-5994e75f-c84a-49db-8f1a-97830ea03b16.png)

**Comment by guangziteam** [comment]
我不敢更新最新预览版了……太不稳定了，我换了beta

**Comment by zhiyiYo** [comment]
> ![图片](https://user-images.githubusercontent.com/75152171/178707374-143c2e29-686d-41df-acb0-aeff799f3d83.png) 我也发现了可能是系统的问题……因为我发现系统应用也有这个毛病…… ![图片](https://user-images.githubusercontent.com/75152171/178707565-1e81ef0a-8fd5-4522-a260-95721cf6e460.png)

我的任务管理器不会有这个问题

**Comment by guangziteam** [comment]
我更新完也没这个问题了
![图片](https://user-images.githubusercontent.com/75152171/179005448-7fe5597e-d3c2-4bb7-a3fb-a3481c1f06ca.png)

**Comment by guangziteam** [comment]
就python的还有这个问题，微软会不会故意为难win32😒

**Comment by guangziteam** [comment]
我好像有一点点的进展，我认为和窗口的边框有关：
![图片](https://user-images.githubusercontent.com/75152171/179196375-99b8949d-4ae5-4b0a-bc62-eabf4574c02d.png)
当有这两个属性其中的一个，并且开启在标题栏显示强调色，就会这样：
![图片](https://user-images.githubusercontent.com/75152171/179196528-dfba966a-4bdb-4aee-be6c-c62ce98abc1f.png)
如果把两个属性都注释掉，并且开启在标题栏显示强调色，标题栏的位置就不会有背景色：
![图片](https://user-images.githubusercontent.com/75152171/179196893-d9f8eb8e-ef73-427a-b728-5254beedc9d2.png)
但这样也有很明显的弊端，他没有边框，没有动画效果，拖到边缘无法布局，窗口失去焦点后亚克力效果依然还在
