### ISSUE TITLE
在窗口中嵌入QWebEngineView之后，窗口边框消失，阴影消失。

### ISSUE THREAD

**Issue by riverbird** [zhiyiYo/PyQt-Frameless-Window#140]
**Describe the bug**
在窗口中嵌入qwebenginer之后，窗口边框消失，阴影消失。

**Environment**
环境信息
 - OS: [e.g. Windows11]
 - DPI scaling: [e.g. 100%]
 - Python: [e.g. 3.11.7 64-bit]
 - PySide6: [e.g. 6.6.1]

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. 将QWebEngineView组件添加至QWidget当中的Layout当中；
2. 窗口边框消失，阴影消失。

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
self.tb_view = QWebEngineView()
self.tb_view.setObjectName('dot_note_preview')
self.tb_view.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
self.tb_view.installEventFilter(self)
```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
有个历史 issue，你去找找
