### ISSUE TITLE
反馈一个小bug：始终在默认路径下建立存储文件。

### ISSUE THREAD

**Issue by npzs** [zhiyiYo/PyQt-Frameless-Window#142]
QWebEngineView -> QWebEnginePage -> QWebEngineProfile
1. 如果想更改永久存储文件的路径，需要从 FramelessWebEngineView 对象逐级的获取 Profile 对象进行设置。
2. 但是如果连配置文件的名称（也是本地数据保存的目录名，默认 Default）也要改的话，就要自行实例化 QWebEngineProfile(const QString &storageName, QObject *parent = nullptr) 了，只能在实例化的时候提供新名称，并且该对象必须持久化到 view 关闭。然后再实例化 QWebEnginePage(QWebEngineProfile *profile, QObject *parent = nullptr)，也就是在参数中同时提供配置文件和父级的QWebEngineView即可，这里不指定父对象而只进行第3步测试无效。
3. FramelessWebEngineView.setPage，这个也必须调用，不然第二步的对象依然不能成功。

至此可以随意定义一个配置文件的路径和名称了，但是出现一个问题，就是我设置到任意路径，每次FramelessWebEngineView显示的时候，依然会在默认路径（调试的时候就是在python解释器路径下）里创建一堆存储数据文件，然后才会按照我的设置去新路径下工作。

开始以为是 QWebEngine 类的问题，特别是 QWebEngineView，后来调试发现，就是咱这个库的问题，出在：
qframelesswindow/webengine/__init__.py
第17行：
self.setHtml("")

这会让视图对象立即工作，此时还无法实现与新的页面和配置对象关联，即使从 FramelessWebEngineView 继承，也得调用父类的初始化后才能关联，也就是这一句代码必须先执行。

这句代码好像没有用吧，我给注释掉了，问题解决，默认路径下再也没有存储数据生成了。

**Comment by npzs** [comment]
就是提交一下给后来有问题的看看，解决了我就关闭咯。

**Comment by zhiyiYo** [comment]
win11上亚克力窗口要用，不能注释

**Comment by npzs** [comment]
> win11上亚克力窗口要用，不能注释

谢谢老板回复。
但不注释的话，是不是就根本实现不了我说的那个逻辑，简单说就是把存储文件改目录改名称，然后运行时不在默认目录创建无用的存储数据。
