### ISSUE TITLE
PySide2版本最右侧依然存在死区

### ISSUE THREAD

**Issue by veikai** [zhiyiYo/PyQt-Frameless-Window#144]
**Describe the bug**
窗口最大化时，最右侧有区域无法点击，简单调试了代码发现可能是鼠标定位有问题？导致没有到最右边的时候被判定成了最右边？
与https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/98类似
![企业微信截图_17072206898307](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/24666952/00cab53f-5922-4a17-960f-951d616cdb86)
粗略的对这部分代码进行了调试，发现右侧鼠标坐标会超过1920
![企业微信截图_17072207597407](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/24666952/07d1cd5b-ab76-42ae-91d6-07c062298823)

**Environment**
环境信息
 - OS: Windows 11
 - DPI scaling: 100%
 - Python: 3.7.16
 - PySide2: 5.15.2.1
 - CodeVersion: 0.3.7

**To Reproduce**
1. 最大化窗口
![video(3) -middle-original](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/24666952/78a8518f-d5ad-41c8-a802-22275a258363)

**Code**
最小复现代码
```python
# Minimum code to reproduce the error

```

**Expected behavior**
最右侧无遮挡

**Comment by veikai** [comment]
当我鼠标移动到最左边时显示的x坐标是-5

**Comment by AlleGao** [comment]
遇到了同样的问题。尤其是当最右边是滚动条的时候，现象尤其突出，因为会出现点击不了滚动条的情况。

**Comment by AlleGao** [comment]
感觉像是坐标系的问题，self.x()的值是负值。

**Comment by veikai** [comment]
https://github.com/zhiyiYo/PyQt-Frameless-Window/pull/145
