### ISSUE TITLE
希望窗口缩放区域判定和系统保持一致

### ISSUE THREAD

**Issue by veikai** [zhiyiYo/PyQt-Frameless-Window#146]
**Is your feature request related to a problem? Please describe.**
系统窗口当鼠标从外部接近时，靠近窗口边框鼠标变成缩放箭头，且窗口内测嗅探距离较短
![video(4) -middle-original](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/24666952/79a5c3b1-f515-42c2-a54c-76b1a64afd92)
demo中鼠标从外部接近时靠近窗口边框鼠标没有变成缩放箭头，而且窗口内测嗅探区域还是有些大，容易阻挡一些滚动条之类的组件
![video(5) -small-original](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/24666952/b536de5e-7fc1-42e8-a766-b41524c3ec5d)

**Comment by zhiyiYo** [comment]
Python 做不到，这个需要修改窗口的 custom Margin 属性

**Comment by littlewhitecloud** [comment]
那如果给窗口加上WS_THICKFRAME样式，再捕获WM_NCCALCSIZE来处理上面的6px非客户端区域呢？

**Comment by zhiyiYo** [comment]
实际上 PyQt5 分支实现了这个特性，但是窗口尺寸会有点问题
![after](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/682c3534-7dee-4ccb-b830-d1ae4b66beca)
