### ISSUE TITLE
Rounded framless window with no shadow

### ISSUE THREAD

**Issue by Jake4353** [zhiyiYo/PyQt-Frameless-Window#149]
im trying to make a desktop widget and i cant seem to make a frameless window that has no shadow, with rounded borders.
When i try to remove the shadow from the window, it removes the rounded border too.

![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/44424544/072ce238-7523-487f-be15-b3c546c7af29)

![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/44424544/5fc2791f-f9b6-4704-8408-fce275452ca9)

**Comment by AlexZhu2001** [comment]
Please show your code about how to disable the shadow and your environment (OS, Python version, PyQt/PySide Version etc.).
This can help us reproduce this problem.
