### ISSUE TITLE
Use QMainWindow Instead of QWidget as a parent class

### ISSUE THREAD

**Issue by Advik-B** [zhiyiYo/PyQt-Frameless-Window#15]
The following code won't work
```py
class Window(FramelessWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setMinimumSize(400, 400)
        self.te = QTextEdit(self)
        self.te.move(10, 30)
        self.te.resize(380, 380)
        self.te.setText("Hello World!")
        self.te.raise_()
        self.setCentralWidget(self.te)
        self.show()
```
The error is at `self.setCentralWidget(self.te)`:
```py
class Window(FramelessWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setMinimumSize(400, 400)
        self.te = QTextEdit(self)
        self.te.move(10, 30)
        self.te.resize(380, 380)
        self.te.setText("Hello World!")
        self.te.raise_()
        self.setCentralWidget(self.te) <<<-----------
        self.show()
```

Because `FramelessWindow` inherits QWidget, not QMainWindow
I changed QWidget to QMainWindow and this is the result
![image](https://user-images.githubusercontent.com/86160411/178660545-29afda82-230d-416b-8f35-12b3351d12c9.png)
Notice the window 🗕🗗🗙 are not showing up. (Sady I STILL havent found a solution for this 😕)

**Comment by zhiyiYo** [comment]
You should leave a little space for the title bar
```python
self.setContentsMargins(0, self.titleBar.height(), 0, 0)
```
![image](https://user-images.githubusercontent.com/65096819/178662243-29085b3a-360f-4df6-b404-27c2a2ef0c55.png)

**Comment by Advik-B** [comment]
Thank you
