### ISSUE TITLE
采用pyside6-6.7.0版本后，windows下面会采用windows11的风格，菜单显示不全。

### ISSUE THREAD

**Issue by riverbird** [zhiyiYo/PyQt-Frameless-Window#153]
**Describe the bug**
采用pyside6-6.7.0版本后，windows下面会采用windows11的风格，菜单显示不全。

**Environment**
环境信息
 - OS: [Windows11]
 - DPI scaling: [125%]
 - Python: [3.11.7 64-bit]
 - PySide6: [6.7.0]

**To Reproduce**
在其它Qstyle下面正常，但是在windows11的风格下面菜单显示不正常。

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
self.titleBar.layout().insertWidget(0, menu_bar, 0, Qt.AlignmentFlag.AlignLeft)
        self.titleBar.layout().insertStretch(1, 1)
        self.setMenuWidget(self.titleBar)
```

**Expected behavior**

**Screenshots**

**Comment by riverbird** [comment]
![微信截图_20240416103002](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/1852814/27a49daa-8312-4330-8874-5b719d8a7507)
附上截图。

**Comment by Cheukfung** [comment]
估计是pysdie6的bug，如果是6.7.0，阴影效果也不行了：https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/848

**Comment by zhiyiYo** [comment]
更换默认 app style 为 fusion 试试
