### ISSUE TITLE
windows窗口最大化时窗口超出屏幕范围

### ISSUE THREAD

**Issue by Henxun** [zhiyiYo/PyQt-Frameless-Window#159]
**Describe the bug**
FramelessMainWindow端窗口最大化时，窗口会超出屏幕，导致右侧会被遮挡一部分

**Environment**
环境信息
 - OS: [e.g. Windows11]
 - DPI scaling: [e.g. 100%]
 - Python: [e.g. 3.11.6 64-bit]
 - PySide6: [e.g. 6.5.3]

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. 点击最大化按钮
2. 现象: 关闭按钮会被屏幕遮住一部分

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
import sys

from PySide6.QtWidgets import QApplication, QLabel
from qframelesswindow import FramelessMainWindow

import app


class MainWindow(FramelessMainWindow):
    def __init__(self):
        super().__init__()

        self.setCentralWidget(QLabel('test'))
        self.titleBar.raise_()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
```

**Expected behavior**
窗口正常显示

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/38826162/9ac7ed76-7c18-429f-8c2b-70499fb0a82d)
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/38826162/9ac7ed76-7c18-429f-8c2b-70499fb0a82d)
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/38826162/9ac7ed76-7c18-429f-8c2b-70499fb0a82d)

**Comment by zhiyiYo** [comment]
PySide6 版本过低
