### ISSUE TITLE
无法显示窗口标题+如何在最小化左边添加其他功能按钮

### ISSUE THREAD

**Issue by idesign2018** [zhiyiYo/PyQt-Frameless-Window#170]
**Describe the bug**
如图序号①：无法显示窗口标题
如图序号②：如何在最小化左边添加其他功能按钮
![image](https://github.com/user-attachments/assets/116eabfe-57ec-4404-8f11-ecc078238050)

**Environment**
环境信息
 - OS: Windows11
 - DPI scaling: 4K, 100%]
 - Python: 3.10.11 64-bit]
 - PyQt5: 5.15.11

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. pip install PyQt5-Frameless-Window
2. 代码：
```python
import sys

from PyQt5.QtWidgets import QApplication
from qframelesswindow import FramelessWindow


class Window(FramelessWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setWindowTitle("PyQt-Frameless-Window")
        self.titleBar.raise_()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())
```
3. See error

**Code**
最小复现代码
```python
import sys
from PyQt5.QtWidgets import QApplication, QLabel, QDesktopWidget
from qframelesswindow import AcrylicWindow

class Window(AcrylicWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        #self.setWindowTitle("窗口测试")
        #self.titleBar.hide("30px")
        #self.titleBar("窗口测试")
        self.title_label = QLabel("窗口测试")
        self.resize(1200, 1000)

        # 获取桌面大小
        desktop = QDesktopWidget()
        screen_rect = desktop.screenGeometry()

        # 获取窗口大小
        window_size = self.geometry()

        # 计算窗口居中的位置
        x = (screen_rect.width() - window_size.width()) // 2
        y = (screen_rect.height() - window_size.height()) // 2
        
        # 移动窗口到居中位置
        self.move(x, y)

        # customize acrylic effect
        # self.windowEffect.setAcrylicEffect(self.winId(), "106EBE99")

        # you can also enable mica effect on Win11
        self.windowEffect.setMicaEffect(self.winId(), False)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    idesign = Window()
    idesign.show()
    sys.exit(app.exec_())
```

**Expected behavior**
无法显示窗口标题+如何在最小化左边添加其他功能按钮

**Screenshots**
![image](https://github.com/user-attachments/assets/116eabfe-57ec-4404-8f11-ecc078238050)

**Comment by zhiyiYo** [comment]
看例子

**Comment by idesign2018** [comment]
> 看例子

不好意思，我是编程小白，表示不清楚如何添加更多按钮，标题栏文本不显示的问题我应该如何调整？

**Comment by zhiyiYo** [comment]
https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/demo.py

**Comment by idesign2018** [comment]
> 看例子

大佬，我认真查看[#55](https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/55) 后，实现了在自定义标题栏的位置添加多个按钮的功能：
![image](https://github.com/user-attachments/assets/e8bbe8a7-9114-4f59-8f0b-a8e1d3504622)
但我的窗口标题栏还是没有标题文字显示，这是什么原因？
尝试添加如图功能时，
![image](https://github.com/user-attachments/assets/74c13278-ef02-4937-ba6f-4b5ec6bcbcd3)
出现错误如下：
```python
发生异常: AttributeError
'CustomTitleBar' object has no attribute 'setTitleBar'
  File "C:\Users\idesign\Desktop\无边窗口.py", line 13, in __init__
    self.setTitleBar(StandardTitleBar(self))
  File "C:\Users\idesign\Desktop\无边窗口.py", line 33, in __init__
    self.setTitleBar(CustomTitleBar(self))
  File "C:\Users\idesign\Desktop\无边窗口.py", line 38, in <module>
    demo = Window()
AttributeError: 'CustomTitleBar' object has no attribute 'setTitleBar'
```
![image](https://github.com/user-attachments/assets/edd65a80-8ac5-4ffa-8aab-f99d0839e418)

完整代码如下：
```python

import sys
from PySide2.QtWidgets import QApplication, QPushButton, QLabel, QHBoxLayout, QWidget
from PySide2.QtGui import QIcon, QColor
from PySide2.QtCore import Qt
from qframelesswindow import FramelessWindow, TitleBar, StandardTitleBar
from qframelesswindow import SvgTitleBarButton

class CustomTitleBar(StandardTitleBar):
    """ Custom title bar """

    def __init__(self, parent):
        super().__init__(parent)
        self.setTitleBar(StandardTitleBar(self))
        self.setWindowIcon(QIcon("C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\logo.svg"))
        self.setWindowTitle("PyQt-Frameless-Window")

        # don't forget to put the title bar at the top
        self.titleBar.raise_()

        self.questionButton = SvgTitleBarButton('C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\help.svg', self)
        self.pinButton = SvgTitleBarButton('C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\pin_1.svg', self)
        layout = QHBoxLayout()
        self.hBoxLayout.insertLayout(4, layout)
        layout.addWidget(self.pinButton, 0, Qt.AlignRight)
        layout.addWidget(self.questionButton, 0, Qt.AlignRight)


class Window(FramelessWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        # change the default title bar
        self.setTitleBar(CustomTitleBar(self))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())

```

还有就是如何修改窗口栏的按钮图标呢？
![image](https://github.com/user-attachments/assets/cdc8268d-5ae6-4ae7-8571-90339c836a91)
我想将上图这些图标都修改为如下图所示效果：
![image](https://github.com/user-attachments/assets/e40ff092-8d04-4762-9848-f679cc460efb)

**Comment by idesign2018** [comment]
> https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/demo.py

这个示例代码出现如下错误：
```python
发生异常: TypeError
QVariant must be holding a QColor
  File "C:\Users\idesign\Desktop\无边窗口1.py", line 19, in __init__
    self.minBtn.setHoverBackgroundColor(QColor(0, 100, 182))
  File "C:\Users\idesign\Desktop\无边窗口1.py", line 39, in __init__
    self.setTitleBar(CustomTitleBar(self))
  File "C:\Users\idesign\Desktop\无边窗口1.py", line 88, in <module>
    demo = Window()
TypeError: QVariant must be holding a QColor
```

**Comment by idesign2018** [comment]
![github-receipt-zhiyiYo](https://github.com/user-attachments/assets/8e716d8e-3187-4386-8fb3-5ef7cb5e4947)

**Comment by zhiyiYo** [comment]
> > 看例子
> 
> 大佬，我认真查看[#55](https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/55) 后，实现了在自定义标题栏的位置添加多个按钮的功能： ![image](https://private-user-images.githubusercontent.com/42263070/387144808-e8bbe8a7-9114-4f59-8f0b-a8e1d3504622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDQ4MDgtZThiYmU4YTctOTExNC00ZjU5LThmMGItYThlMWQzNTA0NjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MDE4ODVlNGE2NzE5ODA2OWU3ZWE2YjVhYTUzNDY2YTFmMGRmZjQxMmNjNjY5MzExOTI3NjI1ZmRmYWVkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6lSUILguPorVT4PwfMqd8Z8hccC3d-_OcEtZz7nK1Mk) 但我的窗口标题栏还是没有标题文字显示，这是什么原因？ 尝试添加如图功能时， ![image](https://private-user-images.githubusercontent.com/42263070/387145653-74c13278-ef02-4937-ba6f-4b5ec6bcbcd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDU2NTMtNzRjMTMyNzgtZWYwMi00OTM3LWJhNmYtNGI1ZWM2YmNiY2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDIyMjE5NjJhZTBlNWZmODQ0Yjg0MjNhMTQwNjY3MmM0OTA2NWVkZmUwMWFmOTEwNmE0ZjQxOWVlNzkyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mQel6UcmeqsUALFIGW9_Rb_Bz3tPEEpR725c946YlJw) 出现错误如下：
> 
> ```python
> 发生异常: AttributeError
> 'CustomTitleBar' object has no attribute 'setTitleBar'
>   File "C:\Users\idesign\Desktop\无边窗口.py", line 13, in __init__
>     self.setTitleBar(StandardTitleBar(self))
>   File "C:\Users\idesign\Desktop\无边窗口.py", line 33, in __init__
>     self.setTitleBar(CustomTitleBar(self))
>   File "C:\Users\idesign\Desktop\无边窗口.py", line 38, in <module>
>     demo = Window()
> AttributeError: 'CustomTitleBar' object has no attribute 'setTitleBar'
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/42263070/387146483-edd65a80-8ac5-4ffa-8aab-f99d0839e418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDY0ODMtZWRkNjVhODAtOGFjNS00ZmZhLThhYWItZjk5ZDA4MzllNDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYWQxN2QxMDgzNTJkNzkzY2Q1MTc5YTNlYjg0ODk2OGVkMjFiYjk5YjRhZTBiNTkxMzAzMjYzZWYyMjFkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aI9QEUAgQrAKKjuDlNjBEoRQqAFn2eE3VPJd-sGs1Ws)
> 
> 完整代码如下：
> 
> ```python
> import sys
> from PySide2.QtWidgets import QApplication, QPushButton, QLabel, QHBoxLayout, QWidget
> from PySide2.QtGui import QIcon, QColor
> from PySide2.QtCore import Qt
> from qframelesswindow import FramelessWindow, TitleBar, StandardTitleBar
> from qframelesswindow import SvgTitleBarButton
> 
> class CustomTitleBar(StandardTitleBar):
>     """ Custom title bar """
> 
>     def __init__(self, parent):
>         super().__init__(parent)
>         self.setTitleBar(StandardTitleBar(self))
>         self.setWindowIcon(QIcon("C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\logo.svg"))
>         self.setWindowTitle("PyQt-Frameless-Window")
> 
>         # don't forget to put the title bar at the top
>         self.titleBar.raise_()
> 
>         self.questionButton = SvgTitleBarButton('C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\help.svg', self)
>         self.pinButton = SvgTitleBarButton('C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\pin_1.svg', self)
>         layout = QHBoxLayout()
>         self.hBoxLayout.insertLayout(4, layout)
>         layout.addWidget(self.pinButton, 0, Qt.AlignRight)
>         layout.addWidget(self.questionButton, 0, Qt.AlignRight)
> 
> 
> class Window(FramelessWindow):
> 
>     def __init__(self, parent=None):
>         super().__init__(parent=parent)
>         # change the default title bar
>         self.setTitleBar(CustomTitleBar(self))
> 
> 
> if __name__ == '__main__':
>     app = QApplication(sys.argv)
>     demo = Window()
>     demo.show()
>     sys.exit(app.exec_())
> ```
> 
> 还有就是如何修改窗口栏的按钮图标呢？ ![image](https://private-user-images.githubusercontent.com/42263070/387149098-cdc8268d-5ae6-4ae7-8571-90339c836a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDkwOTgtY2RjODI2OGQtNWFlNi00YWU3LTg1NzEtOTAzMzljODM2YTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YjVmMjcxYTg1ZmJjOWNlZDNjODNkMmUzNGMyM2NhYjU1OGM2ZWU4NzFkN2FkZWE1MzJiYzI5NjQyMjhmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2dp4PoF5vFksHB96BuqmD63LiAIpmTWLYpz7gii_Rog) 我想将上图这些图标都修改为如下图所示效果： ![image](https://private-user-images.githubusercontent.com/42263070/387149431-e40ff092-8d04-4762-9848-f679cc460efb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDk0MzEtZTQwZmYwOTItOGQwNC00NzYyLTk4NDgtZjY3OWNjNDYwZWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MWEzOWJlNGRmNDU2NjRiYjAwMmQxZmExZGYyNzQ4YTM4YWVmZWIyNmU4Y2RiMzc2ODlkNjlkMDFlZDkxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JOdR4nS31BEcL0PqYraPuWtMZoCWTEp5mB3n5TRLfd8)

你可以参考下我的源代码，看下怎么改这几个按钮，或者就干脆自己继承 TitleBarBase 写一个，目前最大化按钮的图标是画出来的

**Comment by zhiyiYo** [comment]
> > https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/demo.py
> 
> 这个示例代码出现如下错误：
> 
> ```python
> 发生异常: TypeError
> QVariant must be holding a QColor
>   File "C:\Users\idesign\Desktop\无边窗口1.py", line 19, in __init__
>     self.minBtn.setHoverBackgroundColor(QColor(0, 100, 182))
>   File "C:\Users\idesign\Desktop\无边窗口1.py", line 39, in __init__
>     self.setTitleBar(CustomTitleBar(self))
>   File "C:\Users\idesign\Desktop\无边窗口1.py", line 88, in <module>
>     demo = Window()
> TypeError: QVariant must be holding a QColor
> ```
> 
> 我尝试让ChatGPT修复错误，出现了其他新问题

没遇到过这个问题，换成 pqqt5.15.2 试试

**Comment by idesign2018** [comment]
> > > https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/demo.py
> > 
> > 
> > 这个示例代码出现如下错误：
> > ```python
> > 发生异常: TypeError
> > QVariant must be holding a QColor
> >   File "C:\Users\idesign\Desktop\无边窗口1.py", line 19, in __init__
> >     self.minBtn.setHoverBackgroundColor(QColor(0, 100, 182))
> >   File "C:\Users\idesign\Desktop\无边窗口1.py", line 39, in __init__
> >     self.setTitleBar(CustomTitleBar(self))
> >   File "C:\Users\idesign\Desktop\无边窗口1.py", line 88, in <module>
> >     demo = Window()
> > TypeError: QVariant must be holding a QColor
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我尝试让ChatGPT修复错误，出现了其他新问题
> 
> 没遇到过这个问题，换成 pqqt5.15.2 试试

好的，谢谢大佬

**Comment by idesign2018** [comment]
> > > 看例子
> > 
> > 
> > 大佬，我认真查看[#55](https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/55) 后，实现了在自定义标题栏的位置添加多个按钮的功能： <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/42263070/387144808-e8bbe8a7-9114-4f59-8f0b-a8e1d3504622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDQ4MDgtZThiYmU4YTctOTExNC00ZjU5LThmMGItYThlMWQzNTA0NjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MDE4ODVlNGE2NzE5ODA2OWU3ZWE2YjVhYTUzNDY2YTFmMGRmZjQxMmNjNjY5MzExOTI3NjI1ZmRmYWVkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6lSUILguPorVT4PwfMqd8Z8hccC3d-_OcEtZz7nK1Mk"> 但我的窗口标题栏还是没有标题文字显示，这是什么原因？ 尝试添加如图功能时， <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/42263070/387145653-74c13278-ef02-4937-ba6f-4b5ec6bcbcd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDU2NTMtNzRjMTMyNzgtZWYwMi00OTM3LWJhNmYtNGI1ZWM2YmNiY2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDIyMjE5NjJhZTBlNWZmODQ0Yjg0MjNhMTQwNjY3MmM0OTA2NWVkZmUwMWFmOTEwNmE0ZjQxOWVlNzkyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mQel6UcmeqsUALFIGW9_Rb_Bz3tPEEpR725c946YlJw"> 出现错误如下：
> > ```python
> > 发生异常: AttributeError
> > 'CustomTitleBar' object has no attribute 'setTitleBar'
> >   File "C:\Users\idesign\Desktop\无边窗口.py", line 13, in __init__
> >     self.setTitleBar(StandardTitleBar(self))
> >   File "C:\Users\idesign\Desktop\无边窗口.py", line 33, in __init__
> >     self.setTitleBar(CustomTitleBar(self))
> >   File "C:\Users\idesign\Desktop\无边窗口.py", line 38, in <module>
> >     demo = Window()
> > AttributeError: 'CustomTitleBar' object has no attribute 'setTitleBar'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/42263070/387146483-edd65a80-8ac5-4ffa-8aab-f99d0839e418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDY0ODMtZWRkNjVhODAtOGFjNS00ZmZhLThhYWItZjk5ZDA4MzllNDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYWQxN2QxMDgzNTJkNzkzY2Q1MTc5YTNlYjg0ODk2OGVkMjFiYjk5YjRhZTBiNTkxMzAzMjYzZWYyMjFkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aI9QEUAgQrAKKjuDlNjBEoRQqAFn2eE3VPJd-sGs1Ws">
> > 完整代码如下：
> > ```python
> > import sys
> > from PySide2.QtWidgets import QApplication, QPushButton, QLabel, QHBoxLayout, QWidget
> > from PySide2.QtGui import QIcon, QColor
> > from PySide2.QtCore import Qt
> > from qframelesswindow import FramelessWindow, TitleBar, StandardTitleBar
> > from qframelesswindow import SvgTitleBarButton
> > 
> > class CustomTitleBar(StandardTitleBar):
> >     """ Custom title bar """
> > 
> >     def __init__(self, parent):
> >         super().__init__(parent)
> >         self.setTitleBar(StandardTitleBar(self))
> >         self.setWindowIcon(QIcon("C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\logo.svg"))
> >         self.setWindowTitle("PyQt-Frameless-Window")
> > 
> >         # don't forget to put the title bar at the top
> >         self.titleBar.raise_()
> > 
> >         self.questionButton = SvgTitleBarButton('C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\help.svg', self)
> >         self.pinButton = SvgTitleBarButton('C:\\Users\\idesign\\Desktop\\自动化\\1.2\\icons\\pin_1.svg', self)
> >         layout = QHBoxLayout()
> >         self.hBoxLayout.insertLayout(4, layout)
> >         layout.addWidget(self.pinButton, 0, Qt.AlignRight)
> >         layout.addWidget(self.questionButton, 0, Qt.AlignRight)
> > 
> > 
> > class Window(FramelessWindow):
> > 
> >     def __init__(self, parent=None):
> >         super().__init__(parent=parent)
> >         # change the default title bar
> >         self.setTitleBar(CustomTitleBar(self))
> > 
> > 
> > if __name__ == '__main__':
> >     app = QApplication(sys.argv)
> >     demo = Window()
> >     demo.show()
> >     sys.exit(app.exec_())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还有就是如何修改窗口栏的按钮图标呢？ <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/42263070/387149098-cdc8268d-5ae6-4ae7-8571-90339c836a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDkwOTgtY2RjODI2OGQtNWFlNi00YWU3LTg1NzEtOTAzMzljODM2YTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YjVmMjcxYTg1ZmJjOWNlZDNjODNkMmUzNGMyM2NhYjU1OGM2ZWU4NzFkN2FkZWE1MzJiYzI5NjQyMjhmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2dp4PoF5vFksHB96BuqmD63LiAIpmTWLYpz7gii_Rog"> 我想将上图这些图标都修改为如下图所示效果： <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/42263070/387149431-e40ff092-8d04-4762-9848-f679cc460efb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDQxNDEsIm5iZiI6MTczMjAwMzg0MSwicGF0aCI6Ii80MjI2MzA3MC8zODcxNDk0MzEtZTQwZmYwOTItOGQwNC00NzYyLTk4NDgtZjY3OWNjNDYwZWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MWEzOWJlNGRmNDU2NjRiYjAwMmQxZmExZGYyNzQ4YTM4YWVmZWIyNmU4Y2RiMzc2ODlkNjlkMDFlZDkxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JOdR4nS31BEcL0PqYraPuWtMZoCWTEp5mB3n5TRLfd8">
> 
> 你可以参考下我的源代码，看下怎么改这几个按钮，或者就干脆自己继承 TitleBarBase 写一个，目前最大化按钮的图标是画出来的

好的，我重新学习Python
