### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtX11Extras' on MacOS

### ISSUE THREAD

**Issue by ixmb** [zhiyiYo/PyQt-Frameless-Window#19]
I m trying with PyQt5 and using Big Sur 11.6.2. I didn't a solution on the web.
Any suggestion?

**Comment by zhiyiYo** [comment]
There is no MacOS test environment on my computer. Maybe you can refer to [Qt-Nice-Frameless-Window](https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window/tree/master/framelesswindow) for the solution.

**Comment by zhiyiYo** [comment]
@ixmb 
Can you help me run `mainwindow.py` on MacOS? If the dragging and resizing functions are normal, I plan to add support for MacOS by referring to 🙂

**Comment by zhiyiYo** [comment]
@ixmb 
At present, PyQt-Frameless-Window has supported MacOS, please check it.
