### ISSUE TITLE
自定义标题栏颜色异常

### ISSUE THREAD

**Issue by Harry2010410** [zhiyiYo/PyQt-Frameless-Window#22]
你好，我在调试demo.py时，希望可以自定义标题栏颜色，通过setStyleSheet设置了TitleBar的颜色为白色，同时修改了CloseButton、MinimizeButton默认背景颜色为白色，但是执行后，显示如下图所示，开始跟中间部分显示异常，麻烦大佬帮忙看下还有哪里设置不对，谢谢
![image](https://user-images.githubusercontent.com/55910265/189093889-7da0628c-e29c-4deb-ba89-46b595b6f042.png)

**Comment by zhiyiYo** [comment]
@Harry2010410 
能提供一下代码吗

**Comment by Harry2010410** [comment]
demo.py，刚才为了对比，我把主窗口背景设为黑色的了
[PyQt-Frameless-Window.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/9526236/PyQt-Frameless-Window.zip)

**Comment by zhiyiYo** [comment]
@Harry2010410 
因为标题栏里面通过 `self.setAttribute(Qt.WA_TranslucentBackground)` 把背景设置为透明了，你可以把这行注释掉，然后通过样式表设置你想要的背景色

**Comment by Harry2010410** [comment]
@zhiyiYo 这个我试过了，还是不行哦

> @Harry2010410 因为标题栏里面通过 `self.setAttribute(Qt.WA_TranslucentBackground)` 把背景设置为透明了，你可以把这行注释掉，然后通过样式表设置你想要的背景色

**Comment by zhiyiYo** [comment]
@Harry2010410 
如果设置背景不起作用，可以加上 `self.setAttribute(Qt.WA_StyledBackground)`
```python
# self.setAttribute(Qt.WA_TranslucentBackground)
self.setAttribute(Qt.WA_StyledBackground)
self.setStyleSheet("TitleBar{background: white}")
```

效果如下：
![image](https://user-images.githubusercontent.com/65096819/189113249-fc9f88dd-4276-4628-848f-b577e76e2822.png)

**Comment by Harry2010410** [comment]
@zhiyiYo 大佬牛皮，确实解决了，刚才查了WA_StyledBackground，还是有点困惑，TitleBar为什么会被父窗口的背景影响

**Comment by zhiyiYo** [comment]
> @zhiyiYo 大佬牛皮，确实解决了，刚才查了WA_StyledBackground，还是有点困惑，TitleBar为什么会被父窗口的背景影响

Qt 就是这样规定的😕

**Comment by Harry2010410** [comment]
> > @zhiyiYo 大佬牛皮，确实解决了，刚才查了WA_StyledBackground，还是有点困惑，TitleBar为什么会被父窗口的背景影响
> 
> Qt 就是这样规定的😕

哈哈，十分感谢！

**Comment by Drezzler** [comment]
@zhiyiYo - I am sorry for opening this issue again.

Is their a way to override the - `self.setAttribute(Qt.WA_TranslucentBackground)` instead of editing the module `__init_.py` file ?

I tried overriding the `self.setAttribute(Qt.WA_TranslucentBackground)`  in my own class, but that is not working.

Thank you

**Comment by zhiyiYo** [comment]
@Drezzler 
I have removed this line of code in the latest release

**Comment by Drezzler** [comment]
Thank you so much for all the effort you put into this module.

Much appreciated.

**Comment by zhiyiYo** [comment]
🙂
