### ISSUE TITLE
FramelessWindow 隐藏titleBar 后   设置QSS样式后出现titleBar

### ISSUE THREAD

**Issue by 1197730656** [zhiyiYo/PyQt-Frameless-Window#23]
![20](https://user-images.githubusercontent.com/47029287/191289352-ce16b153-26e4-4dcb-a2cd-18f53fd6a0a3.png)
```python
import sys
from PyQt5 import QtCore
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QLabel
from qframelesswindow import FramelessWindow


class ResLabel(QLabel, FramelessWindow):
    def __init__(self, *args, **kwargs):
        super(ResLabel, self).__init__(*args, **kwargs)
        self.titleBar.hide()

        self.setWordWrap(True)
        self.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.setWindowFlags(Qt.WindowStaysOnTopHint)

        self.setStyleSheet('''QLabel{background:rgba(10,10,255,0.1);border:3px solid rgba(255, 0, 0,0.5);
	                                }''')
        self.setText('我想学C++' * 9)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = ResLabel()
    demo.show()
    sys.exit(app.exec_())
```

**Comment by zhiyiYo** [comment]
出现的标题栏是系统的标题栏，没必要用双重继承吧，不能在 `FramelessWindow` 里面放一个 `QLabel` 吗?

**Comment by 1197730656** [comment]
> 在 `FramelessWindow` 里面放一个 `QLabel`

在 FramelessWindow 里面放一个 QLabel可以  能不能隐藏系统标题栏

**Comment by zhiyiYo** [comment]
把设置背景色的那一句 qss 去掉就好了
```python
self.setStyleSheet('''QLabel{border:3px solid rgba(255, 0, 0,0.5)}''')
```

**Comment by zhiyiYo** [comment]
目前来看是系统标题栏被不透明的背景色给挡住了，如果设置半透明的背景色就会看到后面的系统标题栏

**Comment by 1197730656** [comment]
self.setWindowFlags(Qt.FramelessWindowHint) 加上这个可以解决那个问题

**Comment by 1197730656** [comment]
在windows/__init__.py文件中WindowsFramelessWindow类中加上下面的   可以解决无标题栏窗口移动的问题
# 在WindowsFramelessWindow类中__init__函数中加上
self.MARGIN = self.BORDER_WIDTH
self._canmove = False  # 可以移动


    def mousePressEvent(self, event):
        # 鼠标按下事件记录位置
        super(WindowsFramelessWindow, self).mousePressEvent(event)
        if event.buttons() == Qt.LeftButton:
            self._pos = event.pos()
            self._pressed = True
            self._canmove = True

            # if self.childAt(self._pos) != None:
            #     鼠标点击的位置在其它控件上
                # self._canmove = True

    def mouseReleaseEvent(self, event):
        # 鼠标弹起事件
        super(WindowsFramelessWindow, self).mouseReleaseEvent(event)
        self._pressed = False
        self._canmove = False
        self.Direction = None


    def mouseMoveEvent(self, event):
        # 鼠标移动事件
        super(WindowsFramelessWindow, self).mouseMoveEvent(event)

        pos = event.pos()
        xPos, yPos = pos.x(), pos.y()
        wm, hm = self.width() - self.MARGIN, self.height() - self.MARGIN

        if self._canmove:
            self.move(self.mapToGlobal(event.pos() - self._pos))
            return

**Comment by zhiyiYo** [comment]
@1197730656 
这种移动窗口的方法有很多问题，比如不能贴边最大化，建议换成 `utils.startSystemMove()`

**Comment by zhiyiYo** [comment]
> self.setWindowFlags(Qt.FramelessWindowHint) 加上这个可以解决那个问题

加上这个就没有窗口阴影、没有窗口最大化和最小化动画，这些本来就是 PyQt-Frameless-Window 项目解决的问题

**Comment by zhiyiYo** [comment]
建议阅读关于无边框窗口的博客：[如何在pyqt中自定义无边框窗口](https://www.cnblogs.com/zhiyiYo/p/14659981.html)

**Comment by 1197730656** [comment]
> > self.setWindowFlags(Qt.FramelessWindowHint) 加上这个可以解决那个问题
> 
> 直接加上这个标志位会导致窗口无法拉伸、没有窗口阴影、最大化和最小化动画，这些本来就是 PyQt-Frameless-Window 项目解决的问题

PyQt-Frameless-Window中无法设置背景透明 通过继承项目中的framelesswindow、加上那个标志位和重写鼠标移动事件即可实现窗口移动和拉伸和窗口背景透明

**Comment by zhiyiYo** [comment]
如果你不想要窗口阴影，只想要透明背景，可以这么干
```python
from qframelesswindow.utils import startSystemMove


class ResLabel(QLabel, FramelessWindow):

    def __init__(self, *args, **kwargs):
        super(ResLabel, self).__init__(*args, **kwargs)
        self.titleBar.hide()
        self.setWordWrap(True)
        self.setAlignment(QtCore.Qt.AlignLeading |
                          QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.setStyleSheet('''QLabel{background:rgba(10,10,255,0.1);border:3px solid rgba(255, 0, 0,0.5)}''')
        palette = QPalette()
        palette.setColor(self.backgroundRole(), QColor(10, 10, 255, 26))
        self.setPalette(palette)
        self.setText('我想学C++' * 9)
        self.windowEffect.removeShadowEffect(self.winId())

    def mousePressEvent(self, e):
        if sys.platform == "win32":
            return

        startSystemMove(self, e.globalPos())

    def mouseMoveEvent(self, e):
        if sys.platform != "win32":
            return

        startSystemMove(self, e.globalPos())
```
