### ISSUE TITLE
为什么主窗口继承 QWidget 而不是 QMainWindow?

### ISSUE THREAD

**Issue by Mr-ZBin** [zhiyiYo/PyQt-Frameless-Window#24]
在 _qframelesswindow/windows/__init__.py_ 中的 **class WindowsFramelessWindow(QWidget)** 继承了**QWidget**，而不是**QMainWindow**。请问这样是有什么特别的需求吗？因为使用QWidget就不能直接使用 比如 **addDockWidget** 之类的函数了。已经点赞收藏，谢谢博主的作品。

**Comment by zhiyiYo** [comment]
QWidget 用的比较多吧，不是所有界面都需要菜单栏、状态栏和堆叠窗口

**Comment by Mr-ZBin** [comment]
谢谢博主如果快速的回答，我自学的Python和PyQt，对PyQt的理解还不是很深，谢谢博主😀。

**Comment by zhiyiYo** [comment]
😃可以看看一些实战项目的源码加深理解，readme的 see also 里面给了一些

**Comment by Mr-ZBin** [comment]
好的，非常感谢啦
