### ISSUE TITLE
pyinstaller打包成exe运行后报错，ModuleNotFoundError: No module named 'qframelesswindow'

### ISSUE THREAD

**Issue by eggegg2001** [zhiyiYo/PyQt-Frameless-Window#25]
我是新手，肯能会犯一些低级错误，希望得到帮助

**Comment by eggegg2001** [comment]
我尝试了如下办法，都不行
pyinstaller gui.py
pyinstaller --path 'C:\Python310\Lib\site-packages\qframelesswindow' gui.py
pyinstaller --hidden-import qframelesswindow gui.py
pyinstaller gui.py -F -p C:\Python310\Lib\site-packages\qframelesswindow
都是报错“oduleNotFoundError: No module named 'qframelesswindow'”

**Comment by zhiyiYo** [comment]
你有试过在虚拟环境打包吗

**Comment by eggegg2001** [comment]
打包是成功的，是运行exe后报错

**Comment by zhiyiYo** [comment]
代码可以分享一下吗

**Comment by eggegg2001** [comment]
我现在试试在虚拟环境打包看看
代码内容大致如下，我就是要实现pyqt仿windows Terminal的效果。
`import sys
from qframelesswindow import AcrylicWindow
from time import sleep
from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSignal, QThread
from PyQt5.QtGui import QTextCursor
from PyQt5.QtWidgets import QTextEdit


class MainUi(AcrylicWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(800, 600)
        self.init_ui()

        self.th = MyThread()
        self.th.signalForText.connect(self.onUpdateText)
        sys.stdout = self.th

    def onUpdateText(self, text):
        cursor = self.process.textCursor()
        cursor.movePosition(QTextCursor.End)
        cursor.insertText(text)
        self.process.setTextCursor(cursor)
        self.process.ensureCursorVisible()

    def init_ui(self):
        self.process = QTextEdit(self, readOnly=True)
        self.process.ensureCursorVisible()
        self.process.setLineWrapColumnOrWidth(800)
        self.process.setLineWrapMode(QTextEdit.FixedPixelWidth)
        self.process.setFixedWidth(800)
        self.process.setFixedHeight(570)
        self.process.move(0, 30)
        self.process.setStyleSheet(
            '''
            QTextEdit{
                border:none;
                font-size:20px;
            }
            '''
        )

    def closeEvent(self, event):
        # Return stdout to defaults.
        sys.stdout = sys.__stdout__
        super().closeEvent(event)


class MyThread(QThread):
    signalForText = pyqtSignal(str)

    def __init__(self, data=None, parent=None):
        super(MyThread, self).__init__(parent)
        self.data = data

    def write(self, text):
        self.signalForText.emit(str(text))  # 发射信号

    def run(self):
        # 演示代码
        for i in range(5):
            print(i)
            sleep(1)
        print("End")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.aboutToQuit.connect(app.deleteLater)
    gui = MainUi()
    gui.show()
    gui.th.start()
    sys.exit(app.exec_())
`

**Comment by eggegg2001** [comment]
我现在试试在虚拟环境打包看看
代码内容大致如下，我就是要实现pyqt仿windows Terminal的效果。
`import sys
from qframelesswindow import AcrylicWindow
from time import sleep
from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSignal, QThread
from PyQt5.QtGui import QTextCursor
from PyQt5.QtWidgets import QTextEdit


class MainUi(AcrylicWindow):
    def __init__(self):
        super().__init__()
        self.setFixedSize(800, 600)
        self.init_ui()

        self.th = MyThread()
        self.th.signalForText.connect(self.onUpdateText)
        sys.stdout = self.th

    def onUpdateText(self, text):
        cursor = self.process.textCursor()
        cursor.movePosition(QTextCursor.End)
        cursor.insertText(text)
        self.process.setTextCursor(cursor)
        self.process.ensureCursorVisible()

    def init_ui(self):
        self.process = QTextEdit(self, readOnly=True)
        self.process.ensureCursorVisible()
        self.process.setLineWrapColumnOrWidth(800)
        self.process.setLineWrapMode(QTextEdit.FixedPixelWidth)
        self.process.setFixedWidth(800)
        self.process.setFixedHeight(570)
        self.process.move(0, 30)

    def closeEvent(self, event):
        # Return stdout to defaults
        sys.stdout = sys.__stdout__
        super().closeEvent(event)


class MyThread(QThread):
    signalForText = pyqtSignal(str)

    def __init__(self, data=None, parent=None):
        super(MyThread, self).__init__(parent)
        self.data = data

    def write(self, text):
        self.signalForText.emit(str(text))  # 发射信号

    def run(self):
        # 演示代码
        for i in range(5):
            print(i)
            sleep(1)
        print("End")


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.aboutToQuit.connect(app.deleteLater)
    gui = MainUi()
    gui.show()
    gui.th.start()
    sys.exit(app.exec_())
`

**Comment by zhiyiYo** [comment]
我用 readme 里面给出的 demo 打包是没有问题的

**Comment by zhiyiYo** [comment]
你的代码在虚拟环境中也能正常打包和运行
![image](https://user-images.githubusercontent.com/65096819/197918826-6cbb723d-3a90-4fcb-a904-ae2aa3265d9d.png)
