### ISSUE TITLE
How to remove the titlebar completely ?

### ISSUE THREAD

**Issue by jailne-su** [zhiyiYo/PyQt-Frameless-Window#26]
I am developing a Desktop Widget on Windows using this library, which is great for me. But when I try to dide the buttons or just delete the titlebar, it always got a fixed padding left on the right side. I can't drag the window in this area, I can't also make the window size smaller than this padding. Is it a bug or it is just me have to do some tweaks?

**Comment by zhiyiYo** [comment]
建议换成中文提问，表达可以清晰一些

**Comment by jailne-su** [comment]
我在写一个桌面小组件之类的小程序。我想要隐藏标题栏的按钮，但是窗口总会剩下那么一点点空间，高度和宽度没办法再缩小。请问我该怎么修改才能完全去掉标题栏呢？

还有就是，请问怎么隐藏任务栏里的图标？

在 Github 上，我觉得用英语提 issue 会方便检索一些。

以上，感谢您。

**Comment by zhiyiYo** [comment]
你是直接把按钮隐藏了，然后没有隐藏标题栏吗？如果没有隐藏任务栏的话，最后会剩下任务栏的高度 32px

**Comment by zhiyiYo** [comment]
你调用  `self.hide()` 就能隐藏窗口以及任务栏的图标了

**Comment by zhiyiYo** [comment]
如果隐藏了标题栏，但是想要拖动窗口的话，可以在主界面的 `mouseMoveEvent`（Windows 系统）或者 `mousePressEvent` （Linux系统）中调用 `utils.startSystemMove(window, globalPos)`，具体写法参见 `TitleBar` 源代码

**Comment by jailne-su** [comment]
Titlebar 貌似是隐藏了，因为左侧也不相应鼠标拖动了，可是还是剩下来一截哈.....

![截图](https://i.niupic.com/images/2022/11/05/aah8.PNG)

**Comment by jailne-su** [comment]
还有就是我并不是要隐藏整个窗口，只想把任务栏图标给隐藏了，我试了下直接在 `Window `类的初始化方法里写 self.hide()` self.hide()`，貌似没有作用。

**Comment by zhiyiYo** [comment]
你可以添加下面这三行代码实现无任务栏图标以及窗口任意大小：
```python
self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint | Qt.Tool)
self.windowEffect.addWindowAnimation(self.winId())
self.windowEffect.addShadowEffect(self.winId())
```

**Comment by jailne-su** [comment]
谢谢您。我试了一下，还是有点小问题：

首先其实我昨天试过 `Qt.Tool` ，结果窗口动画、阴影全掉了，您今天提供的解决方案应该是通过：
```
self.windowEffect.addWindowAnimation(self.winId())
self.windowEffect.addShadowEffect(self.winId())
```
解决这个问题。

但是我发现窗口动画还是掉了，貌似只有：`self.windowEffect.addShadowEffect(self.winId())` 起作用了。

这貌似是 `Qt.Tool`  这个属性引发的问题。

对于**隐藏状态栏图标**，我查了一下 [MSDN](https://learn.microsoft.com/zh-cn/windows/win32/shell/taskbar) 和 [Stackoverflow](https://stackoverflow.com/questions/50181011/python-taskbar-tasks)，里面提到两个解决方案：

1. 给窗口设置扩展样式 `WS_EX_TOOLWINDOW`，我尝试改了一下 `window_effect.py` 里的 `addWindowAnimation` 方法，把 `win32con.WS_EX_TOOLWINDOW` 加到那一排 `style` 里，不起作用。
2. 调用 `ITaskbarList` [接口](https://learn.microsoft.com/zh-cn/windows/win32/api/shobjidl_core/nn-shobjidl_core-itaskbarlist)，删掉指定窗口的任务栏按钮，我没有 win32 开发相关的经验，请问您能否写个范例我看看？

对于**隐藏窗口按钮**（最大、最小化），是 `Qt.Tool` 在起作用。可这个 Flag 会引发我刚刚说的问题，我很好奇为什么这个无边框窗口会留下这点空间......

感谢您回复我。

**Comment by zhiyiYo** [comment]
因为你没加  `self.titleBar.hide()` 所以会出现标题栏的按钮，我不是很明白为什么需要窗口动画，你已经把标题栏去掉了，应该不需要最大化最小化功能才对啊
