### ISSUE TITLE
How to change acrylic transparency and degree of blur?

### ISSUE THREAD

**Issue by jailne-su** [zhiyiYo/PyQt-Frameless-Window#27]
如图，用 Acrylic 效果感觉背景模糊不够透，即使在参数里设置的颜色是 `01010100` 也只是让背景变黑了。有一篇博客园上的[文章](https://www.cnblogs.com/dino623/p/acrylic.html)讲了在UWP上通过自定义 `AcrylicBrush` 解决这种问题。

![screenshot](https://i.niupic.com/images/2022/11/05/aahT.PNG)

网上的另一个项目 [Countboard](https://github.com/Gaoyongxian666/CountBoard) 用到了你的代码，好奇为啥这个显得就没那么黑。

![Countboard](https://i.niupic.com/images/2022/11/05/aahU.PNG)

**Comment by zhiyiYo** [comment]
可以提供一下代码吗，我测试一下

**Comment by jailne-su** [comment]
是指我的项目的代码吗？我稍后发上来。

**Comment by zhiyiYo** [comment]
不需要整个项目的代码，只需要能复现你图中所示的窗口的最小测试代码

**Comment by jailne-su** [comment]
好的。

[Talk is Cheap, Show me your Code.](https://gist.github.com/jailne-su/856b243a90dcb3675fee0c7b4ee7c6a7)

**Comment by zhiyiYo** [comment]
你加上下面这两行代码试试：
```python
self.windowEffect.addWindowAnimation(self.winId())
self.windowEffect.setAcrylicEffect(self.winId(), "F2F2F299")
```

**Comment by jailne-su** [comment]
哈哈，上午试过这个方法，的确是让背景颜色变白了，但是问题是当我把 rgba 颜色的透明度调低，背景并不会变得更**透明**，而是会变黑。不过我设成白色就好了，谢谢您。
