### ISSUE TITLE
Windows 7 Bugs

### ISSUE THREAD

**Issue by wuxian425** [zhiyiYo/PyQt-Frameless-Window#28]
[record.webm](https://user-images.githubusercontent.com/82699919/201508910-61442219-1c0b-41b3-90c3-06acdd73a3d4.webm)
如视频，在非Aero模式时按钮发生鬼畜（？
[record 2.webm](https://user-images.githubusercontent.com/82699919/201509152-bcc3a083-8b0e-4f56-b199-14d2441f2ef1.webm)
在压克力模式下倒没什么问题，只是没有压克力效果罢了 
[record3.webm](https://user-images.githubusercontent.com/82699919/201509269-e335e29f-7037-408a-b82d-6b2b2c74189f.webm)
两者在 Aero 模式下压克力模式表现良好，一般模式的 Hover 令人迷惑

**Comment by zhiyiYo** [comment]
感谢反馈，如果把 qframelesswindow/windows/window_effect.py 替换成压缩包中的 py 文件还有这些问题吗？
[window_effect.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/9996686/window_effect.zip)

**Comment by wuxian425** [comment]
Record3.webm 标示的 Bug 依然存在，Record.webm 标示的 Bug 变成了一开启项目直接原生按钮在顶层，然后鼠标悬浮后两者在争顶层（如原 Record.webm），Record2 不变

**Comment by zhiyiYo** [comment]
record3 我没怎么看懂，是标题栏按钮按不了以及 hover 不起作用吗

**Comment by wuxian425** [comment]
> record3 我没怎么看懂，是标题栏按钮按不了以及 hover 不起作用吗

标题栏按钮按的了，不过按的貌似跟原生按钮冲突了，Hover 不起作用

**Comment by zhiyiYo** [comment]
如果把 qframelesswindow/windows/__init__.py 的第 32 行改为 `self.setWindowFlags(Qt.FramelessWindowHint)`，还会有这些问题吗

**Comment by wuxian425** [comment]
> 如果把 qframelesswindow/windows/__init__.py 的第 32 行改为 `self.setWindowFlags(Qt.FramelessWindowHint)`，还会有这些问题吗

完全好了！

**Comment by zhiyiYo** [comment]
可以再帮忙测试一下改成 `self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinMaxButtonsHint)` 的效果吗？如果只有 `self.setWindowFlags(Qt.FramelessWindowHint)` 可能会导致点击任务栏按钮无法隐藏/显示窗口

**Comment by wuxian425** [comment]
> 可以再帮忙测试一下改成 `self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinMaxButtonsHint)` 的效果吗？如果只有 `self.setWindowFlags(Qt.FramelessWindowHint)` 可能会导致点击任务栏图标无法隐藏/显示窗口

- 非 Aero 使用正常
- Aero 使用正常
- Windows Classic 使用正常

**Comment by zhiyiYo** [comment]
万分感谢，如果改成下述代码是不是就又会引发之前的哪些问题了？
```python
self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinMaxButtonsHint | Qt.WindowSystemMenuHint)
```

**Comment by wuxian425** [comment]
> 万分感谢，如果改成下述代码是不是就又会引发之前的那些问题了？
> 
> ```python
> self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowMinMaxButtonsHint | Qt.WindowSystemMenuHint)
> ```

正确的

**Comment by zhiyiYo** [comment]
好的，非常感谢
