### ISSUE TITLE
关于windowEffect

### ISSUE THREAD

**Issue by mr-52hz** [zhiyiYo/PyQt-Frameless-Window#3]
您好，使用您的windowEffect解决方案时，我发现，控件只能以窗口的形式存在（效果很满意）。我想将图片作为背景有亚克力效果，有点像音乐播放器的歌手作为背景，上面可以显示歌词那种（AppleMusic）效果，我尝试了很多次，都不能将windowEffect使用到背景图片上，您有好的解决办法吗，十分感谢。

**Comment by zhiyiYo** [comment]
@mr-52hz 
我之前有写过一个模仿亚克力效果的小部件，代码可以从 [acrylic_label](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/master/widgets/acrylic_label) 获取，感觉效果还行，搭配 QThread 使用应该就不会卡住界面了
