### ISSUE TITLE
如何使用WindowChrome？

### ISSUE THREAD

**Issue by St-Luo** [zhiyiYo/PyQt-Frameless-Window#30]
看到了一篇[文章](http://blog.walterlv.com/post/wpf-simulate-native-window-style-using-window-chrome.html)，介绍了WPF如何允许鼠标在窗口阴影处进行窗口缩放，和给窗口添加系统主题色边框
如果有这两个细节……感觉会更好一点……
那篇文章里的对比图：
![图片](https://user-images.githubusercontent.com/75152171/205537535-1bec8a86-c516-4a04-ae15-7d90c9718682.png)
他里面说要用到“WindowChrome”，但是不知道他这个WindowChrome是怎么用的，请问大佬知道怎么用嘛……
希望能加入这两个细节

**Comment by zhiyiYo** [comment]
这个和 Qt 差太多了吧，表示无能为力😕
