### ISSUE TITLE
自动切换主题

### ISSUE THREAD

**Issue by crazy-zxx** [zhiyiYo/PyQt-Frameless-Window#33]
最近想写一个软件，希望可以
①自定义窗口标题栏
②软件的主题可以跟随系统主题自动切换白天、黑暗模式
这个项目很好的解决了第一个问题，对于第二个问题我发现有一个开源项目实现了自动切换主题的项目[PyQtDarkTheme](https://github.com/5yutan5/PyQtDarkTheme) ，但是不知道如何结合这两个项目一起使用，开发大佬可以指点一下吗？

Thanks.

**Comment by zhiyiYo** [comment]
你可以用 [darkdetect](https://github.com/albertosottile/darkdetect) 包来检测系统的亮暗模式

**Comment by crazy-zxx** [comment]
非常感谢，我去试试
