### ISSUE TITLE
黑暗模式下窗口按钮颜色更新问题

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Frameless-Window#34]
感谢作者的开源！
我自己的软件，做了两套qss，来适配dark mode，由于三大按钮是黑色，导致在黑暗模式下，直接消失看不到。
看了下源码，发现可以用updatestyle来更新按钮颜色。
` "normal": {
                "color": (0, 0, 0),
                'background': (0, 0, 0, 26)
            }`
然后发现关闭按钮无法更新，再次看源码，发现关闭按钮是svg，而另外两个按钮是画的。
建议作者把另外两个图标都用svg，这样高分屏下面图标一致性好一点，在高分屏下，最小化最大化的图标和关闭按钮明显不一致,并且使用update style的时候也不会感到疑惑。

再次感谢作者的开源

**Comment by zhiyiYo** [comment]
可以截个图看看高分屏下按钮长什么样吗
![image](https://user-images.githubusercontent.com/65096819/210587870-0f88591e-6b68-40f4-96f4-da3752a36bed.png)

**Comment by Cheukfung** [comment]
放大图片看会觉得svg更模糊，但视觉上看，画的图标很细，svg看起来反而很适合。
<img width="206" alt="1" src="https://user-images.githubusercontent.com/14865236/210591164-96b3f36a-1c51-4717-85ed-297c332864b7.png">

**Comment by zhiyiYo** [comment]
感觉还好，chrome 应该也这么细吧

**Comment by Cheukfung** [comment]
系统图标的效果，肉眼看其实还是有分别
<img width="140" alt="2" src="https://user-images.githubusercontent.com/14865236/210594193-a9971606-f471-4c0d-ae16-adffddbeb88f.png">

**Comment by zhiyiYo** [comment]
换成svg就不好控制颜色了，而且在1920*1080分辨率，dpi缩放比125％下看起来有点糊🤔

**Comment by zhiyiYo** [comment]
@Cheukfung 
我重构了标题栏按钮，现在你可以使用 `SvgTitleBarButton` 类自定义标题栏图标，同时可以更改按钮图标颜色和背景色，使用方法参见 [demo.py](https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/demo.py)。

**注意**：`TitleBarButton.updateStyle` 函数由于安全问题已被弃用
