### ISSUE TITLE
Dialog在macOS下有bug

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Frameless-Window#35]
感谢更新三大按钮样式定制！
再次反馈一个bug
之前我用多继承实现无边框dialog的时候，就发现在macOS下，仍然会有一个没有关闭按钮的边框，不过我的软件用户都是windows用户，所以没多想，后来发现作者更新了无边框Dialog，试了下，依然不行。
<img width="638" alt="image" src="https://user-images.githubusercontent.com/14865236/211202411-88f74204-3721-4c46-b6e2-5eef96152fbc.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/14865236/211202515-4f54679c-69ee-4093-8e84-22c84623344d.png">

**Comment by zhiyiYo** [comment]
感谢反馈，目前我没有macOS的测试条件，可能只能靠各位自行解决了🥲

**Comment by Cheukfung** [comment]
那等我周末试试，不过技术有限，毕竟只是爱好者不是职业的😂

**Comment by Genymobile1** [comment]
@Cheukfung @zhiyiYo

**Comment by zhiyiYo** [comment]
@Cheukfung 
有什么进展吗？

**Comment by zhiyiYo** [comment]
@xianyongjian080402 
如果在 `qframelesswindow/__init__.py` 的 `FramelessDialog__init__()`  最后添加下述代码能隐藏掉对话框的标题栏吗：
```python
import Cocoa
import objc

view = objc.objc_object(c_void_p=self.winId().__int__())
window = view.window()
window.setStyleMask_(window.styleMask() | Cocoa.NSFullSizeContentViewWindowMask)
window.setTitlebarAppearsTransparent_(True)
```

**Comment by zhiyiYo** [comment]
😕

**Comment by zhiyiYo** [comment]
@xianyongjian080402 
如果换成下述代码可以 work 吗？
```python
self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
```

**Comment by xianyongjian080402** [comment]
> @xianyongjian080402 如果更换成下面描述的代码可以工作吗？
> 
> ```python
> self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
> ```

![截屏2023-02-26 10 04 47](https://user-images.githubusercontent.com/70191815/221388291-b58d9da7-9989-4746-a25e-8436a5698f61.png)

this? I's ok,but…窗口没圆角
![截屏2023-02-26 10 06 25](https://user-images.githubusercontent.com/70191815/221388337-7060aaa6-1cb8-43b5-b269-ec68bab266e6.png)

**Comment by xianyongjian080402** [comment]
> > @xianyongjian080402如果更换下面描述的代码可以工作吗？
> > ```python
> > self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
> > ```
> 
> ![截图2023-02-26 10 04 47](https://user-images.githubusercontent.com/70191815/221388291-b58d9da7-9989-4746-a25e-8436a5698f61.png)
> 
> 这？我很好，但是……窗口没有圆角 ![截图2023-02-26 10 06 25](https://user-images.githubusercontent.com/70191815/221388337-7060aaa6-1cb8-43b5-b269-ec68bab266e6.png)

![截屏2023-02-26 10 06 51](https://user-images.githubusercontent.com/70191815/221388351-fa618fb7-36c0-4e2c-bb17-efb5bf88d67f.png)

**Comment by qianye216** [comment]
作者你好，我这发现如果Mac下Dialog双击titlebar的话就会自动隐藏顶部多余的边框，因个人能力有限，查看代码发现双击会执行__toggleMaxState方法，看看这里是否有啥启发
![image](https://user-images.githubusercontent.com/8281775/222859757-b5504617-389d-46be-9896-b578b8280ff2.png)
![image](https://user-images.githubusercontent.com/8281775/222859770-97a45363-b4a6-4ec4-9010-3e64cf4233c9.png)

**Comment by zhiyiYo** [comment]
@qianye216 
感谢帮忙测试，但是双击之后对话框不是会最大化吗

**Comment by zhiyiYo** [comment]
@qianye216 
而且我把无边框对话框双击标题栏最大化的功能禁用了，双击 `FramelessWindow.titleBar` 不会调用 `__toggleMaxState()` 函数：
```python
def mouseDoubleClickEvent(self, event):
    """ Toggles the maximization state of the window """
    if event.button() != Qt.LeftButton or not self._isDoubleClickEnabled:  # 无边框对话框的 _isDoubleClickEnabled 为 False
        return

    self.__toggleMaxState()
```

你双击的标题栏是系统自带的那个吗？

**Comment by qianye216** [comment]
> @qianye216 我把无边框对话框双击标题栏最大化的功能禁用了，双击 `FramelessWindow.titleBar` 不会调用 `__toggleMaxState()` 函数：
> 
> ```python
> def mouseDoubleClickEvent(self, event):
>     """ Toggles the maximization state of the window """
>     if event.button() != Qt.LeftButton or not self._isDoubleClickEnabled:  # 对话框标题栏的 _isDoubleClickEnabled 为 False
>         return
> 
>     self.__toggleMaxState()
> ```
> 
> 你双击的标题栏是系统自带的那个吗？

我是双击的自定义的标题栏

**Comment by zhiyiYo** [comment]
> 我是双击的自定义的标题栏
神奇，感觉可以在无边框对话框的构造函数里面发一个鼠标双击事件给标题栏，看看能不能隐藏掉系统自带的，你可以试下吗

**Comment by qianye216** [comment]
> 

能贴下代码吗

**Comment by zhiyiYo** [comment]
> > 
> 
> 能贴下代码吗

好的，我回去发下

**Comment by qianye216** [comment]
> > > 
> > 
> > 
> > 能贴下代码吗
> 
> 好的，我回去发下

好的，麻烦了

**Comment by zhiyiYo** [comment]
@qianye216 
`qframelesswindow/__init__.py` 的 `FramelessDialog` 改成这样可以吗：
```python
from PyQt5.QtCore import QEvent, QPoint, Qt
from PyQt5.QtGui import QMouseEvent
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow

class FramelessDialog(QDialog, FramelessWindow):
    """ Frameless dialog """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.titleBar.minBtn.hide()
        self.titleBar.maxBtn.hide()
        self.titleBar.setDoubleClickEnabled(False)

        if sys.platform == "darwin":
            e = QMouseEvent(
                QEvent.MouseButtonDblClick,
                QPoint(),
                Qt.LeftButton,
                Qt.LeftButton,
                Qt.NoModifier
            )
            QApplication.sendEvent(self.titleBar, e)
```

**Comment by qianye216** [comment]
> ```python
> from PyQt5.QtCore import QEvent, QPoint, Qt
> from PyQt5.QtGui import QMouseEvent
> from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow
> ```

还是不行

**Comment by zhiyiYo** [comment]
你可以录个屏演示一下双击的效果吗

**Comment by qianye216** [comment]
> @qianye216 `qframelesswindow/__init__.py` 的 `FramelessDialog` 改成这样可以吗：
> 
> ```python
> from PyQt5.QtCore import QEvent, QPoint, Qt
> from PyQt5.QtGui import QMouseEvent
> from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow
> 
> class FramelessDialog(QDialog, FramelessWindow):
>     """ Frameless dialog """
> 
>     def __init__(self, parent=None):
>         super().__init__(parent)
>         self.titleBar.minBtn.hide()
>         self.titleBar.maxBtn.hide()
>         self.titleBar.setDoubleClickEnabled(False)
> 
>         if sys.platform == "darwin":
>             e = QMouseEvent(
>                 QEvent.MouseButtonDblClick,
>                 QPoint(),
>                 Qt.LeftButton,
>                 Qt.LeftButton,
>                 Qt.NoModifier
>             )
>             QApplication.sendEvent(self.titleBar, e)
> ```

我的对话框窗口继承了FramelessDialog的同时也自定义了StandardTitleBar，这种情况双击自定义的标题栏就会隐藏顶部那个多余的标题栏，如果不用StandardTitleBar，那双击标题栏也不会隐藏那个多余的标题栏

**Comment by zhiyiYo** [comment]
双击的是标题栏的哪个位置呀？title 区域吗？还是说空白区域？可以录屏演示一下吗，qq应该可以很方便的录屏

**Comment by qianye216** [comment]
> 双击的是标题栏的哪个位置呀？title 区域吗？还是说空白区域？可以录屏演示一下吗，qq应该可以很方便的录屏

稍等

**Comment by qianye216** [comment]
> 你可以录个屏演示一下双击的效果吗

![image](https://user-images.githubusercontent.com/8281775/222877200-7142d95d-d322-45d0-bea4-a8ade009b7d8.png)
就双击这个区域，我看代码是不是触发了以下代码自动隐藏了系统标题栏
```
def changeEvent(self, event):
        super().changeEvent(event)
        if event.type() == QEvent.WindowStateChange:
            self.__hideSystemTitleBar()
```

**Comment by zhiyiYo** [comment]
可以在 `__hideSystemTitleBar() `里面加个断点看看双击的时候会不会调用 `__hideSystemTitleBar()`，你现在是自定义标题栏的话应该双击可以最大化把？

**Comment by qianye216** [comment]
> 

加了断点好像没触发调用__hideSystemTitleBar，不知道是不是我操作的问题

**Comment by qianye216** [comment]
> 可以在 `__hideSystemTitleBar() `里面加个断点看看双击的时候会不会调用 `__hideSystemTitleBar()`，你现在是自定义标题栏的话应该双击可以最大化对话框吧？

![QQ20230304-131757](https://user-images.githubusercontent.com/8281775/222877734-c3578c88-4aff-4467-a3cc-5dae3c6a5c66.gif)

**Comment by zhiyiYo** [comment]
我有点小问题：
1. 双击标题栏之后对话框自动跑到左下角了吗？
2. 为啥你的最大化按钮的图标在对话框没有最大化的时候显示的是 还原 图标

**Comment by qianye216** [comment]
> 我有点小问题：
> 
> 1. 双击标题栏之后对话框自动跑到左下角了吗？
> 2. 为啥你的最大化按钮的图标在对话框没有最大化的时候显示的是 还原 图标

1、双击标题栏之后对话框会自动跑到左下角
2、确实是这样，打开窗口后默认显示的是还原图标

**Comment by zhiyiYo** [comment]
你有在代码中对无边框对话框和标题栏做其他的操作吗？如果显示的是还原图标，只可能是窗口此时处于最大化状态

**Comment by qianye216** [comment]
> 我有点小问题：
> 
> 1. 双击标题栏之后对话框自动跑到左下角了吗？
> 2. 为啥你的最大化按钮的图标在对话框没有最大化的时候显示的是 还原 图标

其中

> 你有在代码中对无边框对话框和标题栏做其他的操作吗？如果显示的是还原图标，只可能是窗口此时处于最大化状态

我这个窗口是在UI Designer中设计的，最小宽高和最大宽高都写死成一样的数值了

**Comment by zhiyiYo** [comment]
也许确实是 `__toogleMaxState()` 的问题，可以打印一下 `self.window().isMaximized()` 吗？感觉应该一直是 `False` 才对，顺便在 FramelessDialog 的构造函数里面也打印一下看看（感觉此时会是 `True`）：
```python
def __toggleMaxState(self):
    """ Toggles the maximization state of the window and change icon """
    print(self.window().isMaximized())
    if self.window().isMaximized():
        self.window().showNormal()
    else:
        self.window().showMaximized()
```

**Comment by qianye216** [comment]
> ```python
> print(self.window().isMaximized())
> ```
![image](https://user-images.githubusercontent.com/8281775/222878401-76860958-88b7-432d-86ff-b89dfea992b8.png)
双击标题栏会在True和False之间切换

**Comment by zhiyiYo** [comment]
只移动到左下角的原因可能是调用了 `self.window().showMaximized()`，但是窗口的尺寸又被设定为固定值，导致无法顺利最大化。反复双击的话系统的标题栏不会再度出现吗

**Comment by qianye216** [comment]
> 只移动到左下角的原因可能是调用了 `self.window().showMaximized()`，但是窗口的尺寸又被设定为固定值，导致无法顺利最大化。反复双击的话系统的标题栏不会再度出现吗

对的，只要双击后系统标题栏就不会显示，关闭窗口重新打开就又出现了

**Comment by zhiyiYo** [comment]
我不太确定第一次双击标题栏时到底调用的是 `showNormal` 还是 `showMaximized`，你可以测试一下吗

**Comment by qianye216** [comment]
> 我不太确定第一次双击标题栏时到底调用的是 `showNormal` 还是 `showMaximized`，你可以测试一下吗

不管调用showNormal还是 showMaximized都会隐藏系统标题栏，如果我固定窗口大小，第一次双击标题栏就是调用showNormal，如果我不固定窗口大小，第一次双击标题栏就是调用showMaximized，这两种情况都可以隐藏系统标题栏，是不是双击的时候触发了__hideSystemTitleBar

**Comment by zhiyiYo** [comment]
也许你可以在 `__hideSystemTitleBar()` 打印一下日志看看有没有被调用，我觉得应该是被调用了，可是我之前在无边框对话框的构造函数里面手动调用这个函数不起作用

**Comment by qianye216** [comment]
> 也许你可以在 `__hideSystemTitleBar()` 打印一下日志看看有没有被调用，我觉得应该是被调用了，可是我之前在无边框对话框的构造函数里面手动调用这个函数不起作用

打印日志显示启动窗口的时候也有调用__hideSystemTitleBar，但是还是会显示系统标题栏，只有双击标题栏的时候才会真正隐藏系统标题栏（双击标题栏也会调用__hideSystemTitleBar）

**Comment by zhiyiYo** [comment]
是不是只有窗口在 `show()` 之后调用 `__hideSystemTitleBar` 才有效啊？我觉得可以重载一下 `qframelesswindow/mac/__init__.py` 的 `MacFramelessWindow.showEvent(e)` 函数：
```python
def showEvent(self, e):
    super().showEvent(e)
    self.__hideSystemTitleBar()
```

**Comment by qianye216** [comment]
> 是不是只有窗口在 `show()` 之后调用 `__hideSystemTitleBar` 才有效啊？我觉得可以重载一下 `qframelesswindow/mac/__init__.py` 的 `MacFramelessWindow.showEvent(e)` 函数：
> 
> ```python
> def showEvent(self, e):
>     super().showEvent(e)
>     self.__hideSystemTitleBar()
> ```

试了还是不行

**Comment by zhiyiYo** [comment]
把 `changeEvent(self, event):` 函数给注释掉之后双击标题栏还能隐藏系统标题栏吗？如果还能隐藏就说明不是 `__hideSystemTitleBar()` 起的作用

**Comment by qianye216** [comment]
> 把 `changeEvent(self, event):` 函数给注释掉之后双击标题栏还能隐藏系统标题栏吗？如果还能隐藏就说明不是 `__hideSystemTitleBar()` 起的作用

注释掉这个后双击标题栏就不会隐藏系统标题栏了

**Comment by zhiyiYo** [comment]
还真是 `__hideSystemTitleBar()` 起的作用啊，可以手动调用它又不起作用 🤔

**Comment by zhiyiYo** [comment]
难道说必须搭配 `showNormal` 或者 `showMaxmized` 才管用吗？把 `__toogleMaxState()` 改为下述代码还管用吗：
```python
def __toggleMaxState(self):
    """ Toggles the maximization state of the window and change icon """
    self.__hideSystemTitleBar()
```

**Comment by qianye216** [comment]
> 还真是 `__hideSystemTitleBar()` 起的作用啊，可以手动调用它又不起作用 🤔

是的，不知道啥原因

> ```python
> self.__hideSystemTitleBar()
> ```

这种也不管用，只有触发changeEvent才会隐藏系统标题栏

**Comment by zhiyiYo** [comment]
如果是这样的话，你应该可以手动调用一次 `showNormal` 来触发 `changeEvent`：
```python
from PyQt5.QtCore import QEvent, QPoint, Qt
from PyQt5.QtGui import QMouseEvent
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow

class FramelessDialog(QDialog, FramelessWindow):
    """ Frameless dialog """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.titleBar.minBtn.hide()
        self.titleBar.maxBtn.hide()
        self.titleBar.setDoubleClickEnabled(False)

        if sys.platform == "darwin":
            self.showNormal()
```

**Comment by qianye216** [comment]
> 

这种的话会隐藏系统标题栏，但是自定义的标题栏的标题和按钮也不见了，也无法按住拖动窗口
![image](https://user-images.githubusercontent.com/8281775/222879669-87b88776-d3c7-4232-a750-90ca507ce064.png)

**Comment by zhiyiYo** [comment]
再加个 self.titleBar.show() 呢？

**Comment by qianye216** [comment]
> self.titleBar.show()

还是不会正常显示自定义的标题栏

**Comment by zhiyiYo** [comment]
是不是被别的部件挡住了，加个 `self.titleBar.raise_()` 看看？

**Comment by qianye216** [comment]
> ```python
> if sys.platform == "darwin":
>             self.showNormal()
> ```

也不行，而且弹窗的对话框窗口位置也不对，没有相对应父窗口居中显示

**Comment by zhiyiYo** [comment]
累了累了，这个也太诡异了

**Comment by qianye216** [comment]
> 累了累了，这个也太诡异了

没关系，大佬可能过段时间灵光乍现就能找到解决方法^_^

**Comment by zhiyiYo** [comment]
@qianye216 
哈哈，没有测试环境光靠想象力也做不出来捏

**Comment by qianye216** [comment]
> @qianye216 哈哈，没有测试环境光靠想象力也做不出来捏

刚发现如果对话框如果不设置setmodal为true的话就不会显示系统标题栏，应该是这个模态对话框属性导致的

**Comment by zhiyiYo** [comment]
不设置为 true 的话感觉就意义不大了，如果先设置为 false 在设置为 true 系统标题栏还会回来吗

**Comment by qianye216** [comment]
> 不设置为 true 的话感觉就意义不大了，如果先设置为 false 再设置为 true 系统标题栏还会回来吗

不行，只要最后设置为True就有问题

**Comment by xianyongjian080402** [comment]
啊哈

**Comment by zhiyiYo** [comment]
@qianye216 @Cheukfung @xianyongjian080402 
民那桑，这是 chatgpt 生成的 macOS 无边框对话框代码，要不试试看好不好使？
```python
from PyQt5.QtWidgets import QApplication, QDialog
import objc
from Foundation import NSBundle
from AppKit import NSWindow, NSView, NSVisualEffectView, NSVisualEffectBlendingModeBehindWindow, NSRectFillUsingOperation, NSCompositeSourceOver, NSBackingStoreBuffered, NSColor, NSMakeRect

class ShadowDialog(QDialog):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.resize(400, 300)

        # Load the Cocoa framework
        NSBundle.bundleWithPath_('/System/Library/Frameworks/Cocoa.framework').load()

        # Get the window object
        window = self.window().windowHandle().winId()

        # Set the window's style mask
        objc_msgSend = objc.selector(None, selector=b'objc_msgSend')
        mask = objc_msgSend(window, b'styleMask')
        objc_msgSend(window, b'setStyleMask:', mask | (1 << 7) | (1 << 11))

        # Set the window's background color and blending mode
        view = objc_msgSend(window, b'contentView')
        objc_msgSend(view, b'setWantsLayer:', True)
        objc_msgSend(view, b'setLayerContentsRedrawPolicy:', NSBackingStoreBuffered)
        objc_msgSend(view, b'setLayerBackgroundColor:', NSColor.clearColor())
        objc_msgSend(view, b'setBlendingMode:', NSVisualEffectBlendingModeBehindWindow)

        # Add the visual effect view to the content view
        effectView = NSVisualEffectView.alloc().initWithFrame_(NSMakeRect(0, 0, 400, 300))
        effectView.setAutoresizingMask_(NSViewWidthSizable | NSViewHeightSizable)
        effectView.setMaterial_(NSVisualEffectMaterialMediumLight)
        effectView.setBlendingMode_(NSVisualEffectBlendingModeBehindWindow)
        effectView.setState_(NSVisualEffectStateActive)
        objc_msgSend(view, b'addSubview:', effectView)

        # Set the window's shadow properties
        objc_msgSend(window, b'setHasShadow:', True)
        objc_msgSend(window, b'setMovableByWindowBackground:', True)

        # Center the window on the screen
        self.setGeometry(
            QApplication.desktop().screenGeometry().center().x() - self.width() / 2,
            QApplication.desktop().screenGeometry().center().y() - self.height() / 2,
            self.width(),
            self.height()
        )

app = QApplication([])
dialog = ShadowDialog()
dialog.show()
app.exec_()

```

**Comment by zhiyiYo** [comment]
看他代码应该还开启了模糊效果

**Comment by zhiyiYo** [comment]
这是另外一段没有模糊效果的代码：
```python
from PyQt5 import QtWidgets
import sys
import objc
from AppKit import NSWindow, NSMinYMargin, NSWindowStyleMaskBorderless, NSVisualEffectView, NSVisualEffectMaterialAppearanceBased

class NativeDialog(QtWidgets.QDialog):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 创建一个无标题栏的窗口，并将其添加到 PyQt 窗口中
        ns_window = objc.objc_object(c_void_p=int(self.winId()))
        frame = ns_window.frame()
        style = (NSWindowStyleMaskBorderless |
                 NSWindowStyleMaskResizable |
                 NSWindowStyleMaskTitled |
                 NSWindowStyleMaskClosable |
                 NSWindowStyleMaskMiniaturizable |
                 NSWindowStyleMaskFullSizeContentView)

        window = NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(
            frame, style, 2, False)

        window.setTitlebarAppearsTransparent_(True)
        window.setTitleVisibility_(0)
        window.setMinSize_((100, 100))
        window.setContentMinSize_((100, 100))
        window.setMovableByWindowBackground_(True)
        window.setCollectionBehavior_(NSWindowCollectionBehaviorFullScreenPrimary)

        window.contentView().setWantsLayer_(True)
        ns_view = objc.objc_object(c_void_p=int(window.contentView()))
        ns_view.addSubview_(ns_window)

    def show(self):
        super().show()
        QtWidgets.QApplication.processEvents()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    dialog = NativeDialog()
    dialog.setWindowTitle("Hello World")
    dialog.resize(400, 300)
    dialog.show()
    sys.exit(app.exec_())

```

**Comment by qianye216** [comment]
> 



> @qianye216 @Cheukfung @xianyongjian080402 民那桑，这是 chatgpt 生成的 macOS 无边框对话框代码，要不试试看好不好使？
> 
> ```python
> from PyQt5.QtWidgets import QApplication, QDialog
> import objc
> from Foundation import NSBundle
> from AppKit import NSWindow, NSView, NSVisualEffectView, NSVisualEffectBlendingModeBehindWindow, NSRectFillUsingOperation, NSCompositeSourceOver, NSBackingStoreBuffered, NSColor, NSMakeRect
> 
> class ShadowDialog(QDialog):
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.resize(400, 300)
> 
>         # Load the Cocoa framework
>         NSBundle.bundleWithPath_('/System/Library/Frameworks/Cocoa.framework').load()
> 
>         # Get the window object
>         window = self.window().windowHandle().winId()
> 
>         # Set the window's style mask
>         objc_msgSend = objc.selector(None, selector=b'objc_msgSend')
>         mask = objc_msgSend(window, b'styleMask')
>         objc_msgSend(window, b'setStyleMask:', mask | (1 << 7) | (1 << 11))
> 
>         # Set the window's background color and blending mode
>         view = objc_msgSend(window, b'contentView')
>         objc_msgSend(view, b'setWantsLayer:', True)
>         objc_msgSend(view, b'setLayerContentsRedrawPolicy:', NSBackingStoreBuffered)
>         objc_msgSend(view, b'setLayerBackgroundColor:', NSColor.clearColor())
>         objc_msgSend(view, b'setBlendingMode:', NSVisualEffectBlendingModeBehindWindow)
> 
>         # Add the visual effect view to the content view
>         effectView = NSVisualEffectView.alloc().initWithFrame_(NSMakeRect(0, 0, 400, 300))
>         effectView.setAutoresizingMask_(NSViewWidthSizable | NSViewHeightSizable)
>         effectView.setMaterial_(NSVisualEffectMaterialMediumLight)
>         effectView.setBlendingMode_(NSVisualEffectBlendingModeBehindWindow)
>         effectView.setState_(NSVisualEffectStateActive)
>         objc_msgSend(view, b'addSubview:', effectView)
> 
>         # Set the window's shadow properties
>         objc_msgSend(window, b'setHasShadow:', True)
>         objc_msgSend(window, b'setMovableByWindowBackground:', True)
> 
>         # Center the window on the screen
>         self.setGeometry(
>             QApplication.desktop().screenGeometry().center().x() - self.width() / 2,
>             QApplication.desktop().screenGeometry().center().y() - self.height() / 2,
>             self.width(),
>             self.height()
>         )
> 
> app = QApplication([])
> dialog = ShadowDialog()
> dialog.show()
> app.exec_()
> ```

![image](https://user-images.githubusercontent.com/8281775/222933241-31cf22c6-0dda-4307-8202-ff559fdd388c.png)

**Comment by zhiyiYo** [comment]
应该改成 `self.winId()`

**Comment by qianye216** [comment]
> self.winId()

改成这个后提示这个了
![image](https://user-images.githubusercontent.com/8281775/222935681-491b25e4-adb2-49ca-bf5c-65e7cdbd10cf.png)

**Comment by zhiyiYo** [comment]
难绷，chatgpt 很喜欢一本正经胡说八道啊

**Comment by Cheukfung** [comment]
终于有时间测试了。。。
看了下，发现__init__方法里面第一次调用__hideSystemTitleBar是不起作用的，这时候如 @qianye216  说的双击窗口标题栏（或者移动窗口到屏幕边缘）导致类型为WindowStateChange的changeEvent事件发生，这时候会再次调用__hideSystemTitleBar就会起作用（原因未知）。
我的解决方式是：
在paintEvent方法加入self.__hideSystemTitleBar()即可。
<img width="687" alt="image" src="https://user-images.githubusercontent.com/14865236/223039780-043fc47c-02f0-4468-b80c-e267f7efeeef.png">

**Comment by zhiyiYo** [comment]
@Cheukfung 
直接改成这样可以吗：
```python
def paintEvent(self, e):
    super().paintEvent(e)
    self.__hideSystemTitleBar()
```

**Comment by Cheukfung** [comment]
@zhiyiYo 对，效果图晚点发，加了之后就一切正常

**Comment by zhiyiYo** [comment]
感谢

**Comment by zhiyiYo** [comment]
@qianye216 
改了之后你那边还会出现系统标题栏吗？

**Comment by Cheukfung** [comment]
@zhiyiYo 这段show event直接不执行，不知道为什么，其实理论这样才比较好的，paintevent会不断调用hidesystemtitlebar的，不知道会不会有性能问题
 `def showEvent(self, e):
    super().showEvent(e)
    self.__hideSystemTitleBar()`

**Comment by zhiyiYo** [comment]
@Cheukfung 
`showEvent()` 没有被调用过吗？那改成 `show()` 呢？
```python
def show(self):
   super().show()
   self.__hideSystemTitleBar()
```

**Comment by qianye216** [comment]
> @qianye216 改了之后你那边还会出现系统标题栏吗？

paintEvent里改了后正常了

**Comment by zhiyiYo** [comment]
@qianye216 
你的窗口会有性能问题吗？比如界面变卡之类的

**Comment by qianye216** [comment]
> @qianye216 你的窗口会有性能问题吗？比如界面变卡之类的

感觉还好，不卡

**Comment by zhiyiYo** [comment]
@qianye216 
可以录个屏看看最终效果吗，如果没问题的话我打算把补丁 commit 上来了

**Comment by qianye216** [comment]
> @qianye216 可以录个屏看看最终效果吗，如果没问题的话我打算把补丁 commit 上来了


https://user-images.githubusercontent.com/8281775/223062666-82894761-7a14-41d3-92b0-2ac7b6ed4eeb.mp4

**Comment by zhiyiYo** [comment]
万分感谢！
