### ISSUE TITLE
Method _isDragRegion ignores hidden buttons from FramelessDialog

### ISSUE THREAD

**Issue by gilex-dev** [zhiyiYo/PyQt-Frameless-Window#38]
**Describe the bug**
The method `qframelesswindow.titlebar.TitleBar._isDragRegion` ignores hidden buttons from `FramelessDialog` because the [code](https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/b3c4a5a5a2395b1c1e7b325c3640bb3395bb925f/qframelesswindow/titlebar/__init__.py#L76) expects three buttons with a width of 46px each.

**To Reproduce**
1. Create a `FramelessDialog`
2. Try to drag it from a few pixels left from the close button (where usually `minBtn` and `maxBtn` are placed)
3. Window is not draggable until you start dragging from a 'valid' position

**Code**
```python
# Minimum code to reproduce the error
import sys

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QLabel, QHBoxLayout
# from qframelesswindow.titlebar import TitleBar
from qframelesswindow import FramelessDialog


def _isDragRegion(self, pos):
    """ *monkey patch*\
    Check whether the pressed point belongs to the area where dragging is allowed """
    no_drag = 0
    for button in (self.minBtn, self.maxBtn, self.closeBtn):
        if not button.isHidden():
            no_drag += button.width()
    return 0 < pos.x() < self.width() - no_drag


class Dialog(FramelessDialog):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        # TitleBar._isDragRegion = _isDragRegion # monkey patching
        self.setLayout(QHBoxLayout())
        self.layout().addWidget(QLabel('Try to drag me from left of the close button'), 0, Qt.AlignCenter)
        self.titleBar.raise_()


app = QApplication(sys.argv)
window = Dialog()
window.show()
app.exec()

```

**Expected behavior**
Dragging the titlebar next to the close button on a `FramelessDialog` with the minimize and maximize button hidden should work.

**Desktop:**
 - OS: Windows10
 - DPI scaling: 175%

**How I fixed it:**
1. Add this function (calculate sum of the actual width of buttons that are not hidden) to my project:
    ```python
    def _isDragRegion(self, pos):
        """ *monkey patch*\
        Check whether the pressed point belongs to the area where dragging is allowed """
        no_drag = 0
        for button in (self.minBtn, self.maxBtn, self.closeBtn):
            if not button.isHidden():
                no_drag += button.width()
        return 0 < pos.x() < self.width() - no_drag
    ```
2. Monkey patch `_isDragRegion`:
    ```python
    from qframelesswindow.titlebar import TitleBar
    # ...other imports
    class Dialog(FramelessDialog):
        # ...
        TitleBar._isDragRegion = _isDragRegion # monkey patching
        # ...
    ```

To make this even better you could iterate over all visible children of the titlebar that do not have a click/hover event and are visible.

**Comment by zhiyiYo** [comment]
Thank you for reporting this bug. I have fixed it in the new version.
