### ISSUE TITLE
add support to pass widget object as title bar

### ISSUE THREAD

**Issue by YouKnow-sys** [zhiyiYo/PyQt-Frameless-Window#4]
Hi, thank you for great works, its perfect and exactly what I wanted  
but I think one think can make it even better, I mean it will be very good if we can pass a QWidget (or maybe QFrame) to it, in order to use it as a title bar  
in this way we can create our title bar as a part of the whole program in Qt Designer, and then just use it as a title bar by passing widget of it... (in this way we also need to pass the 3 minimize, maximize and close button to it too (or we can leave it to user to handle them)

![](https://user-images.githubusercontent.com/17937017/138158985-7c13b989-85d0-4455-99b4-53841bc50078.png)
and one other thing, please consider commenting your code in english 😅

**Comment by ZouaouiB** [comment]
@YouKnow-sys
I appreciate your concept, and it aligns perfectly with my requirements. Do you believe you could assist me doing that ?

**Comment by ZouaouiB** [comment]
I need you help please, see my post:
https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/143
