### ISSUE TITLE
能否发布个基于pyside6的分支

### ISSUE THREAD

**Issue by Shapaper** [zhiyiYo/PyQt-Frameless-Window#40]
我在从pyside2移植到pyside6时遇到了错误：
![image](https://user-images.githubusercontent.com/88654772/213464687-d02d09e3-3058-4cde-944c-d59eafaf10e9.png)
希望能提供个pyside6的分支以供大家参考

**Comment by zhiyiYo** [comment]
错误原因是啥，图片显示不出来

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213465757-36225479-f19d-4cad-9aed-845b779fe81a.png)

**Comment by Shapaper** [comment]
`Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\tokenize.py", line 385, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:/biancheng/Fandis_Login/Window_client/acrylic_demo.py", line 5, in <module>
    from qframelesswindow import AcrylicWindow
  File "I:\biancheng\Fandis_Login\Window_client\qframelesswindow\__init__.py", line 3, in <module>
    from .titlebar import TitleBar
  File "I:\biancheng\Fandis_Login\Window_client\qframelesswindow\titlebar\__init__.py", line 7, in <module>
    from ..utils import startSystemMove
  File "I:\biancheng\Fandis_Login\Window_client\qframelesswindow\utils\__init__.py", line 5, in <module>
    from .win32_utils import WindowsMoveResize as MoveResize
  File "I:\biancheng\Fandis_Login\Window_client\qframelesswindow\utils\win32_utils.py", line 13, in <module>
    from win32comext.shell import shellcon
  File "I:\biancheng\Fandis_Login\Window_client\venv\lib\site-packages\win32comext\shell\__init__.py", line 2, in <module>
    import win32com
  File "I:\biancheng\Fandis_Login\Window_client\venv\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "I:\biancheng\Fandis_Login\Window_client\venv\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\inspect.py", line 782, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\tokenize.py", line 449, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\tokenize.py", line 426, in detect_encoding
    encoding = find_cookie(first)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\tokenize.py", line 390, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'I:\\biancheng\\Fandis_Login\\Window_client\\venv\\lib\\site-packages\\pywin32_system32\\pywintypes37.dll'

进程已结束，退出代码为 1
`
运行的是 pyside2分支下的acrylic_demo.py 
（已经把pyside2改为pyside6，有一个不存在的库直接注释掉了）

**Comment by zhiyiYo** [comment]
怎么感觉这个报错是 pywin32 的锅，和本仓库无关

**Comment by Shapaper** [comment]
可能是的，请问有什么解决经验供参考嘛

**Comment by zhiyiYo** [comment]
你把什么注释掉了，可以发上来看看嘛

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213467323-86aced2d-5022-4860-baea-d88a2fa97e10.png)

**Comment by zhiyiYo** [comment]
你有试过其他分支的代码会不会报错吗

**Comment by Shapaper** [comment]
还没有，请问您能给个您的dll文件嘛

**Comment by zhiyiYo** [comment]
你直接建个虚拟环境，然后安装 PyQt5 以及 PyQt5-Frameless-Window 包就好了

**Comment by zhiyiYo** [comment]
我是用的 Python3.8，dll应该不一样

**Comment by zhiyiYo** [comment]
测试了一下应该是 win32com 的问题，不过我已经修复了，你可以从 PySide6 分支获取代码

**Comment by Shapaper** [comment]
哈哈，我刚开项目测试，就看到有pyside6分支了

**Comment by Shapaper** [comment]
请问窗口拖动会有延迟是正常现象吗？
我的系统是win10 
![image](https://user-images.githubusercontent.com/88654772/213599294-ba128dd4-ed61-4a48-a3b2-e039ad9b10b2.png)

**Comment by Shapaper** [comment]
拖动时鼠标已经跑了，窗口还慢慢的移动过来，是不是重写了window鼠标信息导致的，python性能不够？
我看到之前的issues里有人说pyside6看起来只能onlywindow了，现在这个分支也是吗

**Comment by Shapaper** [comment]
@zhiyiYo

**Comment by zhiyiYo** [comment]
这个是 win10 的问题，win11 开了亚克力不会这样

**Comment by Shapaper** [comment]
我看到之前的issues里有人说pyside6看起来只能onlywindow了，现在这个分支也是吗

**Comment by zhiyiYo** [comment]
onlywindow是什么意思🤔

**Comment by Shapaper** [comment]
只能在window系统运行

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213602759-b99c3a9c-0292-478b-9a66-fab0151c5e02.png)

**Comment by zhiyiYo** [comment]
目前还不支持 Linux，莫得办法

**Comment by Shapaper** [comment]
嗯，win11的快速布局在这个分支有吗，我这暂时测试不了qwq

**Comment by zhiyiYo** [comment]
暂时没加进去，快速布局有点小问题，具体参见：https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/13

**Comment by Shapaper** [comment]
这个闪动影响使用嘛

**Comment by zhiyiYo** [comment]
不怎么发生，应该不影响使用吧，你可以手动加到自己的代码里面去

**Comment by Shapaper** [comment]
能告诉大概放哪个文件吗

**Comment by zhiyiYo** [comment]
`qframelesswindow/windows/__init__.py` 的 `WindowsFramelessWindow.nativeEvent()` 里面

**Comment by Shapaper** [comment]
问问在win10会报错吗，需要做判断吗

**Comment by zhiyiYo** [comment]
不会报错，放心用吧

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213614654-8695633d-5e62-4be2-97fe-aee888082404.png)
![image](https://user-images.githubusercontent.com/88654772/213614677-dfc93921-d999-4828-9db7-76e0632a98e4.png)
请问大佬这边省略的是什么

**Comment by zhiyiYo** [comment]
WindowsFramelessWindow 的 nativeEvent 里面的代码

**Comment by Shapaper** [comment]
看到了，刚才就发现了，正在改

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213615491-90fa46ed-81f0-4342-ae44-e89ac09b9b99.png)

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213615545-8ad41398-d261-46cc-987a-a8d3c5a5187c.png)
会报错

**Comment by zhiyiYo** [comment]
可能你得改成 `QApplication.sendEvent(self.titleBar.maxBtn, QEnterEvent())` 吧，PyQt5 用 `QEvent` 是不会报错的，我看还是别加快速布局了，加了快速布局之后最大化窗口的时候最大化按钮很容易闪烁

**Comment by Shapaper** [comment]
我找win11的朋友测试下吧qwq

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213617308-4c4b3011-c1e5-4874-bc1f-c2a02d881187.png)

**Comment by Shapaper** [comment]
算了，这个就不用了吧qwq
插个眼，未来假如解决了@我下qwq

**Comment by zhiyiYo** [comment]
Ok

**Comment by Shapaper** [comment]
在win11上的圆角可以自己设定圆角程度吗？

**Comment by zhiyiYo** [comment]
Win11 可以设置更小的圆角，但是具体我忘了具体是哪个枚举成员，还是自己去看下 MSDN 吧

**Comment by Shapaper** [comment]
请问如何移除亚克力效果

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213627059-ea2c2488-93ff-4e7b-a5c6-27ca69291e5e.png)
我在尝试您说的在移动时去除亚克力效果，我目前只发现这个函数重新了移动，我想我需要在启动前后分别加上关闭+开启

**Comment by Shapaper** [comment]
但是似乎Title窗口被继承了许多次，很难将其他py里的值传过来

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213629343-ab02872d-cfb0-483d-9e44-f4990632bcea.png)
似乎可以了，但是我不知到如何去除亚克力

**Comment by Shapaper** [comment]
请问有相关的函数吗

**Comment by Shapaper** [comment]
我搜了很多地方，但大家似乎都自教了如何开启亚克力，没有关闭的

**Comment by zhiyiYo** [comment]
`WindowEffect` 类有一个 removeBackgroundEffect 的函数，但是在移动的时候好像去不掉

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213639524-cc5828f5-c2a3-48c0-ab15-a471339d9d12.png)

**Comment by Shapaper** [comment]
可以了，但是会导致窗口在移动时透明，我想是因为设定为透明的缘故

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213639685-d0f1dfc6-2e9b-4619-884d-ca9603d6b80a.png)
移动状态下的窗口

**Comment by Shapaper** [comment]
我为了实现这个效果改了一部分代码：
![image](https://user-images.githubusercontent.com/88654772/213640717-be0e98e7-2cda-4bb5-b78f-701239159216.png)
多传了些值，程序能正常运行，但是在启动时报错了
![image](https://user-images.githubusercontent.com/88654772/213640866-add0e8ae-2d51-4031-be12-678648becec1.png)

**Comment by Shapaper** [comment]
可以正常运行

**Comment by Shapaper** [comment]
算了，我直接try了吧

**Comment by Shapaper** [comment]
问问，重写放大缩小窗口的函数在哪个文件，我也去弄一下

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213645389-4f6e7fdf-c20f-43a1-b481-d2319549afb9.png)
请问这个代码就是重写放大缩小窗口的吗，return是怎么做到改变窗口大小的qwq

**Comment by zhiyiYo** [comment]
这个是发消息给 Windows 让他来调整大小

**Comment by zhiyiYo** [comment]
> 可以了，但是会导致窗口在移动时透明，我想是因为设定为透明的缘故

你可以重写 paintEvent 或者通过 qss 来设置一个半透明的背景色

**Comment by Shapaper** [comment]
我想知道我remove后为什么会有个灰色的窗口
![image](https://user-images.githubusercontent.com/88654772/213649784-a3b45994-5218-46e8-8512-db693c646bd6.png)

**Comment by Shapaper** [comment]
并且再设置亚克力会导致有这个灰色图层在上面

**Comment by Shapaper** [comment]
严格来说是这个灰色窗口没有自动消失

**Comment by Shapaper** [comment]
感觉是不是remove后，其他组件无法控制移除掉remove的background样式
![image](https://user-images.githubusercontent.com/88654772/213665814-e1f6fc41-08f1-4577-99d1-3f1ec41fbb2b.png)

**Comment by Shapaper** [comment]
@zhiyiYo

**Comment by Shapaper** [comment]
> ![image](https://user-images.githubusercontent.com/88654772/213639524-cc5828f5-c2a3-48c0-ab15-a471339d9d12.png)

这个就是我的实现代码

**Comment by zhiyiYo** [comment]
我的 win11 上不会有这个问题

**Comment by Shapaper** [comment]
az
我打包找我朋友看看

**Comment by zhiyiYo** [comment]
![拖动](https://user-images.githubusercontent.com/65096819/213676998-e50aece2-b538-440b-b871-13d78fbe2c6f.gif)

**Comment by zhiyiYo** [comment]
@Shapaper 
亚克力还是单独开一个 issue 来讨论吧

**Comment by Shapaper** [comment]
ok,等会吧，我这有些事情

**Comment by zhiyiYo** [comment]
@Shapaper 
目前已添加对 Linux 的支持
