### ISSUE TITLE
在win10上remove亚克力后会产生一个灰色窗口

### ISSUE THREAD

**Issue by Shapaper** [zhiyiYo/PyQt-Frameless-Window#41]
如题

**Comment by Shapaper** [comment]
可以在我的另一台win10复现！

**Comment by Shapaper** [comment]
@zhiyiYo 能将您win11的程序打包下发出来嘛

**Comment by zhiyiYo** [comment]
Win11 打包的的程序运行在 Win10 上估计还是会有你所描述的问题，感觉这个锅应该由 Windows 来背

**Comment by Shapaper** [comment]
可以移除这个灰框框吗？
毕竟刚开始运行的时候是没有的，remove完才会一直出现

**Comment by Shapaper** [comment]
我觉得应该是remove在win10水土不服

**Comment by zhiyiYo** [comment]
没有 Win10 的测试条件我也不太好解决这个 bug，[CustomWindow](https://github.com/re7gog/CustomWindow) 是从我的代码改过来的，自称是解决了亚克力拖拽卡顿的问题，或许你可以试试看

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213697959-630b3531-0a8f-4905-a444-e6abff760a05.png)
他的报这个

**Comment by Shapaper** [comment]
和最早说的问题一样了

**Comment by zhiyiYo** [comment]
还是 shellcon 的问题，你把用到的那几个 shellcon 常数用数字来替换就好了

**Comment by Shapaper** [comment]
能够具体说说吗
win32相关的我不太熟练

**Comment by zhiyiYo** [comment]
把 shellcon.XXX 替换成具体的值就好了呀，按住 ctrl 点进去不就能看到这些常量的值吗

**Comment by zhiyiYo** [comment]
```python
ABM_GETSTATE = 4
ABS_AUTOHIDE = 1
ABM_GETTASKBARPOS = 5
```

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/213701174-c3a7925e-5ade-46c6-be3d-4bba6d285469.png)
他是这样写的

**Comment by Shapaper** [comment]
看了半天看不懂了qwq

**Comment by Shapaper** [comment]
没看出来他的原理

**Comment by zhiyiYo** [comment]
他是在这里取消了亚克力效果，估计还是会有你说的那个问题
https://github.com/re7gog/CustomWindow/blob/8336217240b9b6922d993faa49058615e76916d3/custom_window.py#L252

**Comment by Shapaper** [comment]
但是神奇的是他没有

**Comment by Shapaper** [comment]
移动时的确会出现，但是移动完成后立马会消失，那个灰框框

**Comment by Shapaper** [comment]
我问问他这个代码和您的有什么功能上的不同吗

**Comment by zhiyiYo** [comment]
他是在移动一开始取消亚克力然后开了个定时器，定时器一溢出就开启亚克力

**Comment by Shapaper** [comment]
您有什么好的思路嘛，我觉得假如代码量不大的话可以试试。

**Comment by Shapaper** [comment]
同样是remove为什么会有两种结果，真是不理解欸

**Comment by zhiyiYo** [comment]
我看了一下你的代码，为什么用的是 `self.winId` 而不是 `self.winId()`
![image](https://user-images.githubusercontent.com/88654772/213639524-cc5828f5-c2a3-48c0-ab15-a471339d9d12.png)

**Comment by Shapaper** [comment]
因为这边的self获取不到winid，我是传过来的值

**Comment by Shapaper** [comment]
在class的__init__中我把传过来的值保存在了这个变量中

**Comment by Shapaper** [comment]
虽然但是，方便通过语音+屏幕共享的方式可能可以更加方便的讨论下o(╥﹏╥)o

**Comment by zhiyiYo** [comment]
我看了一下他的代码觉的没有太大的不同，可能就多了个 `self.update()`
![image](https://user-images.githubusercontent.com/65096819/213707936-b6b404c2-5313-4aad-9aae-39e7ea9f5664.png)

**Comment by Shapaper** [comment]
这个不就只是更新计时器吗？

**Comment by zhiyiYo** [comment]
`update()` 可以用来刷新界面

**Comment by Shapaper** [comment]
难不成通过计时器[函数]的方式可以删掉一些数据来解决一些奇葩的bug？

**Comment by zhiyiYo** [comment]
可能是拖动的时候频繁调用  `setAcrylicEffect` 导致的问题，如果用定时器就不会有这个问题，因为他这里先把定时器停了从头开始
```python
def _temporary_disable_effect(self):
    self.set_effect(False)
    self.__effect_timer.stop()
    self.__effect_timer.start()
```

**Comment by zhiyiYo** [comment]
你可以录个屏展示一下他的代码拖动时是什么样子吗

**Comment by Shapaper** [comment]
我建议可以语音聊聊，或者等我录屏下

**Comment by zhiyiYo** [comment]
github 好一些，这样别人也能看到讨论过程和结果

**Comment by Shapaper** [comment]
我表述下他的程序把：他的程序在拖动时会丢失亚克力效果，无论你是否还按着鼠标，只要你超过设定的(100ms)的时间就会恢复亚克力，拖动速度慢的话可能会一直闪

**Comment by zhiyiYo** [comment]
嗯嗯，我也在自己电脑试过了，但是我不知道 win10 的那个灰色框框是什么情况，所以让你录个屏看看🤔

**Comment by Shapaper** [comment]
有什么好的录屏工具嘛

**Comment by Shapaper** [comment]
我这边的录屏会导致窗口变成没有显示画面的那种拖动窗口

**Comment by zhiyiYo** [comment]
我平时用 ScreenToGif
https://github.com/NickeManarin/ScreenToGif/releases/tag/2.37.1

**Comment by Shapaper** [comment]
我这边有台win10服务器，我可以给您远程桌面，您可以远程桌面来操控下打包好的exe程序

**Comment by zhiyiYo** [comment]
还是录屏吧，还能永久保存下来

**Comment by zhiyiYo** [comment]
> 哦，我这边网速好慢hh

换个好点的机场吧

**Comment by Shapaper** [comment]
机场?
是什么耕吗(

**Comment by Shapaper** [comment]
链接：https://pan.baidu.com/s/1BNpyykHnebD38iKKelp9Hg?pwd=0000 
提取码：0000

**Comment by zhiyiYo** [comment]
Win10 上面的半透明灰色框看起来好难受，修了等于没修

**Comment by Shapaper** [comment]
是的(o(╥﹏╥)o

**Comment by Shapaper** [comment]
还是先用那个人的吧，继续插眼。

**Comment by zhiyiYo** [comment]
摆烂了，还是不修了，建议换成 Win11😇

**Comment by Shapaper** [comment]
用户可不会因为一个软件升级win11啊qwq

**Comment by zhiyiYo** [comment]
可以给用户一个是否启用亚克力效果的选项，这样拖拽卡顿的后果就由用户自己来承担了
