### ISSUE TITLE
AcrylicWindow不显示标题？

### ISSUE THREAD

**Issue by Usercyk** [zhiyiYo/PyQt-Frameless-Window#43]
Win11，代码就是给的acrylic的demo代码
那个标题不显示？
<img width="310" alt="image" src="https://user-images.githubusercontent.com/109349977/214616082-4188a838-4dab-4cbf-ac5c-4732b92d937d.png">
标题和图标不显示，这是正常现象吗？

**Comment by zhiyiYo** [comment]
正常现象，默认标题栏不提供图标和标题，你可以像demo.py那样继承TitleBar然后用`setTitleBar`更换标题栏

**Comment by Usercyk** [comment]
谢谢
