### ISSUE TITLE
把titlebar里的三个按钮都设置成svgtitlebarbutton

### ISSUE THREAD

**Issue by Usercyk** [zhiyiYo/PyQt-Frameless-Window#44]
因为我觉得窗口的titlebar太细了，但是如果直接设置height就会使得最小化和最大化两个的paintEvent画的偏移了位置，也没有改变大小。
新手研究了半天发现只有closebutton是继承了svgtitlebarbutton, 这个就可以直接放大缩小。
希望能增加这个放大缩小的功能。或者能不能教一下怎么修改那个paintEvent，谢谢

**Comment by zhiyiYo** [comment]
如果觉得图标太细可以把 `pen = QPen(color, 1)` 修改为 `pen = QPen(color, 2)`，但是这样看起来就太粗了

**Comment by Usercyk** [comment]
不是图标太细，是整个titlebar的height太小

**Comment by Usercyk** [comment]
我看代码里面写的好像是32，我这里来看真的超级小

**Comment by zhiyiYo** [comment]
你有开启 dpi 缩放吗

**Comment by Usercyk** [comment]
？不太了解这是啥？
我这里现在是这样的
<img width="262" alt="image" src="https://user-images.githubusercontent.com/109349977/214767993-bc842f43-04d4-4e88-980d-eb243cdaa806.png">

**Comment by zhiyiYo** [comment]
在缩放比为 100% 时 32px 是很正常的，你可以像 demo.py 那样开启 dpi 缩放

**Comment by Usercyk** [comment]
哦我试试

**Comment by Usercyk** [comment]
可以了，谢谢大神
