### ISSUE TITLE
How do I make the window acrylic ?

### ISSUE THREAD

**Issue by CherphAlt** [zhiyiYo/PyQt-Frameless-Window#45]
I know this sounds dumb but there isn't a good enough documentation for the library

**Comment by zhiyiYo** [comment]
You can inherit the `AcrylicWindow` to make the window acrylic, see [examples/acrylic_demo.py](https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/acrylic_demo.py)
