### ISSUE TITLE
提供方法关闭右上角三个按钮的hover效果

### ISSUE THREAD

**Issue by HowieHz** [zhiyiYo/PyQt-Frameless-Window#46]
在收到您的回复后，我已经使用了PySideSix-Frameless-Window库，但是在使用的过程中我发现了一个问题，相较于我自己从pyqt5魔改上来的嵌在项目中的lib，右上角的按钮会高亮

这是我用自己魔改的库（魔改指从pyqt5迁移到pyside6应付使用，功能上没动），当光标放到黄色箭头的位置时无高亮
[分支链接](https://github.com/HowieHz/hpyculator/tree/dev)
![image](https://user-images.githubusercontent.com/94725606/215268905-78e96a2f-6015-4bf8-a697-10d0041d09ff.png)

而换用PySideSix-Frameless-Window库之后的效果
[分支链接](https://github.com/HowieHz/hpyculator/tree/1.X.X_testFatherLib)
![image](https://user-images.githubusercontent.com/94725606/215268789-ce39cf50-5275-43d9-8dee-48a5c5d6e261.png)
![image](https://user-images.githubusercontent.com/94725606/215268776-2f6dd2c3-fc7c-4087-a4ed-06b26bb8a7b7.png)

**希望作者这里能提供支持，如类方法，构造参数。以便调节此处问题**

**Comment by zhiyiYo** [comment]
这个应该是默认标题栏导致的，你可以 `self.titleBar.hide()` 把标题栏隐藏了

**Comment by HowieHz** [comment]
> 



> 这个应该是默认标题栏导致的，你可以 `self.titleBar.hide()` 把标题栏隐藏了

好的，感谢作者光速回复，我刚才发完issue之后想到可以自己隐藏
