### ISSUE TITLE
请问后期考虑使用 QtPy 包去合并不同版本的 PyQt 或者PySide 吗？

### ISSUE THREAD

**Issue by Mr-ZBin** [zhiyiYo/PyQt-Frameless-Window#47]
因为我看到在 .../site-packages/ 中，**PyQt5-Frameless-Window** 和 **PyQt6-Frameless-Window** 都是用了 **qframelesswindow** 文件夹来存放这个包，如果同时安装这两个版本，则最后安装的会把之前的**覆盖**掉。

**Comment by zhiyiYo** [comment]
两个branch在Linux系统上的实现方式不太一样，不好用 qtpy 来统一代码

**Comment by zhiyiYo** [comment]
而且一个项目应该只会用一种 PyQt 吧，有虚拟环境也不用担心命名空间冲突的问题

**Comment by Mr-ZBin** [comment]
谢谢博主👍
