### ISSUE TITLE
MainWindow无法使用windowEffect

### ISSUE THREAD

**Issue by Usercyk** [zhiyiYo/PyQt-Frameless-Window#49]
win11 python3.10.5
就是我试图去将我的FramelessWindow转为QMainWindow，然后发现不能使用AcrylicEffect和MicaEffect了
<img width="955" alt="image" src="https://user-images.githubusercontent.com/109349977/216627607-4d29ec74-5681-4396-8317-d53b8eb9357f.png">
这两种写法都不行，是不是**必须**得改qframelesswindow里的源码的继承关系，把继承从QtWidget改为QMainWindow啊？（我个人觉得如果没有必要，就不要改第三方库的代码）

**Comment by zhiyiYo** [comment]
`Window2` 的构造函数里面加上透明样式：
```python
self.setStyleSheet("Window2{background:transparent}")
```
