### ISSUE TITLE
在有多个屏幕的情况下，窗口的控件元素出现重复，resize后现象消失

### ISSUE THREAD

**Issue by wolaic** [zhiyiYo/PyQt-Frameless-Window#5]
您好: 
       首先非常感谢您的开源，解决了我调用windows api 的问题。这两天我在使用过程中发现了一个问题。就是当你把你的界面拖拽到第二个扩展屏幕上的，界面上元素会出现重复。resize后，界面恢复正常，似乎他无法在两个分辨率中进行调整，只有当你调用了他的resizeEvent后，进行强制刷新界面才行。我有尝试过QApplication.processEvents(),self.update()等方法。都不行。
![bug](https://user-images.githubusercontent.com/46783632/144773540-4f8fda7f-e37d-44ca-8b37-c0fc46d621ed.png)
![normal](https://user-images.githubusercontent.com/46783632/144773544-65cc910e-e238-4a95-9d9c-e953a6584343.png)

**Comment by zhiyiYo** [comment]
感谢支持，我这边没有测试多屏的条件，只能靠各位自己解决了，如果顺利解决了欢迎 PR！

**Comment by wolaic** [comment]
好的，我刚刚又尝试了一下，发现这个有可能是两个屏幕的方法比率不对造成的。在win10的条件的，不同的屏幕有不同推荐的放大比率。都在推荐的放大比率下就不会出现这个问题。我再研究研究。

**Comment by hcaihao** [comment]
这个多屏不同dpi下的问题很多无边框库都有,不解决的画很难项目用.

**Comment by wolaic** [comment]
> 这个多屏不同dpi下的问题很多无边框库都有,不解决的画很难项目用.

我看您的开源项目里里面也有利用C++写的自定义无边框框架，在您的介绍里貌似是解决了这个问题。

**Comment by zhiyiYo** [comment]
> > 这个多屏不同dpi下的问题很多无边框库都有,不解决的画很难项目用.
> 
> 我看您的开源项目里里面也有利用C++写的自定义无边框框架，在您的介绍里貌似是解决了这个问题。

看了一下他的代码和我的很像，我找个时间去研究一下

**Comment by wolaic** [comment]
> > > 这个多屏不同dpi下的问题很多无边框库都有,不解决的画很难项目用.
> > 
> > 
> > 我看您的开源项目里里面也有利用C++写的自定义无边框框架，在您的介绍里貌似是解决了这个问题。
> 
> 看了一下他的代码和我的很像，我找个时间去研究一下
我貌似找到了对多屏幕的适配的关键句
![image](https://user-images.githubusercontent.com/46783632/147996044-0c88a94d-d83d-4eb9-b184-dfbc9abd6336.png)
但是在pyqt中没有找到对应的映射。
![image](https://user-images.githubusercontent.com/46783632/147996110-27230ea7-e149-4d5e-9d24-f04fd511bc43.png)

**Comment by zhiyiYo** [comment]
这个用 pywin32 应该可以解决，我去敲下代码

**Comment by zhiyiYo** [comment]
@wolaic  我更新了代码，可以帮忙测试一下吗？

**Comment by wolaic** [comment]
> 

好的，我现在拉取一下

**Comment by wolaic** [comment]
@zhiyiYo 这个方法是有效的，确实解决了多屏下不同dpi的问题。

**Comment by zhiyiYo** [comment]
感谢😆
