### ISSUE TITLE
No size-grips on FramelessMainWindow after closing FramelessDialog

### ISSUE THREAD

**Issue by gilex-dev** [zhiyiYo/PyQt-Frameless-Window#50]
**Describe the bug**
The size-grips (the little arrows that let you resize a window) disappear on FramelessMainWindow after creating and closing a FramelessDialog.

**Environment**
 - OS: Windows10
 - DPI scaling: e.g. 175%
 - Python: 3.10.6 64 bit
 - PyQt5: 5.15.6

**To Reproduce**
1. Run [main_window.py](https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/examples/main_window.py) and open the help dialog
2. Close the dialog and try to resize the main window (only the size-grip in the bottom right corner will work)

**Expected behavior**
The main window keeps its size-grips on all four sides.

**More info**
Calling [`self.winID()`](https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/master/qframelesswindow/windows/__init__.py#L39) on the initialization of the FramelessDialog seems to remove the size-grips from the main window.
This problem only occurs when you call `self.setCentralWidget` or `self.setLayout` on the main window.

**Comment by zhiyiYo** [comment]
Thank you for reporting this bug. We should add this line to code:
```python
app.setAttribute(Qt.AA_DontCreateNativeWidgetSiblings)
```
