### ISSUE TITLE
如何把无边框窗口应用到designer设计的UI中

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Frameless-Window#51]
想用大佬做的无边框窗口替换掉designer生成的原窗口该怎么写呢？

我感觉是我用法有问题...

[test.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/10675834/test.zip)

**Comment by zhiyiYo** [comment]
你应该给标题栏留出一点空间
![image](https://user-images.githubusercontent.com/65096819/217274105-ecace95b-e2ae-4b7e-916c-b964605b8719.png)


[Ui_Link.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/10676106/Ui_Link.zip)

**Comment by Ephemeralwanning** [comment]
> 你应该给标题栏留出一点空间 ![image](https://user-images.githubusercontent.com/65096819/217274105-ecace95b-e2ae-4b7e-916c-b964605b8719.png)
> 
> [Ui_Link.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/10676106/Ui_Link.zip)

感谢大大 成功了
