### ISSUE TITLE
Full screen and maximized improvement

### ISSUE THREAD

**Issue by AntoineMiras** [zhiyiYo/PyQt-Frameless-Window#52]
Hi, I noticed that when the window is maximized or in full screen (f11 behavior), the close button is not accessible when the mouse cursor is in the upper right corner of the screen.

I have made some changes to your code to suit my needs:

On line 118 of the init.py file in the windows folder

```
            self.BORDER_WIDTH = 5 
            if isMax or isFull: 
                self.BORDER_WIDTH = -win_utils.getResizeBorderThickness(msg.hWnd) - self.BORDER_WIDTH 
```

Also, I saw that the title bar is always dragging in full screen, the following changes in the canDrag function of the titleBar module work well for me:

```
def canDrag(self, pos):
        """ whether the position is draggable """
        if not self.window().isFullScreen():
            return self._isDragRegion(pos) and not self._hasButtonPressed()
        return False
```
I hope this will be useful to you, have a nice day! 🙂

**Comment by zhiyiYo** [comment]
Thank you for your advice. I think the title bar should be hidden in full screen, so I don't plan to modify this part of code🙂
