### ISSUE TITLE
Mica Title bar on Latest windows update

### ISSUE THREAD

**Issue by Cowski0** [zhiyiYo/PyQt-Frameless-Window#53]
When i test my app on the latest windows update, a title bar shows up, i was wondering if there was a way to make this transparent, as it ruins some past apps, thanks.
![Screenshot_20230209_091241](https://user-images.githubusercontent.com/97522577/217783736-e476f888-7a76-41a5-855c-13904cbc13d6.png)  

```python
import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication
from qframelesswindow import AcrylicWindow


class Window(AcrylicWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setWindowTitle("Acrylic Window")
        self.titleBar.raise_()
        self.windowEffect.setMicaEffect(self.winId(), True)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())

**Comment by zhiyiYo** [comment]
Please provide your system version

**Comment by Cowski0** [comment]
22H2 2261.1105

**Comment by zhiyiYo** [comment]
My Windows11 version is 22H2 22623.1250 and does not have this problem.

**Comment by Cowski0** [comment]
show accent colour was the cause of the issue, thanks
