### ISSUE TITLE
大佬，有C++版的QT 无边框吗

### ISSUE THREAD

**Issue by yuanqi-pythoner** [zhiyiYo/PyQt-Frameless-Window#54]
大佬，有C++版的QT 无边框窗口吗，我测试了下，效果很好。但是经常用 C++ QT ，请问您这个有没有C++ 版本的

**Comment by zhiyiYo** [comment]
你可以看下这个 https://github.com/wangwenx190/framelesshelper

**Comment by zhiyiYo** [comment]
只要按 readme 里面来编译就行了
