### ISSUE TITLE
更新代码后 hWnd 少加了一个类型转换

### ISSUE THREAD

**Issue by Virace** [zhiyiYo/PyQt-Frameless-Window#6]
https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/0c4b9f227739703ab3051723787414ef2802cc28/windoweffect/window_effect.py#L83

还有个问题，对于开启亚克力效果的窗口，在 “拖动时显示窗口内容” 这一系统效果打开后，边缘缩放窗口会导致 会有 不跟手的状态，这是什么引起的呢？

**Comment by zhiyiYo** [comment]
第一个问题：不加类型转换也能跑
第二个问题：应该是 Windows 自己的问题，之前没注意到 😅

**Comment by Virace** [comment]
`windoweffect\window_effect.py", line 84, in setAcrylicEffect
    self.SetWindowCompositionAttribute(hWnd, pointer(self.winCompAttrData))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type`

没转换我是遇到这个问题，python 3.10

**Comment by Virace** [comment]
> 第一个问题：不加类型转换也能跑 第二个问题：应该是 Windows 自己的问题，之前没注意到 😅

windoweffect\window_effect.py", line 84, in setAcrylicEffect
    self.SetWindowCompositionAttribute(hWnd, pointer(self.winCompAttrData))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

没加的话会遇到类型错， Python 3.10

**Comment by zhiyiYo** [comment]
我是 Python 3.8.6，那我加上类型转换好了，感谢反馈（￣︶￣）↗

**Comment by Virace** [comment]
嗯，感谢分享
