### ISSUE TITLE
大佬，询问下您是怎么实现最小化和显示动画的

### ISSUE THREAD

**Issue by diaoyujiuyongzhezhao** [zhiyiYo/PyQt-Frameless-Window#61]
如题，抱歉打扰了

**Comment by xianyongjian080402** [comment]
盲猜一波计时器循环

**Comment by xianyongjian080402** [comment]
> 盲猜一波计时器循环

如果不用qt自带的，自己写得话

qt自带的简单，不用咱写代码，他自己就加上了

**Comment by diaoyujiuyongzhezhao** [comment]
是那个windows自带的动画，就是我们点击最小化，有个动画效果往任务栏图标方向的动画

**Comment by zhiyiYo** [comment]
你可以看下我之前的博客
https://www.cnblogs.com/zhiyiYo/p/14644180.html

**Comment by diaoyujiuyongzhezhao** [comment]
我看完了，好像是这个函数，因为我这边是用C++,所以测试没有才来找大佬
    def setWindowAnimation(self, hWnd):
        """ 打开窗口动画效果 """
        style = win32gui.GetWindowLong(hWnd, win32con.GWL_STYLE)
        win32gui.SetWindowLong(
            hWnd, win32con.GWL_STYLE, style | win32con.WS_MAXIMIZEBOX
                                            | win32con.WS_CAPTION
                                            | win32con.CS_DBLCLKS
                                            | win32con.WS_THICKFRAME)

**Comment by diaoyujiuyongzhezhao** [comment]
我这C++那边这么修改，还是没动画，奇了怪了

**Comment by zhiyiYo** [comment]
你电脑上的其他应用会有动画效果吗，如果没有的话可能是你没开启最大化最小化动画，你可以去 高级系统设置--＞性能 里面开启

**Comment by diaoyujiuyongzhezhao** [comment]
有的，其他应用会有动画效果

**Comment by diaoyujiuyongzhezhao** [comment]
// 打开窗口动画效果
    LONG style = GetWindowLong(reinterpret_cast<HWND>(winId()), GWL_STYLE);
    SetWindowLong(reinterpret_cast<HWND>(winId()), GWL_STYLE, style | WS_MINIMIZEBOX | WS_MAXIMIZEBOX | WS_CAPTION | CS_DBLCLKS | WS_THICKFRAME);
    这是我C++代码

**Comment by zhiyiYo** [comment]
https://github.com/hcaihao/StyleWindow
这个仓库用c++重写了我的代码，你可以看下

**Comment by diaoyujiuyongzhezhao** [comment]
好的，非常感谢
