### ISSUE TITLE
当使用FramelessDialog并且继承父窗口时点击关闭对话框窗口后父窗口整个页面的鼠标cursor样式都变成了Qt.Pointinghandcursor

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Frameless-Window#62]
**Describe the bug**
关闭无边框对话框窗口后父窗口的鼠标cursor样式都变成了Qt.Pointinghandcursor

**Environment**
 - OS: MAC
 - Python: 3.9.6
 - PyQt5: 5.15.2

**To Reproduce**
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. 在父窗口的按钮点击事件打开一个无边框对话框窗口
2. 点击无边框对话框窗口的关闭按钮
3. 父窗口的鼠标样式异常
4. 如父窗口点击按钮弹出的对话框没有设置父窗口则正常

![image](https://user-images.githubusercontent.com/8281775/224866778-0d71d01f-7f99-4e48-8d29-455d97a14f32.png)
例如上图，点击按钮弹出注册对话框，如果RegisterWindow()里没有self就没有这个问题

通过咨询chatGPT，目前临时通过在无边框对话框窗口代码重写show和closeEvent方法获取和设置父窗口的cursor样式解决了这个问题，大佬看看有没有其他更好的方法解决。
![image](https://user-images.githubusercontent.com/8281775/224867130-d2c7d695-ff15-429a-baa3-b476570291ae.png)

![image](https://user-images.githubusercontent.com/8281775/224867042-eb8f352e-be6c-4fd1-a06a-ecc3e3b4f5a7.png)

**Comment by zhiyiYo** [comment]
看看是不是这个问题：
https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/50

**Comment by qianye216** [comment]
> 看是不是这个问题#50

谢谢大佬，添加了app.setAttribute(Qt.AA_DontCreateNativeWidgetSiblings)后就正常了，估计是同一个原因导致，能否不用额外添加这个代码也能修复这个问题呢

**Comment by qianye216** [comment]
> > 看是不是这个问题#50
> 
> 谢谢大佬，添加了app.setAttribute(Qt.AA_DontCreateNativeWidgetSiblings)后就正常了，估计是同一个原因导致的，能不能不用额外添加这个代码也可以解决这个问题呢

**Comment by qianye216** [comment]
> #50

好的，谢谢解答
