### ISSUE TITLE
Menu菜单栏没办法点击了

### ISSUE THREAD

**Issue by forzenheart** [zhiyiYo/PyQt-Frameless-Window#65]
![image](https://user-images.githubusercontent.com/12236093/227788343-b4f476a2-a11f-4ca4-90c8-e391a3dc6cef.png)

**Comment by zhiyiYo** [comment]
可以提供一下环境信息以及复现问题的最小代码吗

**Comment by zhiyiYo** [comment]
由于这个issue不再活跃，我将暂时关闭它。
