### ISSUE TITLE
Add support for window effects on KDE and Gnome.

### ISSUE THREAD

**Issue by HRudyPlayZ** [zhiyiYo/PyQt-Frameless-Window#66]
**Describe the solution you'd like**
Add support for those two (and possibly more) desktop environments for Linux. So, as to be able to make better cross-platform apps.

**Describe alternatives you've considered**
There's probably other APIs existing especially for KDE, but i feel this library would benefit from it.

**Comment by zhiyiYo** [comment]
There are too many Linux desktop environments, and it is not realistic to write a `WindowEffect` for each desktop environment.

**Comment by zhiyiYo** [comment]
My virtual machine uses GNOME and it  works well even though WindowEffect is not implemented. But KDE hasn't been tested.
