### ISSUE TITLE
关于DPI缩放

### ISSUE THREAD

**Issue by tonquer** [zhiyiYo/PyQt-Frameless-Window#7]
启用DPI缩放后
```
    QGuiApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QCoreApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())

```
系统Win10, 系统缩放125%
![动画](https://user-images.githubusercontent.com/22116659/149860087-2e4ebf8e-d429-4d86-b1f0-07ebbe0e5910.gif)

似乎这个地方乘以缩放因子就ok了？
![image](https://user-images.githubusercontent.com/22116659/149860363-a6cc9326-589f-4fff-8164-69ee567a783d.png)

**Comment by zhiyiYo** [comment]
模除了 65536 还是没有解决问题吗？

**Comment by zhiyiYo** [comment]
感谢建议，之前没试过 DPI 缩放，我现在改下代码
