### ISSUE TITLE
PySide6版本的标题信息无法设置

### ISSUE THREAD

**Issue by TaoChenyue** [zhiyiYo/PyQt-Frameless-Window#71]
**Describe the bug**

**Environment**
 - OS: [e.g. Windows11]
 - DPI scaling: [e.g. 100%]
 - Python: [e.g. 3.8.16 64-bit]
 - PySide6: [e.g. 5.15.2]

**To Reproduce**

**Code**
```python
# Minimum code to reproduce the error
from PySide6.QtWidgets import QApplication
from qframelesswindow import FramelessWindow
class Window(FramelessWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
if __name__=="__main__":
    app=QApplication()
    window=Window()
    window.setWindowTitle("yes")
    window.show()
    app.exec()
```

**Expected behavior**
把WindowsFramelessWindow的TitleBar改成StandardTitleBar即可。
![1680490892722](https://user-images.githubusercontent.com/40346985/229401899-369c8b5b-1037-4727-bd5c-4a015e2aa857.png)

**Screenshots**
![1680490399453](https://user-images.githubusercontent.com/40346985/229400878-3328d692-692e-4023-9454-1b2fce0e614e.png)

**Comment by zhiyiYo** [comment]
可以调用 `FramelessWindow.setTitleBar()` 来更换默认标题栏
