### ISSUE TITLE
使用 Pythonocc 时，窗口行为怪异

### ISSUE THREAD

**Issue by ovo-Tim** [zhiyiYo/PyQt-Frameless-Window#72]
**Describe the bug**
使用 Pythonocc 时，窗口行为怪异，TitleBar消失。拖动改变窗口大小时，时有失灵

**Environment**
 - OS: 
 ``` bash
 ❯ neofetch
       _,met$$$$$gg.          tim@tim 
    ,g$$$$$$$$$$$$$$$P.       ------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Host: 81BV Lenovo ideapad 720S-13IKB 
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-21-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 16 hours, 58 mins 
 $$P      d$'     ,    $$P    Packages: 3331 (dpkg), 13 (flatpak), 2 (snap) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: Plasma 5.20.5 
 `$$b      "-.__              WM: KWin 
  `Y$$                        Theme: NephriteLight [Plasma], Breeze [GTK2/3] 
   `Y$$.                      Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
     `$$b.                    Terminal: konsole 
       `Y$$b.                 Terminal Font: Hack [SRC] 10 
          `"Y$b._             CPU: Intel i5-8250U (8) @ 3.400GHz 
              `"""            GPU: Intel UHD Graphics 620 
                              Memory: 5501MiB / 7706MiB 
```
 - DPI scaling:  100%
 - Python: conda Python 3.10.8
 - PySide2:5.15.8

**Code**
```python
import sys

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from qframelesswindow import *

from OCC.Display.backend import load_backend, get_loaded_backend
load_backend("qt-pyside2")
import OCC.Display.qtDisplay as qtDisplay


class Window(FramelessWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)

        self.main_layout = QGridLayout(self)

        # 加载OCC
        self.canvas = qtDisplay.qtViewer3d(self)
        self.canvas.InitDriver()
        self.main_layout.addWidget(self.canvas)
        self.display = self.canvas._display

        self.setLayout(self.main_layout)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    sys.exit(app.exec_())

```

**Expected behavior**
正常的窗口

**Screenshots**
只有视频才能体现BUG [视频](https://www.123pan.com/s/qdY9-5tfk3.html)
如视频所见，调整窗口大小似乎是随机可用的

**Comment by zhiyiYo** [comment]
你得给标题栏留出空间
`self.main_layout.setContentMargins(0, self.titleBar.heoght(), 0, 0)`

**Comment by ovo-Tim** [comment]
标题栏显示确实正常了，但是调整窗口大小以及拖动窗口依然有BUG,建议您亲自测试一下

**Comment by zhiyiYo** [comment]
在 Linux 上拖动窗口调用的是 Qt 提供的 api，我也无能为力了

**Comment by ovo-Tim** [comment]
但是原生窗口似乎没有问题，很奇怪。
即使我把这个 canva 放到 QTabWidget 当中也会有这些BUG

**Comment by zhiyiYo** [comment]
原生窗口的移动是系统负责的，qt 只负责绘制窗口内部区域，但是无边框窗口使用了 qt 提供的 `QWindow.startSystemMoveResize` 函数移动窗口，所以行为可能和原生窗口不一样

**Comment by zhiyiYo** [comment]
有测试过 PyQt5 吗

**Comment by ovo-Tim** [comment]
> 有测试过 PyQt5 吗

没有，我空了试试看，我还是比较喜欢pyside
另外，wayland是误报，bug仍然出现
我怀疑和kwin有关系

**Comment by ovo-Tim** [comment]
> Windows 不是用这个 api 实现的

我知道，我单独在 windows 测试过`QWindow.startSystemMoveResize`，是没问题的

**Comment by zhiyiYo** [comment]
话说你用的桌面环境是啥，KDE 吗

**Comment by ovo-Tim** [comment]
> 话说你用的桌面环境是啥，KDE 吗

对，所以才会怀疑 kwin

**Comment by ovo-Tim** [comment]
> kde 无边框窗口是不是没有窗口阴影呀

应该是

**Comment by zhiyiYo** [comment]
> > kde 无边框窗口是不是没有窗口阴影呀
> 
> 应该是

如果给无边框窗口加上这一行代码可以实现窗口阴影吗：
```python
c = "xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id " + str(int(self.winId())
os.system(c)

```

**Comment by ovo-Tim** [comment]
> > > kde 无边框窗口是不是没有窗口阴影呀
> > 
> > 应该是
> 
> 如果给无边框窗口加上这一行代码可以实现窗口阴影吗：
> ```python
> c = "xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id " + str(int(self.winId())
> os.system(c)
> 
> ```
我可能要过几天来测试了
不过这样的话就没法跨平台了
我对阴影没有要求，不过这个bug和阴影有关吗？

**Comment by ovo-Tim** [comment]
> 我研究过 occ 的源码，它 [这个位置](https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/qtDisplay.py#L104-L104)，似乎创建了一个子窗口然后嵌入进去(pythonocc只是occ的python封装，再往里走就是C++了)

再往里走还能找到[这里](https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/OCCViewer.py#L214-L214)

**Comment by zhiyiYo** [comment]
应该和阴影没啥关系，不过没阴影窗口看起来很奇怪，如果有用的话到时候可以把这行代码加在 WindowEffect 类里面

**Comment by ovo-Tim** [comment]
我在想能不能用类似于 `xprop` 的工具来实现这个功能。我搜了一下，似乎没有方法

**Comment by zhiyiYo** [comment]
```
c = "xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id " + str(int(self.winId())
os.system(c)
```
不管用吗
