### ISSUE TITLE
win7系统下窗口最大化时软件闪退

### ISSUE THREAD

**Issue by zjhsb** [zhiyiYo/PyQt-Frameless-Window#76]
win7系统下窗口最大化时软件闪退，而win10系统下没问题。具体故障代码如下
  
Process finished with exit code 1073741845

尝试注释qframlesswindow/utils/win32_utils.py文件中的下面部分代码后解决闪退问题。

windows = QGuiApplication.topLevelWindows()
for window in windows:
 if window and int(window.winId()) == hWnd:
             return window

**Environment**
- OS: [e.g. Windows7]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.8.10 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.2.1]

**Comment by zhiyiYo** [comment]
感谢反馈，没有其他的报错信息吗

**Comment by zjhsb** [comment]
![image](https://user-images.githubusercontent.com/94160900/231644252-d4ebf4e5-3ed3-4484-9eaf-4c3c1ab7e892.png)

**Comment by zhiyiYo** [comment]
@zjhsb 
`qframelesswindow/utils/win32_utils.py` 的 `getResizeBorderThickness` 改成下述代码可以运行吗
```python
def getResizeBorderThickness(hWnd, horizontal=True):
    """ get resize border thickness of widget

    Parameters
    ----------
    hWnd: int or `sip.voidptr`
        window handle

    dpiScale: bool
        whether to use dpi scale
    """
    window = findWindow(hWnd)
    if not window:
        return 0

    user32 = windll.user32

    frame = win32con.SM_CXSIZEFRAME if horizontal else win32con.SM_CYSIZEFRAME
    dpi = getDpiForWindow(hWnd, horizontal)
    result = user32.GetSystemMetricsForDpi(frame, dpi) + user32.GetSystemMetricsForDpi(92, dpi)

    if result > 0:
        return result

    thickness = 8 if QtWin.isCompositionEnabled() else 4
    return round(thickness*window.devicePixelRatio())


def getDpiForWindow(hWnd, horizontal=True):
    """ get dpi for window

    Parameters
    ----------
    hWnd: int or `sip.voidptr`
        window handle

    dpiScale: bool
        whether to use dpi scale
    """
    if hasattr(windll.user32, 'GetDpiForWindow'):
        return windll.user32.GetDpiForWindow(hWnd)

    hdc = win32gui.GetDC(hWnd)
    if hdc:
        return 96

    dpiX = win32print.GetDeviceCaps(hdc, win32con.LOGPIXELSX)
    dpiY = win32print.GetDeviceCaps(hdc, win32con.LOGPIXELSY)
    win32gui.ReleaseDC(hWnd, hdc)
    if dpiX > 0 and horizontal:
        return dpiX
    elif dpiY > 0 and not horizontal:
        return dpiY

    return 96
```

**Comment by zjhsb** [comment]
提示NameError: name 'win32print' is not defined

**Comment by zhiyiYo** [comment]
`import win2print` 一下

**Comment by zjhsb** [comment]
加了之后AttributeError: function 'GetSystemMetricsForDpi' not found   好像这个函数也不能用

**Comment by zhiyiYo** [comment]
改成这样呢：
```python
def getResizeBorderThickness(hWnd, horizontal=True):
    """ get resize border thickness of widget

    Parameters
    ----------
    hWnd: int or `sip.voidptr`
        window handle

    dpiScale: bool
        whether to use dpi scale
    """
    if not isGreaterEqualWin10():
        return 0
    
    window = findWindow(hWnd)
    if not window:
        return 0

    frame = win32con.SM_CXSIZEFRAME if horizontal else win32con.SM_CYSIZEFRAME
    result = getSystemMetrics(hWnd, frame, horizontal) + getSystemMetrics(hWnd, 92, horizontal)

    if result > 0:
        return result

    thickness = 8 if QtWin.isCompositionEnabled() else 4
    return round(thickness*window.devicePixelRatio())


def getSystemMetrics(hWnd, index, horizontal):
    """ get system metrics """
    if not hasattr(windll.user32, 'GetSystemMetricsForDpi'):
        return win32api.GetSystemMetrics(index)

    dpi = getDpiForWindow(hWnd, horizontal)
    return windll.user32.GetSystemMetricsForDpi(index, dpi)


def getDpiForWindow(hWnd, horizontal=True):
    """ get dpi for window

    Parameters
    ----------
    hWnd: int or `sip.voidptr`
        window handle

    dpiScale: bool
        whether to use dpi scale
    """
    if hasattr(windll.user32, 'GetDpiForWindow'):
        return windll.user32.GetDpiForWindow(hWnd)

    hdc = win32gui.GetDC(hWnd)
    if not hdc:
        return 96

    dpiX = win32print.GetDeviceCaps(hdc, win32con.LOGPIXELSX)
    dpiY = win32print.GetDeviceCaps(hdc, win32con.LOGPIXELSY)
    win32gui.ReleaseDC(hWnd, hdc)
    if dpiX > 0 and horizontal:
        return dpiX
    elif dpiY > 0 and not horizontal:
        return dpiY

    return 96

```

**Comment by zhiyiYo** [comment]
如果把下面两行注释掉不知道会怎样
```python
if not isGreaterEqualWin10():
        return 0
```

**Comment by zjhsb** [comment]
牛的，没问题了

**Comment by zhiyiYo** [comment]
最大化后长啥样

**Comment by zhiyiYo** [comment]
能否截下图

**Comment by zjhsb** [comment]
def getResizeBorderThickness(hWnd, horizontal=True):
    """ get resize border thickness of widget

    Parameters
    ----------
    hWnd: int or `sip.voidptr`
        window handle

    dpiScale: bool
        whether to use dpi scale
    """
    if not isGreaterEqualWin10():
        return 0

    window = findWindow(hWnd)
    if not window:
        return 0

    frame = win32con.SM_CXSIZEFRAME if horizontal else win32con.SM_CYSIZEFRAME
    result = getSystemMetrics(hWnd, frame, horizontal) + getSystemMetrics(hWnd, 92, horizontal)

    if result > 0:
        return result

    thickness = 8 if QtWin.isCompositionEnabled() else 4
    return round(thickness * window.devicePixelRatio())


def getSystemMetrics(hWnd, index, horizontal):
    """ get system metrics """
    if not hasattr(windll.user32, 'GetSystemMetricsForDpi'):
        return win32api.GetSystemMetrics(index)

    dpi = getDpiForWindow(hWnd, horizontal)
    return windll.user32.GetSystemMetricsForDpi(index, dpi)


def getDpiForWindow(hWnd, horizontal=True):
    """ get dpi for window

    Parameters
    ----------
    hWnd: int or `sip.voidptr`
        window handle

    dpiScale: bool
        whether to use dpi scale
    """
    if hasattr(windll.user32, 'GetDpiForWindow'):
        return windll.user32.GetDpiForWindow(hWnd)

    hdc = win32gui.GetDC(hWnd)
    if not hdc:
        return 96

    dpiX = win32print.GetDeviceCaps(hdc, win32con.LOGPIXELSX)
    dpiY = win32print.GetDeviceCaps(hdc, win32con.LOGPIXELSY)
    win32gui.ReleaseDC(hWnd, hdc)
    if dpiX > 0 and horizontal:
        return dpiX
    elif dpiY > 0 and not horizontal:
        return dpiY

    return 96
就改成这样

**Comment by zjhsb** [comment]
![image](https://user-images.githubusercontent.com/94160900/232400937-531ec6a3-6b94-42e8-b1cc-5d6c7c4ffae0.png)

**Comment by zhiyiYo** [comment]
奇怪，窗口最大化后还是超出了显示屏

**Comment by zhiyiYo** [comment]
确定只改了这个地方吗，`nativeEvent` 有动过吗

**Comment by zjhsb** [comment]
没有，因为这是一个新创建的工程，重新下载的库文件

**Comment by zhiyiYo** [comment]
如果把 `nativeEvent` 注释掉后再最大化会超出显示屏吗

**Comment by zhiyiYo** [comment]
或者只注释 `getResizeBorderThickness()` 的前两行而不注释 `nativeEvent`
```python
if not isGreaterEqualWin10():
        return 0
```

**Comment by zjhsb** [comment]
![image](https://user-images.githubusercontent.com/94160900/232406978-9e17aa77-f6e2-4bc2-99dd-5057c3695571.png)

**Comment by zjhsb** [comment]
nativeEvent 注释掉后没有无边框的效果了，上面的图是只注释 getResizeBorderThickness() 的前两行

**Comment by zhiyiYo** [comment]
应该是强两行直接返回 0 导致的结果

**Comment by zhiyiYo** [comment]
现在看来最大化应该是没啥问题了，但是很好奇 Win7 上会有窗口阴影吗
![image](https://user-images.githubusercontent.com/65096819/232407624-f573e8d3-0930-4e5f-9185-e499b9da1f34.png)

**Comment by zjhsb** [comment]
可以描述下窗口阴影是什么效果吗

**Comment by zhiyiYo** [comment]
窗口旁边这一圈就是阴影
![image](https://user-images.githubusercontent.com/65096819/232408164-4df0b289-2c89-4593-aa05-09787dac6b1c.png)

**Comment by zjhsb** [comment]
![image](https://user-images.githubusercontent.com/94160900/232411882-8a268d36-33eb-4d4e-9df0-70a644fd1885.png)
这种xiao效果吗

**Comment by zhiyiYo** [comment]
是旁边这一圈阴影
![image](https://user-images.githubusercontent.com/65096819/232413959-1932b1fe-2109-4f0b-990b-ba3d9f3bf9ab.png)

**Comment by zhiyiYo** [comment]
行吧，最新版本的 pyqt-frameless-window 已经修复了最大化问题，可以更新一下试试

**Comment by zjhsb** [comment]
ok，牛的
