### ISSUE TITLE
窗口效果改进建议

### ISSUE THREAD

**Issue by TaoChenyue** [zhiyiYo/PyQt-Frameless-Window#77]
调用Windows底层的亚克力效果会导致窗口变卡。要不要用fluentwidgets里面的AcrylicLabel实现方法来代替。
我看watt toolkit就有很多种窗口效果，而且还不卡。
![image](https://user-images.githubusercontent.com/40346985/231778887-2d290d61-3f1b-4c37-86dd-c02d2329dc27.png)

**Comment by zhiyiYo** [comment]
watt toolkit 用的就是 WinUI 提供的 AcrylicBrush 来绘制的背景，而 PyQt-Frameless-Window 用的是系统 API，比不了呀

**Comment by zhiyiYo** [comment]
用 AcrylicLabel 也做不到这种效果，因为检测不到窗口下方的背景是否发生变化

**Comment by TaoChenyue** [comment]
也许可以pillow截图

**Comment by zhiyiYo** [comment]
截图也截不到窗口下方的样子

**Comment by TaoChenyue** [comment]
如果不考虑桌面图标的话，可以获取当前桌面壁纸来截。

**Comment by TaoChenyue** [comment]
隐藏窗口然后截图不知道性能怎么样

**Comment by TaoChenyue** [comment]
算了，略卡😂
