### ISSUE TITLE
Demo全屏之后界面右侧和下侧会超出屏幕边界

### ISSUE THREAD

**Issue by Cijade** [zhiyiYo/PyQt-Frameless-Window#79]
**Describe the bug**
After full screen, the right and bottom sides extend beyond the boundaries of the screen
Demo全屏之后界面右侧和下侧会超出屏幕边界

**Environment**
 - OS: [e.g. Windows11]
 - DPI scaling: [e.g. 100%]
 - Python: [e.g. 3.9.16 64-bit]
 - Pyside6

**Comment by zhiyiYo** [comment]
用的是 pyside6.5.0 吗

**Comment by Cijade** [comment]
![image](https://user-images.githubusercontent.com/26559370/232417056-4497d1db-6c63-406c-9154-3fc618f86b94.png)

**Comment by Cijade** [comment]
对是6.5.0

**Comment by zhiyiYo** [comment]
6.5.0 确实会有此问题，建议换成 6.4.2

**Comment by zhiyiYo** [comment]
直接运行 gallery.exe 窗口最大化后应该也不会超出显示器
