### ISSUE TITLE
关于qmediawidget播放视频无法拉伸窗口的问题

### ISSUE THREAD

**Issue by qinyao86** [zhiyiYo/PyQt-Frameless-Window#8]
你好，你的代码让我受益匪浅，最近尝试练习制作一个媒体播放器，发现一旦使用了qt里的setVideoOutput方法，让一个widget作为视频显示的界面之后，鼠标移动到窗口边缘就不再出现箭头了，原因好像是无法获取到windows发出的消息，但其他效果均无影响。实在不懂win32这块，希望能帮忙解决一下，小白在此跪谢！

**Comment by zhiyiYo** [comment]
你可以换成QGraphicsVideoItem

**Comment by qinyao86** [comment]
真的可以了，而且使用了QGraphicsVideoItem,悬浮在视频上的控件也可以设置qss圆角等效果了，膜拜！谢谢！

**Comment by zhiyiYo** [comment]
有些时候视频可能会显示异常，可以考虑使用下面的这个类
```python
class GraphicsVideoItem(QGraphicsVideoItem):
    """ 视频图元 """

    def paint(self, painter: QPainter, option, widget):
        painter.setCompositionMode(QPainter.CompositionMode_Difference)
        super().paint(painter, option, widget)
```

**Comment by qinyao86** [comment]
好的，尝试一呀
