### ISSUE TITLE
Tkinter Frameless-Window

### ISSUE THREAD

**Issue by DimasRulit** [zhiyiYo/PyQt-Frameless-Window#80]
Is it possible to use Tkinter to build a window + style using your add-on? I use customtkinter, which allows me to keep design costs to a minimum.

**Comment by zhiyiYo** [comment]
Sorry, I'm not familiar with TK and I don't know how to implement this requirement

**Comment by TotoWang-hhh** [comment]
> Sorry, I'm not familiar with TK and I don't know how to implement this requirement

I'm both using tkinter and qfluentwidgets recently. I searched sth and accidentally saw this closed issue seconds ago. I'm currently doing some experiments on tkinter frameless window.
