### ISSUE TITLE
最大化窗口后的意外发现

### ISSUE THREAD

**Issue by Xiaoxiao114514** [zhiyiYo/PyQt-Frameless-Window#81]
![Snipaste_2023-04-18_19-15-04](https://user-images.githubusercontent.com/98245750/232761083-4661c059-426a-469e-b221-e63699cfd223.png)
...当我使用 qframelesswindow.AcrylicWindow 时，我发现当窗口最大化时把鼠标移动到最右边鼠标会变成可拉伸样式，于是我好奇地拉了一下。结果就是上图。
（PyQt 新手）

**Comment by zhiyiYo** [comment]
还是别用亚克力窗口了，问题很多
