### ISSUE TITLE
通病

### ISSUE THREAD

**Issue by MrPython-XiaoXiao** [zhiyiYo/PyQt-Frameless-Window#84]
只要使用了 QFramelessWindow.AcrylicWindow。所创建的窗口在最大化后，窗口的最右侧是可以拖动的。
一旦拖动，就会发现窗口多出来的 8 个像素
有没有什么解决方法？

Mica
![Mica](https://user-images.githubusercontent.com/98245750/233078057-ae3a61c3-1c0a-4fce-a9c6-7e7e690d4e4b.png)

亚克力
![A_YKL](https://user-images.githubusercontent.com/98245750/233078095-93cdd3cd-8a51-4fbb-b209-91fe0ff541a4.png)

Aero
![Aero](https://user-images.githubusercontent.com/98245750/233078143-2976c422-04bc-4d01-a664-9d8a5ca6aa67.png)

**Comment by zhiyiYo** [comment]
@Xiaoxiao114514 
PyQt5分支的代码把拉伸区域移动到窗口外部了，可以试试吗？
