### ISSUE TITLE
加入QML控件之后窗口圆角变成直角了而且不能拉伸

### ISSUE THREAD

**Issue by Cijade** [zhiyiYo/PyQt-Frameless-Window#85]
**Environment**
 - OS: [e.g. Windows11]
 - DPI scaling: [e.g. 100%]
 - Python: [e.g. 3.9.16 64-bit]
 - PySide6.5.0

参考代码：https://blog.csdn.net/wenxingchen/article/details/127683645
![XE)F_U`)2IF1K0E{BPP4W0V](https://user-images.githubusercontent.com/26559370/233523152-81169a91-967d-4cf1-9652-bacbb052801e.png)

**Comment by zhiyiYo** [comment]
不会 QML 呀，咱也不知道怎么解决

**Comment by Cijade** [comment]
测试了原生QWidgt 添加QML没有出现这种情况，感觉是FramelessWindow类的问题
![image](https://user-images.githubusercontent.com/26559370/233523372-77a13993-bc07-47ec-a17b-83ad7b67c3f9.png)
