### ISSUE TITLE
又是一个关于窗口边框的问题

### ISSUE THREAD

**Issue by Xiaoxiao114514** [zhiyiYo/PyQt-Frameless-Window#86]
当我把 setMinimumSize 与 setMaximumSize 均填为 500，400 时按下最大化按钮就会有奇怪的现象。但PyQt 原生与 QFW 展现出了截然不同的性质：
QFM
![ikaja-dlziv](https://user-images.githubusercontent.com/98245750/233836423-3ed10cbc-21f1-4e17-a1d3-bcd2da477738.gif)
PyQt 原生
最大化按钮直接变成了不可用样式

**Comment by zhiyiYo** [comment]
最大尺寸与最小尺寸相同的时候窗口应该是固定大小的，所以标题栏最大化按钮会被禁用掉
