### ISSUE TITLE
Title Bar Button 的自定义

### ISSUE THREAD

**Issue by Xiaoxiao114514** [zhiyiYo/PyQt-Frameless-Window#87]
我个人希望 TitleBar 可以自定义按钮，比方说可以这样：
`...`
`self.setTitleBarButton(qframelesswindow.TitleBarButton.maximizeButton `
`                       | qframelesswindow.TitleBarButton.minimizeButton `
`                      | qframelesswindow.TitleBarButton.closeButton)`
`...`

**Comment by zhiyiYo** [comment]
把按钮隐藏一下不就行了吗？

**Comment by Cheukfung** [comment]
我猜测可能是需要添加自定义按钮，比如在三大按钮的左边添加darkmode的切换按钮，我就有这个需求，不过我是自己重写类加进去的
