### ISSUE TITLE
dialog在win7无法正常运行

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Frameless-Window#88]
错误提示：QWidgetWindow(0x4f9f4b8, name="DialogClassWindow") ( QScreen(0x4d47c28, name="\\\\.\\DISPLAY1") ): Attempt to set a scre
en on a child window.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/14865236/234271901-cc9eeac8-9942-4aa5-abab-3392c8f8aa52.png">
dialog/demo出错后直接卡死：
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14865236/234271997-3bf9db9b-0159-48b8-9da9-cf3dcef873e7.png">

**Comment by zhiyiYo** [comment]
v0.2.5会这样吗

**Comment by Cheukfung** [comment]
> v0.2.5会这样吗
会，现在就是0.2.5版本

**Comment by zhiyiYo** [comment]
examples/main_window.py 弹出的对话框会出错的话那就是这个库的问题了

**Comment by zhiyiYo** [comment]
v0.2.4 会有这个问题吗

**Comment by Cheukfung** [comment]
examples/main_window.py ，我从0.1.9测试到0.2.5，都会卡死

**Comment by zhiyiYo** [comment]
这就奇怪了，更早的版本呢

**Comment by Cheukfung** [comment]
目前定位到错误代码在windows/init.py文件的36行
```python
self.setWindowFlags(Qt.FramelessWindowHint |Qt.WindowMinMaxButtonsHint)
```
注释掉这句就能正常运行。
chatgpt的解释是这样的：

> 这个错误通常发生在 Windows 7 操作系统下，是由于在子窗口中设置了屏幕属性，而父窗口的屏幕属性与子窗口的屏幕属性不一致导致的。

**Comment by Cheukfung** [comment]
另外，改成
```python
self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint|Qt.WindowMinMaxButtonsHint)
```
也能运行

**Comment by zhiyiYo** [comment]
我记得之前 Win7 下会有一些问题，所以我才那样写的，参见 #28

**Comment by Cheukfung** [comment]
提pr了，这样写不会出现#28的问题，也能完美运行。
问题应该是在win7下，子窗口的属性和父窗口不一致，当传入parent的时候，把父窗口的windowFlags也设置给子窗口就可以了。
