### ISSUE TITLE
多个显示屏时拖动窗口切换所在显示屏或高DPI时无法正常拖拽窗口大小

### ISSUE THREAD

**Issue by XiaoYouChR** [zhiyiYo/PyQt-Frameless-Window#9]
如标题

这是自己写的修复方案:

```python
 def nativeEvent(self, eventType, message):
        """ 处理windows消息 """
        msg = MSG.from_address(message.__int__())
        if msg.message == win32con.WM_NCHITTEST:
            # 解决多屏下会出现鼠标一直为拖动状态的问题
            Pos = QCursor.pos()
            xPos, yPos = Pos.x() - self.x(), Pos.y() - self.y()

            w, h = self.width(), self.height()
            lx = xPos < self.BORDER_WIDTH
            rx = xPos + 3 > w - self.BORDER_WIDTH
            ty = yPos < self.BORDER_WIDTH
            by = yPos > h - self.BORDER_WIDTH

            if lx and ty:
                return True, win32con.HTTOPLEFT
            elif rx and by:
                return True, win32con.HTBOTTOMRIGHT
            elif rx and ty:
                return True, win32con.HTTOPRIGHT
            elif lx and by:
                return True, win32con.HTBOTTOMLEFT
            elif ty:
                return True, win32con.HTTOP
            elif by:
                return True, win32con.HTBOTTOM
            elif lx:
                return True, win32con.HTLEFT
            elif rx:
                return True, win32con.HTRIGHT

--snip--

```

**Comment by zhiyiYo** [comment]
我怀疑你的代码不是最新的🧐

**Comment by XiaoYouChR** [comment]
> 我怀疑你的代码不是最新的🧐

在最新的代码里面也出现了类似的问题

**Comment by XiaoYouChR** [comment]
![IMG_20220416_001455](https://user-images.githubusercontent.com/87308195/163594715-85f3a04f-bb0a-45da-8c99-4d6c5de6a535.jpg)

![IMG_20220416_001446](https://user-images.githubusercontent.com/87308195/163594722-e8346b1f-2aed-442e-ad1a-b92f5fdc4bad.jpg)

**Comment by zhiyiYo** [comment]
感谢回复，我这边没有多屏的测试条件，可以演示一下修改完代码之后，多屏+屏幕缩放125%的效果吗

**Comment by XiaoYouChR** [comment]
抱歉久等了！
此前我的计算机上并未安装视频录制软件。

[2022-04-16 00-43-40.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/8497009/2022-04-16.00-43-40.zip)

**Comment by XiaoYouChR** [comment]
> 抱歉久等了！ 此前我的计算机上并未安装视频录制软件。
> 
> [2022-04-16 00-43-40.zip](https://github.com/zhiyiYo/PyQt-Frameless-Window/files/8497009/2022-04-16.00-43-40.zip)

同时纠正一下我的问题，源代码在高分屏下并未出现问题！

**Comment by zhiyiYo** [comment]
看了一下你的缩放125%的操作，似乎没在 `app = QApplication(sys.argv)` 前面加上适配 DPI 缩放的代码：
```python
QApplication.setHighDpiScaleFactorRoundingPolicy( Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
```
然后  `rx = xPos + 3 > w - self.BORDER_WIDTH`  应该没必要+3，看了一下我的代码加了 9，会导致里右边框还有 9px 时就显示拖拽图标，改成 `rx = xPos  > w - self.BORDER_WIDTH` 就好了，其他代码用你的应该没啥问题。方便的话可以再测试一下 `多屏+100%缩放` 和 `多屏+125%` 缩放的情况吗，QQ 里面自带录屏功能也挺好用的，感激不尽~

**Comment by zhiyiYo** [comment]
我还看了一下你的下载器的代码，发现处理无边框窗口切换显示屏的代码被你移除了，不知道你的演示视频里面有没有加上这一句以及对应的槽函数。
![image](https://user-images.githubusercontent.com/65096819/163656967-e09ff262-661d-4e4b-96d9-85132a61a257.png)

**Comment by zhiyiYo** [comment]
已更新代码
