### ISSUE TITLE
FramelessDialog 与 Windows 贴靠布局

### ISSUE THREAD

**Issue by Xiaoxiao114514** [zhiyiYo/PyQt-Frameless-Window#91]
好吧，当我使用 FramelessDialog 时，它虽然不会再有最大化最小化按钮了，但是 Windows 贴靠布局仍然在发挥作用，
我现在需要实现贴靠布局的函数定义，找到它后，把它 pass 掉

**Comment by zhiyiYo** [comment]
移动窗口使用的是 Win32 API：
```python
        win32gui.ReleaseCapture()
        win32api.SendMessage(
            int(window.winId()),
            win32con.WM_SYSCOMMAND,
            win32con.SC_MOVE | win32con.HTCAPTION,
            0
        )
```

**Comment by Xiaoxiao114514** [comment]
在哪个文件里？

**Comment by zhiyiYo** [comment]
qframelesswindow/utils/win32_utils.py

**Comment by wsdtl** [comment]
self.setWindowFlags(Qt.WindowMinimizeButtonHint)   FramelessWindow窗口进行以上设置  停靠便不会在生效  之后可方向删除最大化

**Comment by zhiyiYo** [comment]
应该是加了 `win32con.WS_MAXIMIZEBOX` 标志导致的，移除这个标志就可以解决了

**Comment by zhiyiYo** [comment]
最新版本已修复此问题
