### ISSUE TITLE
SvgTitleBarButton中调用svg后图片变形

### ISSUE THREAD

**Issue by CofWMil** [zhiyiYo/PyQt-Frameless-Window#93]
![image](https://user-images.githubusercontent.com/130544123/236391203-7d7276bf-9259-40da-9cf4-35f304b2aff9.png)
![image](https://user-images.githubusercontent.com/130544123/236391436-63a42d2b-aed9-4b3c-a530-94739645c559.png)
原图是200X200的正六边形，但使用SvgTitleBarButton后就被压扁了

`class MyTitleBar(StandardTitleBar):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setting_pbt = SvgTitleBarButton(r'./images/icon/设置.svg', self)
        self.hBoxLayout.insertWidget(4, self.setting_pbt, 0, Qt.AlignRight)

class MainWindow(FramelessWindow):
    def __init__(self, user=None, client_connection=None):
        super().__init__()
        self.resize(1000, 800)
        self.setTitleBar(MyTitleBar(self))
        self.titleBar.raise_()
`

**Comment by zhiyiYo** [comment]
估计是你 svg 的 viewbox 没调好，需要是 46*32 的

**Comment by zhiyiYo** [comment]
然后再把 height 和 weight 调的差不多就行了

**Comment by CofWMil** [comment]
![image](https://user-images.githubusercontent.com/130544123/236418013-8d51c167-5673-444e-b3ff-399c7734c86d.png)
放在侧边栏是不会变形的，但在SvgTitleBarButton就有问题了

![image](https://user-images.githubusercontent.com/130544123/236419515-41ebea3b-1648-4e6c-9140-025d4eaf3be1.png)
![image](https://user-images.githubusercontent.com/130544123/236419662-9a1dd682-e112-44dd-bc4a-67715b3016b7.png)
我调成46*32后，它还是变形的，放到SvgTitleBarButton里就被拉长了，图片代码贴下面了

`<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1683267023291" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2384" xmlns:xlink="http://www.w3.org/1999/xlink" width="460" height="320"><path d="M878.08 466.944l-129.3824-253.0816a98.8672 98.8672 0 0 0-88.064-53.8624H366.08c-36.864 0-70.656 20.48-87.6544 53.1456l-132.096 253.0816a98.8672 98.8672 0 0 0 0 91.5456l132.096 253.0816a98.8672 98.8672 0 0 0 87.6544 53.1456h294.5536c37.1712 0 71.168-20.7872 88.064-53.8624l129.3824-253.1328a98.8672 98.8672 0 0 0 0-90.0096z m-72.3968 372.3264a162.8672 162.8672 0 0 1-145.0496 88.7296H366.08a162.8672 162.8672 0 0 1-144.384-87.552l-132.096-253.0816a162.8672 162.8672 0 0 1 0-150.7328l132.096-253.1328a162.8672 162.8672 0 0 1 144.384-87.5008h294.5536c61.184 0 117.1968 34.304 145.0496 88.7296l129.3824 253.1328c23.808 46.592 23.808 101.7344 0 148.2752l-129.3824 253.1328z" fill="#5A5A68" p-id="2385"></path><path d="M512 697.6a185.6 185.6 0 1 1 0-371.2 185.6 185.6 0 0 1 0 371.2z m0-64a121.6 121.6 0 1 0 0-243.2 121.6 121.6 0 0 0 0 243.2z" fill="#5A5A68" p-id="2386"></path></svg>`

**Comment by zhiyiYo** [comment]
viewbox 也要改
