### ISSUE TITLE
在macOS中，使用AcrylicWindow存在部分无法拖拽/关闭窗口的情况

### ISSUE THREAD

**Issue by gucheng599** [zhiyiYo/PyQt-Frameless-Window#94]
**Describe the bug**

**Environment**
 - OS: macOS 12.5.1
 - DPI scaling: 100%
 - Python: 3.8.16
 - PyQt5: PySide2==5.15.2.1

**To Reproduce**
Steps to reproduce the behavior(you can use GIF to demonstrate :):
1. 在使用pyside2时，打开examples中的login的例子（这个例子中使用到了AcrylicWindow类），搭配self.setupUi方法使用。会导致窗口无法使用拖拽。我猜想可能时与其中的部分代码冲突了。
2.当注释掉self.setupUi方法后 正常拖拽时的场景：
![2023-05-13 16 43 51](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/46436123/d37aea00-d25b-47e3-9f8e-bb93d7449adb)

3.当没有注释self.setupUi方法后 无法拖拽时的场景：
![2023-05-13 16 45 27](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/46436123/33aed5ea-669b-4b96-b577-30786c703fee)
**Code**

```python
# 使用的examples代码中的login的例子
# 同时继承AcrylicWindow与Ui_Form
class LoginWindow(AcrylicWindow, Ui_Form):

    def __init__(self):
        super().__init__()
        self.setupUi(self)  # 当注释掉这个setupUi后，窗口可以正常运行
```

**Comment by zhiyiYo** [comment]
macOS 没测试过，没有测试条件，还是换成 `FramelessWindow` 吧

**Comment by gucheng599** [comment]
> macOS 没测试过，没有测试条件，还是换成 `FramelessWindow` 吧

我调试了一下。
1.貌似是因为使用了QMacCocoaViewContainer绘制原生窗口，与UI_Form中的部分QT组件有冲突。
2.在我注释掉Ui_LoginWindow.py的`self.horizontalLayout.addWidget(self.label)` Line27后，就能够正常运行了。。我猜想可能是qt组件覆盖掉了原生组件的部分功能。但不太清楚其具体原因。
```python

class QMacCocoaViewContainer(QWidget):

    def __init__(self, view, parent=None):
        super().__init__(parent=parent)
        self.setAttribute(Qt.WA_NativeWindow)
```

效果图片：
![2023-05-14 14 35 30](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/46436123/0bc8c843-bf80-4604-b55a-3f0837972231)

**Comment by zhiyiYo** [comment]
acrylic window存在很多问题，Win10 上拖动和拉伸也会卡顿，建议不要使用
