### ISSUE TITLE
QMainWindow无法使用FramelessWindow

### ISSUE THREAD

**Issue by Aero80wd** [zhiyiYo/PyQt-Frameless-Window#95]
报错：
File "G:\pythonProject\gui.py", line 158, in setupUi
    MainWindow.setCentralWidget(self.centralwidget)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'main' object has no attribute 'setCentralWidget'. Did you mean: 'centralwidget'?

**Comment by zhiyiYo** [comment]
贴下最小复现代码吧
