### ISSUE TITLE
NonClient border reaches into the client are when the windows is maximized

### ISSUE THREAD

**Issue by UsYer** [zhiyiYo/PyQt-Frameless-Window#98]
**Describe the bug**
I noticed that the non client are (at least on the right side, the others I have not tested) reaching quite some pixels into the client are when the window is maximized.
I noticed because I have a button that is displayed while the cursor is inside its containing are.
But on the right window side the button disappears to early even though the cursor is visually still inside the containing are.

I found this code to be partially responsible:
```python
class WindowsFramelessWindowBase:
  ...
  def nativeEvent(self, eventType, message):
      ...
      if msg.message == win32con.WM_NCHITTEST and self._isResizeEnabled:
          pos = QCursor.pos()
          xPos = pos.x() - self.x()
          yPos = pos.y() - self.y()
          w, h = self.width(), self.height()
          # !! Here the NCHITTEST is extended into the client are even if the window is maximized !!
          # In my opinion the border width should be 0 here if we are maximized
          lx = xPos < self.BORDER_WIDTH
          rx = xPos > w - self.BORDER_WIDTH
          ty = yPos < self.BORDER_WIDTH
          by = yPos > h - self.BORDER_WIDTH
```

I would suggest something like this:
```python
      if msg.message == win32con.WM_NCHITTEST and self._isResizeEnabled:
          pos = QCursor.pos()
          xPos = pos.x() - self.x()
          yPos = pos.y() - self.y()
          w, h = self.width(), self.height()
          border_width = 0 if win_utils.isMaximized(msg.hWnd) or win_utils.isFullScreen(msg.hWnd) else self.BORDER_WIDTH
          lx = xPos < border_width
          rx = xPos > w - border_width
          ty = yPos < border_width
          by = yPos > h - border_width
```

**Environment**
 - OS: Windows10
 - DPI scaling: 200 %
 - Python: 3.10.6 64-bit]
 - PySide6: 6.3.2

**To Reproduce**
1. Maximize a FramelessWindow
2. Have something mark if you're still in client or non-client are.
Example gif:
![FramelessQtBug](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/627373/83d350a8-eb0b-4c5a-9ce4-e9ad828f58b2)

**Expected behavior**
I would have expected that that the client are is not affected when the window is maximized.

**Comment by zhiyiYo** [comment]
You are right! Thank you for this patch

**Comment by UsYer** [comment]
Great, thanks for fixing this!
