### ISSUE TITLE
在 QThread 子线程中进行某些循环会造成主线程 FramelessWindow 窗口卡顿

### ISSUE THREAD

**Issue by Zzaphkiel** [zhiyiYo/PyQt-Frameless-Window#99]
**问题描述**

您好，在我的代码中，需要在运行中实时判断某进程是否存在，我通过每隔一段时间在子线程中遍历 `psutil.process_iter()` 来实现，但是在这一子线程的遍历行为会导致主线程 `FramelessWindow` 的卡顿，最少代码示例如下：
``` python
import psutil
import sys

from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QThread
from qframelesswindow import FramelessWindow


class MainWindow(FramelessWindow):

    def __init__(self):
        super().__init__()

        self.listerner = ProcessListener(self)
        self.listerner.start()


class ProcessListener(QThread):

    def __init__(self, parent):
        super().__init__(parent)

    def run(self):
        while True:
            AFunctionTravelsProcessList()
            self.msleep(500)


def AFunctionTravelsProcessList():
    for _ in psutil.process_iter():
        pass


if __name__ == '__main__':
    app = QApplication(sys.argv)

    w = MainWindow()

    w.show()

    app.exec()
```

当拖动窗口（或窗口有其他动画效果）时，其每 500 毫秒会卡顿一次（符合 `self.msleep()` 的频率）：
![2023-05-31 14-00-40](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/60383222/96c1c578-ace1-4aa8-8420-166211b2021a)

我发现循环会在 `psutil.process_iter()` 中遍历约 300 个元素，便尝试在 `AFunctionTravelsProcessList()` 遍历其他内容，如：
``` python
def AFunctionTravelsProcessList():
    for _ in range(0, 300):
        pass
```
而如果这样做，GUI 窗口将不会再卡顿了。于是我尝试遍历更多的次数，如
``` python
def AFunctionTravelsProcessList():
    for _ in range(0, 2000000):
        pass
```
这样则又会卡顿。

然而，如果我不使用 `FramelessWindow` 而直接使用 `QWidget`，如
``` python
class MainWindow(QWidget):
# ...
```
那么以上的所有的遍历代码均不会导致窗口卡顿：
![2023-05-31 14-00-40_1](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/60383222/567f2e8e-b2b1-4996-a3ff-21fc8ff87265)
因此我判断可能是 `FramelessWindow` 导致了这一问题。

**环境**

 - OS: Windows 10, 21H2
 - DPI scaling: 100%
 - Python: 3.8.16 64-bit
 - PyQt5: 5.15.2
 - PyQt-Frameless-Window: 0.2.7

**预期的结果**

在子线程中进行的行为不应该导致主线程窗口的卡顿。

感谢您的回复。

**Comment by zhiyiYo** [comment]
我把framelesswindow的代码都注释了还是会卡🥲

**Comment by Zzaphkiel** [comment]
感谢您的及时回复。

> 我把framelesswindow的代码都注释了还是会卡🥲

抱歉我没太听懂您的意思，您是指您那里无论使用 `QWdiget` 还是 `FramelessWindow` 都会卡顿吗？我刚刚在一个别的环境下做出了同样的尝试，依旧是只有使用 `FramelessWindow` 会卡顿而使用 `QWidget` 则不会。环境如下：

- OS: Windows 11, 21H2
- DPI scaling: 125%
- Python: 3.8.11 64-bit
- PyQt5: 5.15.9
- PyQt-Frameless-Window: 0.2.7

我一直认为正常情况下子线程的行为应该是不会导致主线程 GUI 卡顿的，我想知道是什么导致了它的卡顿，又该怎样解决它呢？还是我的理解本身有问题？

如果暂时没有好的解决办法我可能需要换一种方式实现我的功能了😢

**Comment by zhiyiYo** [comment]
问题出在 `nativeEvent` 上，只要是重写了这个函数就会出现卡顿问题

**Comment by Zzaphkiel** [comment]
感谢您的回复。

> 问题出在 `nativeEvent` 上，只要是重写了这个函数就会出现卡顿问题

感觉是个难以解决的问题？

我放弃了遍历 `psutil.process_iter()` 而用了别的方法来检测进程状态，现在就不会卡顿了
``` python
import subprocess

def isProcessExists(processName):
    processes = subprocess.check_output("tasklist")
    return processName.encode('utf-8') in processes
```
